// AUTO-GENERATED by scripts/generate-activity-summaries.mjs — DO NOT EDIT.
// Regenerate with `npm run gen:summaries` (runs automatically via the prebuild hook).
/* eslint-disable */
import type { ActivitySummary } from '$lib/types/activity';
export const activitySummaries: ActivitySummary[] = [
	{
		"id": "ai-africa-symposium-kansas-2026",
		"title": "Panel on African history at the AI and Africa Symposium",
		"dateISO": "2026-09-16",
		"date": "16 September 2026",
		"year": 2026,
		"description": "Taking part in Panel I: African History at the University of Kansas AI and Africa Symposium, held on Zoom on 17 September 2026.",
		"tags": [
			"AI",
			"Digital Humanities",
			"African Studies",
			"African History",
			"African Literature",
			"Archives"
		],
		"type": "lecture",
		"panelType": "lecture",
		"url": "https://calendar.ku.edu/event/ai-and-africa-symposium",
		"image": "images/communications/ai-africa-symposium-kansas-2026.webp",
		"heroImage": {
			"src": "images/communications/ai-africa-symposium-kansas-2026-hero.webp",
			"alt": "Flyer for the AI and Africa Symposium, held on Zoom on 17 September 2026 from 10am to 1pm, organised by AAAS | KASC and African Digital Humanities at the University of Kansas. Panel I: African History with Frédérick Madore, Karen Ijumba and Fu’ad Lawal, moderated by Dr. Rahina Muazu. Panel II: African Writers Discuss AI with Mubanga Kalimamukwento, Ukamaka Olisakwe and Munyao Kilolo, moderated by Dr. Martha Ndakalako."
		}
	},
	{
		"id": "amira-launch-2026",
		"title": "Launch of the Africa Multiple Interactive Research Atlas (AMIRA)",
		"dateISO": "2026-06-11",
		"date": "11 June 2026",
		"year": 2026,
		"description": "The Africa Multiple Interactive Research Atlas (AMIRA) is now live. A major project I have worked on as Data Curator at the University of Bayreuth, it offers a central platform for exploring and visualising research data from the Cluster of Excellence Africa Multiple.",
		"heroImage": {
			"src": "images/activities/amira-launch-2026-hero.webp",
			"alt": "Screenshot of the Africa Multiple Interactive Research Atlas (AMIRA) homepage"
		},
		"image": "images/activities/amira-launch-2026.webp",
		"url": "https://data.africamultiple.uni-bayreuth.de/",
		"urlLabel": "Explore AMIRA",
		"tags": [
			"Digital Humanities",
			"African Studies",
			"Africa Multiple",
			"University of Bayreuth",
			"Data Curation",
			"Data Visualisation",
			"Metadata"
		],
		"type": "news",
		"panelType": "news"
	},
	{
		"id": "archives-algorithms-iwac-2025",
		"title": "From Archives to Algorithms: Uncovering Transregional Islamic Connections through the Islam West Africa Collection (IWAC)",
		"dateISO": "2025-09-11",
		"date": "11 September 2025",
		"year": 2025,
		"description": "Paper presented at the Eighth European Congress on World and Global History",
		"tags": [
			"Digital Humanities",
			"Global History",
			"Archives",
			"Algorithms",
			"Transregional History",
			"ENIUGH",
			"Conference",
			"IWAC",
			"Islam",
			"West Africa"
		],
		"type": "conference",
		"heroImage": {
			"src": "images/activities/ENIUGH-hero.webp",
			"alt": "Photo of Frédérick Madore, Mila Oiva, Gerben Zaagsma, and Kathleen Schlütter at the European Congress on World and Global History"
		},
		"panelType": "conference"
	},
	{
		"id": "author-meets-critic-faith-based-student-activism",
		"title": "Author Meets Critic: Religious Activism on Campuses in Togo and Benin",
		"dateISO": "2024-12-12",
		"date": "12 December 2024",
		"year": 2024,
		"description": "Panel discussion at the 67th Annual Meeting of the African Studies Association (ASA).",
		"tags": [
			"Conference",
			"ASA",
			"Book Launch",
			"Togo",
			"Benin",
			"Religious Activism",
			"Islam",
			"African Studies"
		],
		"panelType": "conference",
		"heroImage": {
			"src": "images/activities/asa-panel-discussion.webp",
			"alt": "Author Meets Critics panel at the African Studies Association annual meeting",
			"caption": "Panel discussion on religious activism at the ASA conference in Chicago"
		},
		"type": "conference"
	},
	{
		"id": "building-ai-pipelines-african-digital-collections",
		"title": "Building AI Pipelines for African Digital Collections: Lessons from the Islam West Africa Collection",
		"dateISO": "2025-12-05",
		"date": "5 December 2025",
		"year": 2025,
		"description": "Presentation to the ALMEDA team on AI pipelines for managing large-scale African digital collections.",
		"tags": [
			"AI",
			"Digital Humanities",
			"African Studies",
			"IWAC",
			"ALMEDA",
			"Talk",
			"West Africa",
			"Islam"
		],
		"type": "lecture",
		"panelType": "lecture",
		"heroImage": {
			"src": "images/activities/uppsala-2025-hero.webp",
			"alt": "Frédérick Madore presenting to the ALMEDA team at Uppsala University around a conference table with laptops and a screen displaying research data"
		}
	},
	{
		"id": "charting-new-territory-blogpost-2026",
		"title": "Blog post: Charting New Territory – Digital Humanities and AI in African Studies",
		"dateISO": "2026-03-31",
		"date": "31 March 2026",
		"year": 2026,
		"description": "Blog post co-authored with Vincent Hiribarren for Digital History Bielefeld, reflecting on the Hannover workshop on Digital Humanities and AI in African Studies.",
		"tags": [
			"Digital Humanities",
			"AI",
			"African Studies",
			"Workshop",
			"Blog Post",
			"Volkswagen Foundation"
		],
		"type": "publication",
		"panelType": "publication",
		"url": "https://digihistbie.hypotheses.org/1117",
		"image": "images/publications/digital-history-bielefeld.webp",
		"heroImage": {
			"src": "images/publications/digital-history-bielefeld-hero.webp",
			"alt": "Screenshot of the blog post on Digital History Bielefeld"
		}
	},
	{
		"id": "charting-new-territory-workshop-hannover",
		"title": "Charting New Territory: Digital Humanities and AI in African Studies Workshop, Hannover",
		"dateISO": "2026-02-16",
		"date": "16 February 2026",
		"year": 2026,
		"description": "Three-day workshop in Hannover bringing together 25 researchers from 16 countries to explore digital humanities and AI in African Studies, co-organised with Vincent Hiribarren and funded by the VolkswagenStiftung.",
		"heroImage": {
			"src": "images/activities/charting-new-territory-workshop-hannover-hero.webp",
			"alt": "Charting New Territory: Digital Humanities and AI in African Studies Workshop, Hannover",
			"caption": ""
		},
		"tags": [
			"Digital Humanities",
			"AI",
			"African Studies",
			"Workshop",
			"Volkswagen Foundation"
		],
		"type": "workshop",
		"panelType": "workshop"
	},
	{
		"id": "ciram-book-discussion-religious-activism-2025",
		"title": "Présentation-discussion de l'ouvrage \"Religious Activism on Campuses in Togo and Benin\"",
		"dateISO": "2025-11-03",
		"date": "3 November 2025",
		"year": 2025,
		"description": "Book discussion hosted by the Centre interdisciplinaire de recherche sur l'Afrique et le Moyen-Orient (CIRAM), Université Laval.",
		"tags": [
			"Book Launch",
			"CIRAM",
			"Université Laval",
			"Talk",
			"Togo",
			"Benin",
			"Religious Activism",
			"Islam"
		],
		"panelType": "lecture",
		"heroImage": {
			"src": "images/communications/ciram-2025-hero.webp",
			"alt": "Poster for an online book talk with Frédérick Madore on “Religious Activism on Campuses in Togo and Benin”, 6 Nov 2025"
		},
		"type": "lecture",
		"url": "https://www.ciram.hei.ulaval.ca/activite/discussion-autour-du-livre-religious-activism-on-campuses-in-togo-and-benin/"
	},
	{
		"id": "dga-roundtable-dormant-digital-collections-2026",
		"title": "Dormant Digital Collections, AI Triage: Lessons from the Islam West Africa Collection and Beyond",
		"dateISO": "2026-05-06",
		"date": "6 May 2026",
		"year": 2026,
		"description": "Invited talk for the Deutsche Gesellschaft für Asienforschung (DGA) roundtable on Digital Humanities and AI in regional studies, exploring how AI can turn scholars' dormant scan collections into active research instruments.",
		"tags": [
			"Digital Humanities",
			"AI",
			"IWAC",
			"Talk",
			"DGA",
			"ZMO",
			"Archives",
			"West Africa",
			"Islam"
		],
		"url": "https://asienforschung.de/events/roundtable-2-digital-humanities-und-kuenstliche-intelligenz-in-den-regionalwissenschaften/",
		"type": "lecture",
		"panelType": "lecture",
		"heroImage": {
			"src": "images/activities/dga-roundtable-2026-hero.webp",
			"alt": "Poster for the DGA-Roundtable on Digital Humanities and Artificial Intelligence in regional studies, 6 May 2026 at 17:30, hosted at ZMO Berlin and online via Zoom. Speaker: Dr. Frédérick Madore. Moderation: Dr. Max Kramer."
		}
	},
	{
		"id": "dh-ai-african-studies-ecas-panel",
		"title": "Digital Humanities (DH) and AI in African Studies: Opportunities, Challenges, and Decolonial Perspectives",
		"dateISO": "2024-10-14",
		"date": "14 October 2024",
		"year": 2024,
		"description": "Announcing the acceptance of the panel proposal 'Digital Humanities (DH) and AI in African Studies: Opportunities, Challenges, and Decolonial Perspectives' for ECAS 2025 in Prague.",
		"tags": [
			"ECAS",
			"Digital Humanities",
			"AI",
			"African Studies",
			"Conference",
			"Call for Papers",
			"Panel"
		],
		"image": "",
		"panelType": "conference",
		"heroImage": {
			"src": "images/activities/ECAS-2025.webp",
			"alt": "ECAS 2025 logo with the theme “African, Afropean, Afropolitan,” held in Prague, June 25-28, 2025.",
			"caption": ""
		},
		"type": "conference"
	},
	{
		"id": "dh-ai-african-studies-edited-volume",
		"title": "Call for Chapters: Digital Humanities and AI in African Studies",
		"dateISO": "2025-10-30",
		"date": "30 October 2025",
		"year": 2025,
		"description": "Call for chapter proposals for an edited volume on Digital Humanities and Artificial Intelligence in African Studies, to be published by Bielefeld University Press.",
		"tags": [
			"Digital Humanities",
			"AI",
			"African Studies",
			"Call for Papers"
		],
		"type": "publication",
		"pdfPath": "files/CfC-DH-and-AI-in-African-Studies.pdf",
		"pdfTitle": "Call for Chapters",
		"panelType": "publication"
	},
	{
		"id": "dh-ai-african-studies-stias-workshop",
		"title": "Call for Papers: Digital Humanities and Artificial Intelligence in African Studies: Towards Sustainable and Equitable Practices",
		"dateISO": "2026-03-24",
		"date": "24 March 2026",
		"year": 2026,
		"description": "Call for papers for a four-day workshop at the Stellenbosch Institute for Advanced Study (STIAS) in South Africa, 21–24 September 2026, co-organised with Vincent Hiribarren, Emmanuel Ngué Um, and Menno van Zaanen, and funded by the DFG Point Sud programme.",
		"heroImage": {
			"src": "images/communications/point-sud-logo.svg",
			"alt": "DFG Point Sud programme logo",
			"caption": ""
		},
		"tags": [
			"Digital Humanities",
			"AI",
			"African Studies",
			"Call for Papers",
			"Workshop",
			"DFG"
		],
		"type": "workshop",
		"panelType": "workshop"
	},
	{
		"id": "dh-digital-history-luxembourg-2026",
		"title": "AI through History, History through AI",
		"dateISO": "2026-06-17",
		"date": "17 June 2026",
		"year": 2026,
		"description": "Reflections on the Eighth Conference on Digital Humanities and Digital History in Luxembourg, where I presented the MCP server I built for the Islam West Africa Collection (IWAC).",
		"tags": [
			"Digital Humanities",
			"Digital History",
			"AI",
			"Large Language Models",
			"IWAC",
			"MCP",
			"Islam",
			"West Africa",
			"Conference",
			"Luxembourg"
		],
		"type": "conference",
		"url": "https://www.uni.lu/c2dh-en/events/ai-through-history-history-through-ai/",
		"urlLabel": "Conference website",
		"heroImage": {
			"src": "images/activities/dh-digital-history-luxembourg-2026-hero.webp",
			"alt": "The University of Luxembourg's Belval campus in Esch-sur-Alzette: a dark building bearing a vertical 'Maison du Nombre' sign faces a vivid red building across a paved plaza with a reflecting pool, under a clear blue sky.",
			"caption": "The University of Luxembourg's Belval campus in Esch-sur-Alzette, venue for the Eighth Conference on Digital Humanities and Digital History."
		},
		"panelType": "conference"
	},
	{
		"id": "digital-orientalist-review-2025",
		"title": "Anaïs Wion reviews the Islam West Africa Collection in The Digital Orientalist",
		"dateISO": "2025-09-23",
		"date": "23 September 2025",
		"year": 2025,
		"description": "Anaïs Wion's review of the Islam West Africa Collection published in The Digital Orientalist.",
		"tags": [
			"Digital Humanities",
			"IWAC",
			"Review",
			"AI",
			"West Africa",
			"Islam"
		],
		"panelType": "publication",
		"image": "images/activities/The-Digital-Orientalist.webp",
		"heroImage": {
			"src": "images/activities/The-Digital-Orientalist-hero.webp",
			"alt": "The Digital Orientalist review of the Islam West Africa Collection"
		},
		"type": "publication"
	},
	{
		"id": "ecas-panel-report",
		"title": "Digital Humanities and AI in African Studies: Insights from ECAS 2025",
		"dateISO": "2025-06-26",
		"date": "26 June 2025",
		"year": 2025,
		"description": "Summary report of the ECAS 2025 panel on Digital Humanities and AI in African Studies.",
		"tags": [
			"ECAS",
			"Digital Humanities",
			"AI",
			"African Studies",
			"Conference",
			"Panel",
			"IWAC"
		],
		"image": "",
		"panelType": "conference",
		"heroImage": {
			"src": "images/activities/ECAS-2025.webp",
			"alt": "ECAS 2025 logo with the theme “African, Afropean, Afropolitan,” held in Prague, June 25-28, 2025.",
			"caption": ""
		},
		"type": "conference"
	},
	{
		"id": "ecole-nationale-des-chartes-visit-2025",
		"title": "Visit to the École nationale des chartes",
		"dateISO": "2025-05-22",
		"date": "22 May 2025",
		"year": 2025,
		"description": "Visited École nationale des chartes in Paris on the invitation of Vincent Jolivet.",
		"tags": [
			"École nationale des chartes",
			"Talk",
			"Digital Humanities",
			"AI",
			"Computational Methods",
			"IWAC",
			"West Africa",
			"Islam"
		],
		"heroImage": {
			"src": "images/activities/ecole-nationale-des-chartes.webp",
			"alt": "École nationale des chartes"
		},
		"type": "lecture"
	},
	{
		"id": "ehess-paris-lecture-series-2025",
		"title": "Lecture Series at EHESS, Paris",
		"dateISO": "2025-05-12",
		"date": "12 May 2025",
		"year": 2025,
		"description": "A series of four public talks at EHESS, Paris, in May 2025, exploring the histories of Islam and religious pluralism in francophone West Africa using digital humanities methods.",
		"tags": [
			"EHESS",
			"Francophone West Africa",
			"Islam",
			"Religious Pluralism",
			"Digital Humanities",
			"Talk",
			"West Africa",
			"Togo",
			"Benin",
			"Burkina Faso",
			"Côte d'Ivoire",
			"African Studies",
			"IWAC"
		],
		"image": "images/communications/EHESS-2025.webp",
		"heroImage": {
			"src": "images/communications/EHESS-2025-hero.webp",
			"alt": "Promotional flyer for Frédérick Madore's May 2025 lecture series at EHESS, Paris, featuring talks on Islam in West Africa, digital humanities, religious coexistence, and student activism."
		},
		"pdfPath": "files/prog-professeurs-invites_2024-2025_madore.pdf",
		"pdfTitle": "Flyer",
		"type": "lecture"
	},
	{
		"id": "etablir-une-faitiere-islamique",
		"title": "Établir une faîtière islamique à l'échelle nationale: le cas de 4 pays d'Afrique de l'Ouest francophone",
		"dateISO": "2025-03-04",
		"date": "4 March 2025",
		"year": 2025,
		"description": "Comparative analysis of national Islamic umbrella organisations in four West African countries.",
		"tags": [
			"Workshop",
			"Benin",
			"Burkina Faso",
			"Côte d'Ivoire",
			"Togo",
			"Islam",
			"West Africa"
		],
		"panelType": "workshop",
		"heroImage": {
			"src": "images/activities/puidoux.webp",
			"alt": "Crêt-Bérard Monastery",
			"caption": "Crêt-Bérard Monastery"
		},
		"pdfPath": "files/Programme_Atelier-Cret-Berard.pdf",
		"pdfTitle": "Programme",
		"type": "workshop"
	},
	{
		"id": "for-whom-for-what-purpose-publication-2026",
		"title": "New publication: For Whom and For What Purpose? A Position Paper on Digital Humanities and AI in African Studies",
		"dateISO": "2026-09-09",
		"date": "9 September 2026",
		"year": 2026,
		"description": "Our collective position paper on digital humanities and AI in African Studies is now freely available in the ZMO Programmatic Texts series.",
		"tags": [
			"Digital Humanities",
			"AI",
			"African Studies",
			"Publication",
			"Volkswagen Foundation"
		],
		"type": "publication",
		"panelType": "publication",
		"url": "https://doi.org/10.58144/20260827-000",
		"image": "images/publications/for-whom-for-what-purpose-2026.webp",
		"heroImage": {
			"src": "images/publications/for-whom-for-what-purpose-2026.webp",
			"alt": "Cover of For Whom and For What Purpose? A Position Paper on Digital Humanities and AI in African Studies, ZMO Programmatic Texts 16"
		}
	},
	{
		"id": "humanistica-conference-2025-dakar",
		"title": "Humanistica Conference 2025 - Dakar",
		"dateISO": "2025-04-21",
		"date": "21 April 2025",
		"year": 2025,
		"description": "Attending and presenting at the Humanistica 2025 conference in Dakar, focusing on Digital Humanities and AI.",
		"tags": [
			"Digital Humanities",
			"AI",
			"IWAC",
			"Conference",
			"Humanistica",
			"African Studies",
			"West Africa"
		],
		"url": "",
		"image": "images/activities/humanistica-2025-dakar.webp",
		"heroImage": {
			"src": "images/activities/humanistica-2025-dakar-hero.webp",
			"alt": "Humanistica 2025 conference in Dakar",
			"caption": ""
		},
		"type": "conference"
	},
	{
		"id": "humanites-numeriques-ia-etudes-africaines-reaf-2026",
		"title": "Humanités numériques (DH) et IA dans les études africaines - REAF 2026",
		"dateISO": "2025-09-29",
		"date": "29 September 2025",
		"year": 2025,
		"description": "Call for papers for the panel \"Humanités numériques (DH) et IA dans les études africaines\" at the 9th Rencontre des Études Africaines en France (REAF) 2026.",
		"tags": [
			"REAF",
			"Digital Humanities",
			"AI",
			"Methodology",
			"Panel",
			"Call for Papers",
			"African Studies",
			"Conference"
		],
		"type": "conference",
		"image": "images/communications/reaf-2026.webp",
		"heroImage": {
			"src": "images/communications/reaf-2026-hero.webp",
			"alt": "9ème édition Rencontres des Études Africaines en France"
		},
		"pdfPath": "files/humanites-numeriques-ia-etudes-africaines-reaf-2026.pdf",
		"pdfTitle": "Appel à propositions - Humanités numériques (DH) et IA et dans les études africaines (REAF 2026)",
		"panelType": "conference"
	},
	{
		"id": "islams-peripheries-erlangen-seminar-2026",
		"title": "Presenting \"Islam's Peripheries\" in the \"Digital History in/of Central Asia and the South Caucasus\" Seminar",
		"dateISO": "2026-06-29",
		"date": "29 June 2026",
		"year": 2026,
		"type": "lecture",
		"description": "Aksana Ismailbekova and I introduced our VolkswagenStiftung-funded project on AI and Islamic archives in West Africa and Central Asia in the \"Digital History in/of Central Asia and the South Caucasus\" seminar series at Friedrich-Alexander-Universität Erlangen-Nürnberg.",
		"tags": [
			"Volkswagen Foundation",
			"Digital Humanities",
			"AI",
			"Large Language Models",
			"IWAC",
			"Islam",
			"West Africa",
			"Central Asia",
			"Archives",
			"Erlangen"
		],
		"url": "https://www.osteuropa.phil.fau.de/digital-history-seminars/",
		"urlLabel": "Seminar Series Website",
		"additionalUrls": [
			{
				"label": "Presentation Slides",
				"url": "https://slides.frederickmadore.com/talks/2026-06-29-erlangen-islam-peripheries/"
			}
		],
		"image": "images/communications/islam-peripheries-dh-ai-west-africa-central-asia-2026.webp",
		"heroImage": {
			"src": "images/communications/islam-peripheries-dh-ai-west-africa-central-asia-2026-hero.webp",
			"alt": "Poster for the seminar series “Digital History in/of Central Asia and the South Caucasus,” advertising the talk “Islam's ‘Peripheries’: Digital Humanities, Algorithmic Analysis, and AI in West Africa and Central Asia” by Dr. Aksana Ismailbekova (Leibniz-Zentrum Moderner Orient, Berlin) and Dr. Frédérick Madore (University of Bayreuth) on 29 June at 14:00 CET. Portraits of the two speakers appear on the right, with the Max Weber Stiftung and Friedrich-Alexander-Universität Erlangen-Nürnberg (FAU) logos along the top.",
			"caption": "Poster for the talk in the “Digital History in/of Central Asia and the South Caucasus” seminar series at Friedrich-Alexander-Universität Erlangen-Nürnberg."
		},
		"panelType": "lecture"
	},
	{
		"id": "religiosity-africa-campuses-oa",
		"title": "“Religiosity on University Campuses in Africa: Trends and Experiences” now in open-access",
		"dateISO": "2024-11-12",
		"date": "12 November 2024",
		"year": 2024,
		"description": "The edited volume 'Religiosity on University Campuses in Africa: Trends and Experiences', co-edited with Abdoulaye Sounaye, is now available in open access.",
		"tags": [
			"Publication",
			"Remoboko",
			"Open Access",
			"Religious Activism",
			"African Studies",
			"Islam"
		],
		"panelType": "publication",
		"image": "",
		"heroImage": {
			"src": "images/publications/religiosity-university-campuses.webp",
			"alt": "Book cover of Religiosity on University Campuses in Africa, edited by Abdoulaye Sounaye and Frédérick Madore.",
			"caption": ""
		},
		"type": "publication"
	},
	{
		"id": "religious-activism-campuses-review-fall-2025",
		"title": "Macodou Fall's review of 'Religious Activism on Campuses in Togo and Benin'",
		"dateISO": "2026-01-14",
		"date": "14 January 2026",
		"year": 2026,
		"description": "Grateful that my book Religious Activism on Campuses in Togo and Benin has been reviewed by Macodou Fall in Research Africa Reviews.",
		"tags": [
			"Book Review",
			"Religious Activism",
			"Togo",
			"Benin",
			"Publication",
			"Islam",
			"West Africa"
		],
		"panelType": "publication",
		"heroImage": {
			"src": "images/activities/research-africa-reviews-hero.webp",
			"alt": "Screenshot of Research Africa Reviews journal website showing Volume 9, Issue 3 - December 2025"
		},
		"type": "publication",
		"url": "https://researchafrica.duke.edu/sites/default/files/-5-7-Religious-Activism-on-Campuses-in-Togo-and-Benin-Issue3-2025.pdf"
	},
	{
		"id": "religious-activism-campuses-review-thompson-2026",
		"title": "K.D. Thompson's review of 'Religious Activism on Campuses in Togo and Benin'",
		"dateISO": "2026-01-28",
		"date": "28 January 2026",
		"year": 2026,
		"description": "K.D. Thompson reviewed my book Religious Activism on Campuses in Togo and Benin in The Journal of Modern African Studies, describing it as 'a vital contribution to our understanding of West African faith-based student associations'.",
		"tags": [
			"Book Review",
			"Religious Activism",
			"Togo",
			"Benin",
			"Publication",
			"Islam",
			"West Africa"
		],
		"panelType": "publication",
		"heroImage": {
			"src": "images/activities/jmas-review-hero.webp",
			"alt": "Screenshot of The Journal of Modern African Studies cover showing Volume 63, Issue 4 - December 2025"
		},
		"type": "publication",
		"url": "https://doi.org/10.1017/S0022278X25101195"
	},
	{
		"id": "religious-activism-on-campuses-in-togo-and-benin",
		"title": "Religious Activism on Campuses in Togo and Benin: Christian and Muslim Students Navigating Authoritarianism and Laïcité, 1970-2023",
		"dateISO": "2025-03-21",
		"date": "21 March 2025",
		"year": 2025,
		"description": "New book publication based on research conducted at Leibniz-Zentrum Moderner Orient since 2021.",
		"tags": [
			"Publication",
			"Remoboko",
			"Togo",
			"Benin",
			"Religious Activism",
			"Islam",
			"Open Access",
			"Book Launch"
		],
		"panelType": "publication",
		"heroImage": {
			"src": "images/activities/De-Gruyter-ZMO.webp",
			"alt": "Book cover of Religiosity on University Campuses in Africa, edited by Abdoulaye Sounaye and Frédérick Madore.",
			"caption": "Published March 2025 by De Gruyter"
		},
		"type": "publication"
	},
	{
		"id": "repenser-categorisation-religieuse-benin-publication",
		"title": "Publication of 'Repenser la catégorisation religieuse à partir du Bénin, terre du Vodun'",
		"dateISO": "2026-03-10",
		"date": "10 March 2026",
		"year": 2026,
		"description": "Publication of the edited volume L'Afrique des religions à l'épreuve des chiffres et des catégorisations, featuring a chapter co-authored with Fiacre Anato on the limits of religious categorisations in Beninese censuses and surveys.",
		"tags": [
			"Publication",
			"Benin",
			"Religion",
			"West Africa"
		],
		"type": "publication",
		"panelType": "publication",
		"image": "images/publications/repenser-categorisation-religieuse-benin.webp",
		"heroImage": {
			"src": "images/publications/repenser-categorisation-religieuse-benin.webp",
			"alt": "Cover of L'Afrique des religions à l'épreuve des chiffres et des catégorisations"
		}
	},
	{
		"id": "repenser-categorisation-religieuse-benin",
		"title": "Repenser la catégorisation religieuse à partir du Bénin, terre du vodun",
		"dateISO": "2024-12-05",
		"date": "5 December 2024",
		"year": 2024,
		"description": "Presented a paper with Fiacre Anato at the workshop L'Afrique des religions à l'épreuve des chiffres et des catégorisations at the Université Paris Cité. Examined religious categorisation dynamics in Benin, highlighting the tension between Vodun's statistical decline and its cultural vitality.",
		"tags": [
			"Workshop",
			"Benin",
			"Religion",
			"Islam",
			"West Africa"
		],
		"type": "workshop"
	},
	{
		"id": "stias-dh-ai-workshop-2026",
		"title": "Heading to Stellenbosch for the workshop on digital humanities and AI in African studies",
		"dateISO": "2026-09-18",
		"date": "18 September 2026",
		"year": 2026,
		"description": "The workshop \"Digital Humanities and Artificial Intelligence in African Studies: Towards Sustainable and Equitable Practices\" runs at the Stellenbosch Institute for Advanced Study from 21 to 24 September 2026. Presentations are streamed live on Teams with simultaneous French–English translation.",
		"tags": [
			"Digital Humanities",
			"AI",
			"African Studies",
			"Workshop",
			"Sustainability",
			"Equity",
			"DFG",
			"STIAS"
		],
		"type": "workshop",
		"panelType": "workshop",
		"url": "https://fmadore.github.io/stias-dh-ai-workshop-2026/",
		"urlLabel": "Workshop Website",
		"image": "images/communications/point-sud-logo.svg",
		"heroImage": {
			"src": "images/communications/point-sud-logo.svg",
			"alt": "DFG Point Sud programme logo",
			"caption": ""
		}
	},
	{
		"id": "tracing-islamic-knowledge-production",
		"title": "Tracing Islamic Knowledge Production in Francophone West African Newspapers (1990-Present)",
		"dateISO": "2024-12-02",
		"date": "2 December 2024",
		"year": 2024,
		"description": "Presented findings on Islamic knowledge production in Francophone West Africa at the ZMO workshop \"Perspectives in Motion: Conceptual Fields from the Global South\". Examined how Muslim intellectuals navigate multiple epistemologies using a corpus of 1,500 Islamic periodicals.",
		"tags": [
			"Workshop",
			"Digital Humanities",
			"Côte d'Ivoire",
			"ZMO",
			"Islam",
			"West Africa",
			"Benin",
			"Burkina Faso",
			"Togo",
			"IWAC"
		],
		"image": "",
		"panelType": "workshop",
		"heroImage": {
			"src": "images/activities/tracing-islamic-knowledge-production.webp",
			"alt": "Bar chart of 204 articles mentioning intégrisme by country and year (1979-2019), peaking in Côte d'Ivoire in the early 1990s.",
			"caption": ""
		},
		"pdfPath": "files/perspectives-in-motion-programme.pdf",
		"pdfTitle": "Workshop programme",
		"type": "workshop"
	},
	{
		"id": "volkswagen-foundation-grant-islams-peripheries",
		"title": "VolkswagenStiftung grant: Islam's 'Peripheries': Digital Humanities, Algorithmic Analysis, and AI in West Africa and Central Asia",
		"date": "10 December 2025",
		"dateISO": "2025-12-10",
		"year": 2025,
		"type": "grant",
		"heroImage": {
			"src": "images/activities/VolkswagenStiftung-logo.webp",
			"alt": "VolkswagenStiftung logo"
		},
		"description": "Awarded a grant under the Volkswagen Foundation's \"Open Up\" programme for a collaboration with Aksana Ismailbekova on AI-driven comparative history of Islamic archives in West Africa and Central Asia.",
		"tags": [
			"Grant",
			"Digital Humanities",
			"AI",
			"West Africa",
			"Central Asia",
			"Volkswagen Foundation",
			"Islam",
			"IWAC",
			"Archives",
			"ZMO"
		]
	},
	{
		"id": "volkswagenstiftung-dh-ai-african-studies-workshop-2026",
		"title": "VolkswagenStiftung grant for “Charting New Territory: Digital Humanities and AI in African Studies”",
		"dateISO": "2025-08-11",
		"date": "11 August 2025",
		"year": 2025,
		"description": "With Vincent Hiribarren, I received funding from the VolkswagenStiftung to organise a scoping workshop (18-20 Feb 2026, Herrenhausen Palace, Hanover) on DH and AI in African Studies.",
		"tags": [
			"Volkswagen Foundation",
			"Grant",
			"Workshop",
			"Digital Humanities",
			"AI",
			"African Studies"
		],
		"panelType": "grant",
		"image": "",
		"heroImage": {
			"src": "images/activities/VolkswagenStiftung-logo.webp",
			"alt": "VolkswagenStiftung logo",
			"caption": ""
		},
		"type": "grant"
	},
	{
		"id": "volkswagenstiftung-open-up-kickoff-2026",
		"title": "Presenting \"Islam's Peripheries\" at the VolkswagenStiftung \"Open Up\" Kick-Off Event",
		"dateISO": "2026-03-05",
		"date": "5 March 2026",
		"year": 2026,
		"type": "presentation",
		"description": "Aksana Ismailbekova and I presented our project \"Islam's 'Peripheries'\" at the VolkswagenStiftung \"Open Up\" kick-off event at Herrenhausen Palace in Hannover.",
		"tags": [
			"Volkswagen Foundation",
			"Digital Humanities",
			"AI",
			"West Africa",
			"Central Asia",
			"Islam",
			"IWAC",
			"Presentation",
			"Hannover"
		],
		"heroImage": {
			"src": "images/activities/volkswagenstiftung-open-up-kickoff-2026-hero.webp",
			"alt": "Frédérick Madore and Aksana Ismailbekova presenting their project at the VolkswagenStiftung \"Open Up\" kick-off event at Herrenhausen Palace in Hannover"
		}
	},
	{
		"id": "when-ai-meets-the-archive-sadilar-2025",
		"title": "When AI Meets the Archive: Transforming the Islam West Africa Collection with Large Language Models",
		"dateISO": "2025-08-20",
		"date": "20 August 2025",
		"year": 2025,
		"description": "Invited lecture at the SADiLaR Digital Humanities colloquia exploring how large language models can transform vast archival collections into more navigable resources.",
		"tags": [
			"Digital Humanities",
			"AI",
			"IWAC",
			"Large Language Models",
			"Talk",
			"SADiLaR",
			"West Africa",
			"Islam",
			"Archives"
		],
		"url": "https://sadilar.org/en/dh-colloquium/",
		"additionalUrls": [
			{
				"label": "Video Recording",
				"url": "https://youtu.be/OhbPYA4_URo"
			}
		],
		"image": "images/communications/SADILAR.webp",
		"heroImage": {
			"src": "images/communications/SADILAR-hero.webp",
			"alt": "Poster for the SADiLaR DH Colloquium on 20 August 2025 at 10:00 SAST. Title reads: \"When AI Meets the Archive: Transforming the Islam West Africa Collection with Large Language Models.\" Speaker: Frédérick Madore. The right side features a digital illustration of binary code with document icons connected by lines and a large magnifying glass."
		},
		"type": "lecture"
	},
	{
		"id": "zmo-farewell-bayreuth-2025",
		"title": "Farewell to ZMO and New Beginnings at the University of Bayreuth",
		"dateISO": "2025-12-18",
		"date": "18 December 2025",
		"year": 2025,
		"description": "After five years at ZMO, I am moving to the Africa Multiple Cluster of Excellence at the University of Bayreuth as a data curator.",
		"heroImage": {
			"src": "images/activities/zmo-farewell-hero.webp",
			"alt": "The main entrance of the Leibniz-Zentrum Moderner Orient (ZMO) building in Berlin"
		},
		"tags": [
			"Career",
			"ZMO",
			"University of Bayreuth",
			"Africa Multiple",
			"Digital Humanities",
			"Data Curation",
			"African Studies"
		],
		"type": "career",
		"panelType": "event"
	},
	{
		"id": "zmo-kitchen-talks-podcast-2025",
		"title": "ZMO Kitchen Talks Podcast Recording",
		"dateISO": "2025-11-21",
		"date": "21 November 2025",
		"year": 2025,
		"description": "Joined Elisa Nobel-Dilaty on the ZMO \"Kitchen Talks\" podcast to discuss the Islam in West Africa Collection and potential and pitfalls of AI in African and Islamic studies.",
		"tags": [
			"Podcast",
			"AI",
			"African Studies",
			"Islamic Studies",
			"Digital Humanities",
			"ZMO",
			"IWAC",
			"West Africa",
			"Islam"
		],
		"image": "images/communications/zmo-kitchen-talks-podcast-2025.webp",
		"heroImage": {
			"src": "images/communications/zmo-kitchen-talks-podcast-2025.webp",
			"alt": "Frédérick Madore and Elisa Nobel-Dilaty sitting at a table with microphones and headphones in a recording studio for the ZMO Kitchen Talks podcast."
		},
		"type": "podcast",
		"panelType": "media"
	}
];
