// AUTO-GENERATED by scripts/generate-analysis-summaries.mjs — DO NOT EDIT.
// Regenerate with `npm run gen:analysis` (runs automatically via the prebuild hook).
/* eslint-disable */
import type { NgramFrequency, WordFrequency } from '$lib/types';

/**
 * The three fixed views of the full-text corpus that /publications/visualisations
 * draws: the 100-term cloud and the 30 commonest two-word phrases, for the
 * whole corpus and for each analysed language. None of it varies with anything
 * the reader can do, so it is a fact about the record rather than a computation
 * the browser should repeat over 306 KiB of frequencies.
 */
export const corpusSummary: {
	/** Publications with a full-text analysis, whatever their language. */
	publicationCount: number;
	/** Publications behind each filter; `all` is the two languages together. */
	analysed: { all: number; en: number; fr: number };
	wordCloud: { all: WordFrequency[]; en: WordFrequency[]; fr: WordFrequency[] };
	bigrams: { all: NgramFrequency[]; en: NgramFrequency[]; fr: NgramFrequency[] };
} = {
	"publicationCount": 27,
	"analysed": {
		"all": 27,
		"en": 16,
		"fr": 11
	},
	"wordCloud": {
		"all": [
			{
				"word": "islam",
				"count": 1657
			},
			{
				"word": "association",
				"count": 1400
			},
			{
				"word": "student",
				"count": 1276
			},
			{
				"word": "musulman",
				"count": 1212
			},
			{
				"word": "university",
				"count": 1178
			},
			{
				"word": "togo",
				"count": 1110
			},
			{
				"word": "muslim",
				"count": 1078
			},
			{
				"word": "religious",
				"count": 1063
			},
			{
				"word": "imam",
				"count": 953
			},
			{
				"word": "islamic",
				"count": 822
			},
			{
				"word": "national",
				"count": 798
			},
			{
				"word": "islamique",
				"count": 770
			},
			{
				"word": "africa",
				"count": 736
			},
			{
				"word": "social",
				"count": 699
			},
			{
				"word": "public",
				"count": 698
			},
			{
				"word": "religieux",
				"count": 672
			},
			{
				"word": "campus",
				"count": 645
			},
			{
				"word": "political",
				"count": 618
			},
			{
				"word": "côte",
				"count": 598
			},
			{
				"word": "religion",
				"count": 595
			},
			{
				"word": "benin",
				"count": 537
			},
			{
				"word": "organisation",
				"count": 521
			},
			{
				"word": "leader",
				"count": 499
			},
			{
				"word": "afrique",
				"count": 497
			},
			{
				"word": "lomé",
				"count": 487
			},
			{
				"word": "new",
				"count": 480
			},
			{
				"word": "presse",
				"count": 474
			},
			{
				"word": "country",
				"count": 439
			},
			{
				"word": "jec",
				"count": 438
			},
			{
				"word": "année",
				"count": 425
			},
			{
				"word": "muslims",
				"count": 407
			},
			{
				"word": "politique",
				"count": 407
			},
			{
				"word": "radio",
				"count": 402
			},
			{
				"word": "african",
				"count": 401
			},
			{
				"word": "group",
				"count": 396
			},
			{
				"word": "community",
				"count": 387
			},
			{
				"word": "president",
				"count": 379
			},
			{
				"word": "communauté",
				"count": 375
			},
			{
				"word": "jeune",
				"count": 373
			},
			{
				"word": "ouagadougou",
				"count": 357
			},
			{
				"word": "woman",
				"count": 353
			},
			{
				"word": "bénin",
				"count": 343
			},
			{
				"word": "aeemb",
				"count": 339
			},
			{
				"word": "education",
				"count": 335
			},
			{
				"word": "état",
				"count": 335
			},
			{
				"word": "member",
				"count": 333
			},
			{
				"word": "young",
				"count": 330
			},
			{
				"word": "grand",
				"count": 330
			},
			{
				"word": "faith",
				"count": 326
			},
			{
				"word": "musulmane",
				"count": 319
			},
			{
				"word": "base",
				"count": 313
			},
			{
				"word": "mouvement",
				"count": 312
			},
			{
				"word": "movement",
				"count": 303
			},
			{
				"word": "figure",
				"count": 300
			},
			{
				"word": "pays",
				"count": 299
			},
			{
				"word": "étudiant",
				"count": 296
			},
			{
				"word": "development",
				"count": 294
			},
			{
				"word": "state",
				"count": 290
			},
			{
				"word": "mosquée",
				"count": 288
			},
			{
				"word": "nouveau",
				"count": 285
			},
			{
				"word": "cerfi",
				"count": 273
			},
			{
				"word": "journal",
				"count": 272
			},
			{
				"word": "support",
				"count": 268
			},
			{
				"word": "role",
				"count": 266
			},
			{
				"word": "study",
				"count": 266
			},
			{
				"word": "activity",
				"count": 264
			},
			{
				"word": "mosque",
				"count": 261
			},
			{
				"word": "include",
				"count": 261
			},
			{
				"word": "université",
				"count": 261
			},
			{
				"word": "medium",
				"count": 246
			},
			{
				"word": "challenge",
				"count": 246
			},
			{
				"word": "conversation",
				"count": 245
			},
			{
				"word": "lead",
				"count": 241
			},
			{
				"word": "président",
				"count": 241
			},
			{
				"word": "africain",
				"count": 240
			},
			{
				"word": "activism",
				"count": 239
			},
			{
				"word": "hadj",
				"count": 234
			},
			{
				"word": "youth",
				"count": 233
			},
			{
				"word": "year",
				"count": 232
			},
			{
				"word": "francophone",
				"count": 232
			},
			{
				"word": "access",
				"count": 229
			},
			{
				"word": "christian",
				"count": 229
			},
			{
				"word": "dir",
				"count": 226
			},
			{
				"word": "pouvoir",
				"count": 222
			},
			{
				"word": "life",
				"count": 221
			},
			{
				"word": "ivoire",
				"count": 220
			},
			{
				"word": "internet",
				"count": 218
			},
			{
				"word": "sermon",
				"count": 215
			},
			{
				"word": "church",
				"count": 214
			},
			{
				"word": "press",
				"count": 213
			},
			{
				"word": "face",
				"count": 210
			},
			{
				"word": "média",
				"count": 209
			},
			{
				"word": "authority",
				"count": 205
			},
			{
				"word": "sunnite",
				"count": 201
			},
			{
				"word": "site",
				"count": 200
			},
			{
				"word": "sphère",
				"count": 200
			},
			{
				"word": "cotonou",
				"count": 199
			},
			{
				"word": "people",
				"count": 197
			},
			{
				"word": "calavi",
				"count": 196
			},
			{
				"word": "change",
				"count": 195
			}
		],
		"en": [
			{
				"word": "student",
				"count": 1276
			},
			{
				"word": "university",
				"count": 1120
			},
			{
				"word": "muslim",
				"count": 1074
			},
			{
				"word": "religious",
				"count": 1048
			},
			{
				"word": "togo",
				"count": 946
			},
			{
				"word": "association",
				"count": 842
			},
			{
				"word": "islamic",
				"count": 778
			},
			{
				"word": "islam",
				"count": 732
			},
			{
				"word": "political",
				"count": 615
			},
			{
				"word": "africa",
				"count": 588
			},
			{
				"word": "campus",
				"count": 579
			},
			{
				"word": "benin",
				"count": 527
			},
			{
				"word": "national",
				"count": 523
			},
			{
				"word": "new",
				"count": 480
			},
			{
				"word": "leader",
				"count": 471
			},
			{
				"word": "social",
				"count": 453
			},
			{
				"word": "country",
				"count": 439
			},
			{
				"word": "lomé",
				"count": 415
			},
			{
				"word": "muslims",
				"count": 407
			},
			{
				"word": "group",
				"count": 396
			},
			{
				"word": "community",
				"count": 387
			},
			{
				"word": "côte",
				"count": 382
			},
			{
				"word": "president",
				"count": 379
			},
			{
				"word": "religion",
				"count": 376
			},
			{
				"word": "woman",
				"count": 353
			},
			{
				"word": "public",
				"count": 352
			},
			{
				"word": "jec",
				"count": 339
			},
			{
				"word": "education",
				"count": 335
			},
			{
				"word": "member",
				"count": 333
			},
			{
				"word": "young",
				"count": 330
			},
			{
				"word": "faith",
				"count": 326
			},
			{
				"word": "african",
				"count": 318
			},
			{
				"word": "imam",
				"count": 317
			},
			{
				"word": "movement",
				"count": 303
			},
			{
				"word": "base",
				"count": 297
			},
			{
				"word": "development",
				"count": 294
			},
			{
				"word": "presse",
				"count": 293
			},
			{
				"word": "bénin",
				"count": 292
			},
			{
				"word": "state",
				"count": 290
			},
			{
				"word": "support",
				"count": 268
			},
			{
				"word": "role",
				"count": 266
			},
			{
				"word": "study",
				"count": 266
			},
			{
				"word": "activity",
				"count": 264
			},
			{
				"word": "mosque",
				"count": 261
			},
			{
				"word": "include",
				"count": 261
			},
			{
				"word": "organisation",
				"count": 251
			},
			{
				"word": "medium",
				"count": 246
			},
			{
				"word": "challenge",
				"count": 246
			},
			{
				"word": "conversation",
				"count": 245
			},
			{
				"word": "lead",
				"count": 241
			},
			{
				"word": "activism",
				"count": 239
			},
			{
				"word": "youth",
				"count": 233
			},
			{
				"word": "year",
				"count": 232
			},
			{
				"word": "christian",
				"count": 229
			},
			{
				"word": "access",
				"count": 224
			},
			{
				"word": "life",
				"count": 221
			},
			{
				"word": "church",
				"count": 214
			},
			{
				"word": "authority",
				"count": 205
			},
			{
				"word": "cotonou",
				"count": 199
			},
			{
				"word": "people",
				"count": 197
			},
			{
				"word": "calavi",
				"count": 196
			},
			{
				"word": "change",
				"count": 195
			},
			{
				"word": "school",
				"count": 193
			},
			{
				"word": "west",
				"count": 191
			},
			{
				"word": "face",
				"count": 186
			},
			{
				"word": "islamique",
				"count": 184
			},
			{
				"word": "abomey",
				"count": 183
			},
			{
				"word": "high",
				"count": 180
			},
			{
				"word": "activist",
				"count": 180
			},
			{
				"word": "influence",
				"count": 179
			},
			{
				"word": "leadership",
				"count": 175
			},
			{
				"word": "musulmane",
				"count": 174
			},
			{
				"word": "aeemci",
				"count": 174
			},
			{
				"word": "issue",
				"count": 173
			},
			{
				"word": "regime",
				"count": 172
			},
			{
				"word": "organization",
				"count": 171
			},
			{
				"word": "radio",
				"count": 167
			},
			{
				"word": "establish",
				"count": 164
			},
			{
				"word": "context",
				"count": 162
			},
			{
				"word": "create",
				"count": 161
			},
			{
				"word": "economic",
				"count": 159
			},
			{
				"word": "press",
				"count": 153
			},
			{
				"word": "international",
				"count": 153
			},
			{
				"word": "government",
				"count": 152
			},
			{
				"word": "significant",
				"count": 152
			},
			{
				"word": "focus",
				"count": 149
			},
			{
				"word": "follow",
				"count": 147
			},
			{
				"word": "work",
				"count": 146
			},
			{
				"word": "hold",
				"count": 145
			},
			{
				"word": "french",
				"count": 145
			},
			{
				"word": "gbeeb",
				"count": 145
			},
			{
				"word": "musulmans",
				"count": 144
			},
			{
				"word": "seek",
				"count": 144
			},
			{
				"word": "aeemt",
				"count": 143
			},
			{
				"word": "remain",
				"count": 142
			},
			{
				"word": "provide",
				"count": 142
			},
			{
				"word": "figure",
				"count": 140
			},
			{
				"word": "intellectual",
				"count": 140
			},
			{
				"word": "time",
				"count": 140
			},
			{
				"word": "society",
				"count": 140
			}
		],
		"fr": [
			{
				"word": "musulman",
				"count": 1204
			},
			{
				"word": "islam",
				"count": 925
			},
			{
				"word": "religieux",
				"count": 654
			},
			{
				"word": "imam",
				"count": 636
			},
			{
				"word": "islamique",
				"count": 586
			},
			{
				"word": "association",
				"count": 558
			},
			{
				"word": "afrique",
				"count": 426
			},
			{
				"word": "année",
				"count": 425
			},
			{
				"word": "politique",
				"count": 366
			},
			{
				"word": "jeune",
				"count": 363
			},
			{
				"word": "public",
				"count": 346
			},
			{
				"word": "état",
				"count": 335
			},
			{
				"word": "communauté",
				"count": 324
			},
			{
				"word": "grand",
				"count": 320
			},
			{
				"word": "pays",
				"count": 299
			},
			{
				"word": "mouvement",
				"count": 295
			},
			{
				"word": "nouveau",
				"count": 285
			},
			{
				"word": "mosquée",
				"count": 283
			},
			{
				"word": "national",
				"count": 275
			},
			{
				"word": "organisation",
				"count": 270
			},
			{
				"word": "aeemb",
				"count": 249
			},
			{
				"word": "social",
				"count": 246
			},
			{
				"word": "ouagadougou",
				"count": 242
			},
			{
				"word": "président",
				"count": 241
			},
			{
				"word": "radio",
				"count": 235
			},
			{
				"word": "africain",
				"count": 230
			},
			{
				"word": "hadj",
				"count": 224
			},
			{
				"word": "étudiant",
				"count": 222
			},
			{
				"word": "pouvoir",
				"count": 222
			},
			{
				"word": "religion",
				"count": 219
			},
			{
				"word": "dir",
				"count": 219
			},
			{
				"word": "côte",
				"count": 216
			},
			{
				"word": "ivoire",
				"count": 212
			},
			{
				"word": "média",
				"count": 209
			},
			{
				"word": "université",
				"count": 200
			},
			{
				"word": "sphère",
				"count": 200
			},
			{
				"word": "étude",
				"count": 194
			},
			{
				"word": "responsable",
				"count": 188
			},
			{
				"word": "sunnite",
				"count": 184
			},
			{
				"word": "presse",
				"count": 181
			},
			{
				"word": "mettre",
				"count": 180
			},
			{
				"word": "voir",
				"count": 179
			},
			{
				"word": "prêcheur",
				"count": 174
			},
			{
				"word": "cerfi",
				"count": 173
			},
			{
				"word": "journal",
				"count": 170
			},
			{
				"word": "sein",
				"count": 169
			},
			{
				"word": "ouest",
				"count": 168
			},
			{
				"word": "togo",
				"count": 164
			},
			{
				"word": "figure",
				"count": 160
			},
			{
				"word": "internet",
				"count": 160
			},
			{
				"word": "site",
				"count": 158
			},
			{
				"word": "discours",
				"count": 158
			},
			{
				"word": "cohorte",
				"count": 150
			},
			{
				"word": "contexte",
				"count": 148
			},
			{
				"word": "africa",
				"count": 148
			},
			{
				"word": "sermon",
				"count": 148
			},
			{
				"word": "vendredi",
				"count": 145
			},
			{
				"word": "musulmane",
				"count": 145
			},
			{
				"word": "construction",
				"count": 142
			},
			{
				"word": "membre",
				"count": 136
			},
			{
				"word": "société",
				"count": 136
			},
			{
				"word": "autorité",
				"count": 133
			},
			{
				"word": "vol",
				"count": 133
			},
			{
				"word": "cmbf",
				"count": 132
			},
			{
				"word": "numérique",
				"count": 131
			},
			{
				"word": "espace",
				"count": 130
			},
			{
				"word": "burkinabé",
				"count": 126
			},
			{
				"word": "groupe",
				"count": 124
			},
			{
				"word": "arabe",
				"count": 123
			},
			{
				"word": "nombre",
				"count": 122
			},
			{
				"word": "important",
				"count": 119
			},
			{
				"word": "place",
				"count": 119
			},
			{
				"word": "ivoirien",
				"count": 119
			},
			{
				"word": "création",
				"count": 118
			},
			{
				"word": "recherche",
				"count": 115
			},
			{
				"word": "devenir",
				"count": 113
			},
			{
				"word": "cas",
				"count": 113
			},
			{
				"word": "wahhabite",
				"count": 113
			},
			{
				"word": "formation",
				"count": 111
			},
			{
				"word": "prière",
				"count": 110
			},
			{
				"word": "dernier",
				"count": 110
			},
			{
				"word": "chrétien",
				"count": 109
			},
			{
				"word": "ailleurs",
				"count": 108
			},
			{
				"word": "arabisant",
				"count": 108
			},
			{
				"word": "entretien",
				"count": 107
			},
			{
				"word": "pèlerinage",
				"count": 107
			},
			{
				"word": "aîné",
				"count": 107
			},
			{
				"word": "pratique",
				"count": 107
			},
			{
				"word": "conseil",
				"count": 106
			},
			{
				"word": "foi",
				"count": 106
			},
			{
				"word": "tendance",
				"count": 106
			},
			{
				"word": "prêche",
				"count": 104
			},
			{
				"word": "fidèle",
				"count": 102
			},
			{
				"word": "jec",
				"count": 99
			},
			{
				"word": "part",
				"count": 98
			},
			{
				"word": "télévision",
				"count": 98
			},
			{
				"word": "nasr",
				"count": 98
			},
			{
				"word": "voltaïque",
				"count": 98
			},
			{
				"word": "cmhv",
				"count": 98
			},
			{
				"word": "publique",
				"count": 98
			}
		]
	},
	"bigrams": {
		"all": [
			{
				"ngram": "communauté musulman",
				"words": [
					"communauté",
					"musulman"
				],
				"count": 189
			},
			{
				"ngram": "student association",
				"words": [
					"student",
					"association"
				],
				"count": 147
			},
			{
				"ngram": "muslim community",
				"words": [
					"muslim",
					"community"
				],
				"count": 146
			},
			{
				"ngram": "muslim student",
				"words": [
					"muslim",
					"student"
				],
				"count": 145
			},
			{
				"ngram": "mouvement sunnite",
				"words": [
					"mouvement",
					"sunnite"
				],
				"count": 139
			},
			{
				"ngram": "west africa",
				"words": [
					"west",
					"africa"
				],
				"count": 116
			},
			{
				"ngram": "high education",
				"words": [
					"high",
					"education"
				],
				"count": 115
			},
			{
				"ngram": "sphère publique",
				"words": [
					"sphère",
					"publique"
				],
				"count": 96
			},
			{
				"ngram": "publique musulmane",
				"words": [
					"publique",
					"musulmane"
				],
				"count": 96
			},
			{
				"ngram": "university campus",
				"words": [
					"university",
					"campus"
				],
				"count": 88
			},
			{
				"ngram": "sphère public",
				"words": [
					"sphère",
					"public"
				],
				"count": 88
			},
			{
				"ngram": "association islamique",
				"words": [
					"association",
					"islamique"
				],
				"count": 77
			},
			{
				"ngram": "association musulman",
				"words": [
					"association",
					"musulman"
				],
				"count": 73
			},
			{
				"ngram": "young people",
				"words": [
					"young",
					"people"
				],
				"count": 65
			},
			{
				"ngram": "muslim woman",
				"words": [
					"muslim",
					"woman"
				],
				"count": 64
			},
			{
				"ngram": "espace public",
				"words": [
					"espace",
					"public"
				],
				"count": 64
			},
			{
				"ngram": "student activism",
				"words": [
					"student",
					"activism"
				],
				"count": 61
			},
			{
				"ngram": "radio station",
				"words": [
					"radio",
					"station"
				],
				"count": 58
			},
			{
				"ngram": "kane koné",
				"words": [
					"kane",
					"koné"
				],
				"count": 58
			},
			{
				"ngram": "communauté musulmane",
				"words": [
					"communauté",
					"musulmane"
				],
				"count": 55
			},
			{
				"ngram": "jeune musulman",
				"words": [
					"jeune",
					"musulman"
				],
				"count": 52
			},
			{
				"ngram": "public sphere",
				"words": [
					"public",
					"sphere"
				],
				"count": 51
			},
			{
				"ngram": "grand mosquée",
				"words": [
					"grand",
					"mosquée"
				],
				"count": 51
			},
			{
				"ngram": "aminata kane",
				"words": [
					"aminata",
					"kane"
				],
				"count": 50
			},
			{
				"ngram": "site web",
				"words": [
					"site",
					"web"
				],
				"count": 48
			},
			{
				"ngram": "étude africain",
				"words": [
					"étude",
					"africain"
				],
				"count": 48
			},
			{
				"ngram": "arabie saoudite",
				"words": [
					"arabie",
					"saoudite"
				],
				"count": 47
			},
			{
				"ngram": "grand imam",
				"words": [
					"grand",
					"imam"
				],
				"count": 47
			},
			{
				"ngram": "catholic church",
				"words": [
					"catholic",
					"church"
				],
				"count": 46
			},
			{
				"ngram": "religious group",
				"words": [
					"religious",
					"group"
				],
				"count": 45
			}
		],
		"en": [
			{
				"ngram": "student association",
				"words": [
					"student",
					"association"
				],
				"count": 147
			},
			{
				"ngram": "muslim community",
				"words": [
					"muslim",
					"community"
				],
				"count": 146
			},
			{
				"ngram": "muslim student",
				"words": [
					"muslim",
					"student"
				],
				"count": 145
			},
			{
				"ngram": "high education",
				"words": [
					"high",
					"education"
				],
				"count": 115
			},
			{
				"ngram": "west africa",
				"words": [
					"west",
					"africa"
				],
				"count": 113
			},
			{
				"ngram": "university campus",
				"words": [
					"university",
					"campus"
				],
				"count": 88
			},
			{
				"ngram": "young people",
				"words": [
					"young",
					"people"
				],
				"count": 65
			},
			{
				"ngram": "muslim woman",
				"words": [
					"muslim",
					"woman"
				],
				"count": 64
			},
			{
				"ngram": "student activism",
				"words": [
					"student",
					"activism"
				],
				"count": 61
			},
			{
				"ngram": "radio station",
				"words": [
					"radio",
					"station"
				],
				"count": 58
			},
			{
				"ngram": "kane koné",
				"words": [
					"kane",
					"koné"
				],
				"count": 58
			},
			{
				"ngram": "aminata kane",
				"words": [
					"aminata",
					"kane"
				],
				"count": 50
			},
			{
				"ngram": "public sphere",
				"words": [
					"public",
					"sphere"
				],
				"count": 47
			},
			{
				"ngram": "catholic church",
				"words": [
					"catholic",
					"church"
				],
				"count": 46
			},
			{
				"ngram": "religious group",
				"words": [
					"religious",
					"group"
				],
				"count": 45
			},
			{
				"ngram": "national university",
				"words": [
					"national",
					"university"
				],
				"count": 44
			},
			{
				"ngram": "student movement",
				"words": [
					"student",
					"movement"
				],
				"count": 43
			},
			{
				"ngram": "social medium",
				"words": [
					"social",
					"medium"
				],
				"count": 41
			},
			{
				"ngram": "islamic association",
				"words": [
					"islamic",
					"association"
				],
				"count": 39
			},
			{
				"ngram": "university student",
				"words": [
					"university",
					"student"
				],
				"count": 34
			},
			{
				"ngram": "imam affiliate",
				"words": [
					"imam",
					"affiliate"
				],
				"count": 33
			},
			{
				"ngram": "communauté musulmane",
				"words": [
					"communauté",
					"musulmane"
				],
				"count": 32
			},
			{
				"ngram": "bible group",
				"words": [
					"bible",
					"group"
				],
				"count": 32
			},
			{
				"ngram": "muslim women",
				"words": [
					"muslim",
					"women"
				],
				"count": 31
			},
			{
				"ngram": "digital medium",
				"words": [
					"digital",
					"medium"
				],
				"count": 30
			},
			{
				"ngram": "religious activism",
				"words": [
					"religious",
					"activism"
				],
				"count": 29
			},
			{
				"ngram": "christian student",
				"words": [
					"christian",
					"student"
				],
				"count": 29
			},
			{
				"ngram": "religious authority",
				"words": [
					"religious",
					"authority"
				],
				"count": 28
			},
			{
				"ngram": "muslim intellectual",
				"words": [
					"muslim",
					"intellectual"
				],
				"count": 28
			},
			{
				"ngram": "public university",
				"words": [
					"public",
					"university"
				],
				"count": 28
			}
		],
		"fr": [
			{
				"ngram": "communauté musulman",
				"words": [
					"communauté",
					"musulman"
				],
				"count": 189
			},
			{
				"ngram": "mouvement sunnite",
				"words": [
					"mouvement",
					"sunnite"
				],
				"count": 131
			},
			{
				"ngram": "sphère publique",
				"words": [
					"sphère",
					"publique"
				],
				"count": 96
			},
			{
				"ngram": "publique musulmane",
				"words": [
					"publique",
					"musulmane"
				],
				"count": 96
			},
			{
				"ngram": "sphère public",
				"words": [
					"sphère",
					"public"
				],
				"count": 88
			},
			{
				"ngram": "association islamique",
				"words": [
					"association",
					"islamique"
				],
				"count": 77
			},
			{
				"ngram": "association musulman",
				"words": [
					"association",
					"musulman"
				],
				"count": 73
			},
			{
				"ngram": "espace public",
				"words": [
					"espace",
					"public"
				],
				"count": 64
			},
			{
				"ngram": "jeune musulman",
				"words": [
					"jeune",
					"musulman"
				],
				"count": 52
			},
			{
				"ngram": "grand mosquée",
				"words": [
					"grand",
					"mosquée"
				],
				"count": 51
			},
			{
				"ngram": "site web",
				"words": [
					"site",
					"web"
				],
				"count": 48
			},
			{
				"ngram": "étude africain",
				"words": [
					"étude",
					"africain"
				],
				"count": 48
			},
			{
				"ngram": "arabie saoudite",
				"words": [
					"arabie",
					"saoudite"
				],
				"count": 47
			},
			{
				"ngram": "grand imam",
				"words": [
					"grand",
					"imam"
				],
				"count": 47
			},
			{
				"ngram": "étudiant musulman",
				"words": [
					"étudiant",
					"musulman"
				],
				"count": 45
			},
			{
				"ngram": "média numérique",
				"words": [
					"média",
					"numérique"
				],
				"count": 44
			},
			{
				"ngram": "islam burkinabé",
				"words": [
					"islam",
					"burkinabé"
				],
				"count": 43
			},
			{
				"ngram": "jeune arabisant",
				"words": [
					"jeune",
					"arabisant"
				],
				"count": 42
			},
			{
				"ngram": "islam voltaïque",
				"words": [
					"islam",
					"voltaïque"
				],
				"count": 37
			},
			{
				"ngram": "transition démocratique",
				"words": [
					"transition",
					"démocratique"
				],
				"count": 35
			},
			{
				"ngram": "réseau social",
				"words": [
					"réseau",
					"social"
				],
				"count": 34
			},
			{
				"ngram": "afrique subsaharien",
				"words": [
					"afrique",
					"subsaharien"
				],
				"count": 33
			},
			{
				"ngram": "chemin sinueux",
				"words": [
					"chemin",
					"sinueux"
				],
				"count": 31
			},
			{
				"ngram": "islam ivoirien",
				"words": [
					"islam",
					"ivoirien"
				],
				"count": 29
			},
			{
				"ngram": "dernier année",
				"words": [
					"dernier",
					"année"
				],
				"count": 27
			},
			{
				"ngram": "école coranique",
				"words": [
					"école",
					"coranique"
				],
				"count": 27
			},
			{
				"ngram": "citoyenneté musulmane",
				"words": [
					"citoyenneté",
					"musulmane"
				],
				"count": 26
			},
			{
				"ngram": "connaissance religieux",
				"words": [
					"connaissance",
					"religieux"
				],
				"count": 24
			},
			{
				"ngram": "église catholique",
				"words": [
					"église",
					"catholique"
				],
				"count": 23
			},
			{
				"ngram": "communauté musulmane",
				"words": [
					"communauté",
					"musulmane"
				],
				"count": 23
			}
		]
	}
};
