// AUTO-GENERATED by scripts/generate-analysis-summaries.mjs — DO NOT EDIT.
// Regenerate with `npm run gen:analysis` (runs automatically via the prebuild hook).
/* eslint-disable */
import type { WordFrequency } from '$lib/types';

/**
 * Each analysed publication's 28 most frequent full-text terms — what the
 * record rail's key-terms cloud prints, and nothing else. A publication absent
 * from this map has no full-text analysis.
 */
export const keyTermsByPublication: Record<string, WordFrequency[]> = {
	"beninese-imam-election-2022": [
		{
			"word": "imam",
			"count": 95
		},
		{
			"word": "uib",
			"count": 77
		},
		{
			"word": "muslim",
			"count": 69
		},
		{
			"word": "islamic",
			"count": 50
		},
		{
			"word": "community",
			"count": 46
		},
		{
			"word": "political",
			"count": 44
		},
		{
			"word": "election",
			"count": 41
		},
		{
			"word": "ousmane",
			"count": 37
		},
		{
			"word": "benin",
			"count": 36
		},
		{
			"word": "national",
			"count": 36
		},
		{
			"word": "bénin",
			"count": 36
		},
		{
			"word": "muslims",
			"count": 36
		},
		{
			"word": "president",
			"count": 32
		},
		{
			"word": "africa",
			"count": 31
		},
		{
			"word": "beninese",
			"count": 30
		},
		{
			"word": "religious",
			"count": 29
		},
		{
			"word": "leader",
			"count": 28
		},
		{
			"word": "mosque",
			"count": 26
		},
		{
			"word": "country",
			"count": 25
		},
		{
			"word": "politic",
			"count": 24
		},
		{
			"word": "interview",
			"count": 24
		},
		{
			"word": "islam",
			"count": 23
		},
		{
			"word": "islamique",
			"count": 23
		},
		{
			"word": "talon",
			"count": 21
		},
		{
			"word": "organization",
			"count": 21
		},
		{
			"word": "cotonou",
			"count": 19
		},
		{
			"word": "state",
			"count": 19
		},
		{
			"word": "minority",
			"count": 18
		}
	],
	"communaute-musulmane-burkina-faso-2014": [
		{
			"word": "communauté",
			"count": 9
		},
		{
			"word": "cmbf",
			"count": 7
		},
		{
			"word": "association",
			"count": 7
		},
		{
			"word": "musulmane",
			"count": 6
		},
		{
			"word": "volta",
			"count": 5
		},
		{
			"word": "country",
			"count": 4
		},
		{
			"word": "state",
			"count": 4
		},
		{
			"word": "haute",
			"count": 3
		},
		{
			"word": "islamic",
			"count": 3
		},
		{
			"word": "muslim",
			"count": 3
		},
		{
			"word": "imām",
			"count": 3
		},
		{
			"word": "clash",
			"count": 3
		},
		{
			"word": "member",
			"count": 3
		},
		{
			"word": "mosque",
			"count": 3
		},
		{
			"word": "ouagadougou",
			"count": 3
		},
		{
			"word": "lead",
			"count": 3
		},
		{
			"word": "mouvement",
			"count": 3
		},
		{
			"word": "sunnite",
			"count": 3
		},
		{
			"word": "oumarou",
			"count": 3
		},
		{
			"word": "kanazoé",
			"count": 3
		},
		{
			"word": "révolution",
			"count": 3
		},
		{
			"word": "rené",
			"count": 3
		},
		{
			"word": "found",
			"count": 2
		},
		{
			"word": "upper",
			"count": 2
		},
		{
			"word": "national",
			"count": 2
		},
		{
			"word": "want",
			"count": 2
		},
		{
			"word": "achieve",
			"count": 2
		},
		{
			"word": "congress",
			"count": 2
		}
	],
	"exister-contexte-autoritaire-lome-2023": [
		{
			"word": "togo",
			"count": 132
		},
		{
			"word": "étudiant",
			"count": 127
		},
		{
			"word": "jec",
			"count": 99
		},
		{
			"word": "lomé",
			"count": 68
		},
		{
			"word": "campus",
			"count": 66
		},
		{
			"word": "association",
			"count": 65
		},
		{
			"word": "université",
			"count": 61
		},
		{
			"word": "musulman",
			"count": 57
		},
		{
			"word": "entretien",
			"count": 55
		},
		{
			"word": "religieux",
			"count": 53
		},
		{
			"word": "national",
			"count": 47
		},
		{
			"word": "année",
			"count": 44
		},
		{
			"word": "universitaire",
			"count": 44
		},
		{
			"word": "presse",
			"count": 41
		},
		{
			"word": "mouvement",
			"count": 38
		},
		{
			"word": "eyadéma",
			"count": 37
		},
		{
			"word": "chrétien",
			"count": 34
		},
		{
			"word": "ancien",
			"count": 34
		},
		{
			"word": "contexte",
			"count": 32
		},
		{
			"word": "groupe",
			"count": 32
		},
		{
			"word": "islamique",
			"count": 31
		},
		{
			"word": "togolais",
			"count": 31
		},
		{
			"word": "jeunesse",
			"count": 31
		},
		{
			"word": "jeiub",
			"count": 31
		},
		{
			"word": "politique",
			"count": 30
		},
		{
			"word": "catholique",
			"count": 29
		},
		{
			"word": "pouvoir",
			"count": 29
		},
		{
			"word": "président",
			"count": 27
		}
	],
	"francophone-muslim-intellectuals-burkina-faso-2020": [
		{
			"word": "muslim",
			"count": 85
		},
		{
			"word": "leader",
			"count": 57
		},
		{
			"word": "islamic",
			"count": 56
		},
		{
			"word": "faib",
			"count": 56
		},
		{
			"word": "muslims",
			"count": 49
		},
		{
			"word": "religious",
			"count": 44
		},
		{
			"word": "cerfi",
			"count": 43
		},
		{
			"word": "islam",
			"count": 41
		},
		{
			"word": "association",
			"count": 39
		},
		{
			"word": "community",
			"count": 38
		},
		{
			"word": "political",
			"count": 35
		},
		{
			"word": "aeemb",
			"count": 31
		},
		{
			"word": "intellectual",
			"count": 30
		},
		{
			"word": "president",
			"count": 30
		},
		{
			"word": "public",
			"count": 28
		},
		{
			"word": "young",
			"count": 27
		},
		{
			"word": "francophone",
			"count": 26
		},
		{
			"word": "compaoré",
			"count": 25
		},
		{
			"word": "country",
			"count": 25
		},
		{
			"word": "access",
			"count": 25
		},
		{
			"word": "national",
			"count": 24
		},
		{
			"word": "new",
			"count": 23
		},
		{
			"word": "state",
			"count": 22
		},
		{
			"word": "university",
			"count": 21
		},
		{
			"word": "ouagadougou",
			"count": 21
		},
		{
			"word": "organization",
			"count": 19
		},
		{
			"word": "people",
			"count": 18
		},
		{
			"word": "change",
			"count": 18
		}
	],
	"good-muslim-bad-muslim-togo-2021": [
		{
			"word": "togo",
			"count": 149
		},
		{
			"word": "muslim",
			"count": 55
		},
		{
			"word": "umt",
			"count": 52
		},
		{
			"word": "regime",
			"count": 47
		},
		{
			"word": "muslims",
			"count": 46
		},
		{
			"word": "political",
			"count": 44
		},
		{
			"word": "access",
			"count": 44
		},
		{
			"word": "atchadam",
			"count": 43
		},
		{
			"word": "country",
			"count": 43
		},
		{
			"word": "president",
			"count": 36
		},
		{
			"word": "lomé",
			"count": 35
		},
		{
			"word": "imam",
			"count": 35
		},
		{
			"word": "gnassingbé",
			"count": 34
		},
		{
			"word": "official",
			"count": 34
		},
		{
			"word": "togolese",
			"count": 33
		},
		{
			"word": "acmt",
			"count": 33
		},
		{
			"word": "opposition",
			"count": 32
		},
		{
			"word": "leader",
			"count": 32
		},
		{
			"word": "islam",
			"count": 28
		},
		{
			"word": "government",
			"count": 23
		},
		{
			"word": "africa",
			"count": 23
		},
		{
			"word": "national",
			"count": 22
		},
		{
			"word": "faure",
			"count": 22
		},
		{
			"word": "public",
			"count": 22
		},
		{
			"word": "support",
			"count": 22
		},
		{
			"word": "state",
			"count": 22
		},
		{
			"word": "int",
			"count": 21
		},
		{
			"word": "pnp",
			"count": 21
		}
	],
	"hackett-interview-digital-media-2017": [
		{
			"word": "medium",
			"count": 58
		},
		{
			"word": "religious",
			"count": 46
		},
		{
			"word": "religion",
			"count": 42
		},
		{
			"word": "digital",
			"count": 33
		},
		{
			"word": "africa",
			"count": 29
		},
		{
			"word": "new",
			"count": 27
		},
		{
			"word": "social",
			"count": 22
		},
		{
			"word": "research",
			"count": 21
		},
		{
			"word": "online",
			"count": 20
		},
		{
			"word": "hackett",
			"count": 18
		},
		{
			"word": "church",
			"count": 18
		},
		{
			"word": "media",
			"count": 13
		},
		{
			"word": "african",
			"count": 13
		},
		{
			"word": "study",
			"count": 11
		},
		{
			"word": "offline",
			"count": 10
		},
		{
			"word": "interview",
			"count": 9
		},
		{
			"word": "charismatic",
			"count": 9
		},
		{
			"word": "community",
			"count": 9
		},
		{
			"word": "leader",
			"count": 9
		},
		{
			"word": "access",
			"count": 9
		},
		{
			"word": "practice",
			"count": 9
		},
		{
			"word": "internet",
			"count": 9
		},
		{
			"word": "rosalind",
			"count": 8
		},
		{
			"word": "pentecostal",
			"count": 8
		},
		{
			"word": "service",
			"count": 8
		},
		{
			"word": "member",
			"count": 7
		},
		{
			"word": "video",
			"count": 7
		},
		{
			"word": "ghana",
			"count": 7
		}
	],
	"hadj-cote-divoire-2018": [
		{
			"word": "hadj",
			"count": 140
		},
		{
			"word": "musulman",
			"count": 122
		},
		{
			"word": "organisation",
			"count": 121
		},
		{
			"word": "pèlerinage",
			"count": 107
		},
		{
			"word": "état",
			"count": 88
		},
		{
			"word": "association",
			"count": 67
		},
		{
			"word": "côte",
			"count": 60
		},
		{
			"word": "ivoire",
			"count": 60
		},
		{
			"word": "cni",
			"count": 51
		},
		{
			"word": "président",
			"count": 50
		},
		{
			"word": "mecque",
			"count": 49
		},
		{
			"word": "communauté",
			"count": 46
		},
		{
			"word": "ivoirien",
			"count": 44
		},
		{
			"word": "cosim",
			"count": 44
		},
		{
			"word": "fraternité",
			"count": 41
		},
		{
			"word": "bédié",
			"count": 41
		},
		{
			"word": "matin",
			"count": 40
		},
		{
			"word": "pèlerin",
			"count": 38
		},
		{
			"word": "nouveau",
			"count": 34
		},
		{
			"word": "jour",
			"count": 34
		},
		{
			"word": "cnopm",
			"count": 33
		},
		{
			"word": "fofana",
			"count": 32
		},
		{
			"word": "gbagbo",
			"count": 30
		},
		{
			"word": "ministre",
			"count": 30
		},
		{
			"word": "pouvoir",
			"count": 29
		},
		{
			"word": "islamique",
			"count": 29
		},
		{
			"word": "diaby",
			"count": 29
		},
		{
			"word": "islam",
			"count": 28
		}
	],
	"imams-islamic-preachers-ouagadougou-2020": [
		{
			"word": "imam",
			"count": 110
		},
		{
			"word": "imams",
			"count": 103
		},
		{
			"word": "islam",
			"count": 86
		},
		{
			"word": "mosque",
			"count": 73
		},
		{
			"word": "islamic",
			"count": 67
		},
		{
			"word": "young",
			"count": 63
		},
		{
			"word": "muslim",
			"count": 59
		},
		{
			"word": "public",
			"count": 58
		},
		{
			"word": "religious",
			"count": 55
		},
		{
			"word": "preacher",
			"count": 49
		},
		{
			"word": "new",
			"count": 48
		},
		{
			"word": "radio",
			"count": 47
		},
		{
			"word": "sermon",
			"count": 47
		},
		{
			"word": "affiliate",
			"count": 40
		},
		{
			"word": "muslims",
			"count": 36
		},
		{
			"word": "aeemb",
			"count": 36
		},
		{
			"word": "cmbf",
			"count": 36
		},
		{
			"word": "ouagadougou",
			"count": 34
		},
		{
			"word": "elder",
			"count": 33
		},
		{
			"word": "cerfi",
			"count": 30
		},
		{
			"word": "country",
			"count": 27
		},
		{
			"word": "political",
			"count": 27
		},
		{
			"word": "youth",
			"count": 27
		},
		{
			"word": "medium",
			"count": 27
		},
		{
			"word": "nasr",
			"count": 27
		},
		{
			"word": "africa",
			"count": 26
		},
		{
			"word": "social",
			"count": 26
		},
		{
			"word": "vendredi",
			"count": 26
		}
	],
	"introduction-religiosity-university-campuses-2023": [
		{
			"word": "university",
			"count": 149
		},
		{
			"word": "campus",
			"count": 105
		},
		{
			"word": "africa",
			"count": 81
		},
		{
			"word": "student",
			"count": 57
		},
		{
			"word": "religiosity",
			"count": 56
		},
		{
			"word": "religious",
			"count": 53
		},
		{
			"word": "social",
			"count": 50
		},
		{
			"word": "african",
			"count": 42
		},
		{
			"word": "nigeria",
			"count": 40
		},
		{
			"word": "political",
			"count": 35
		},
		{
			"word": "education",
			"count": 31
		},
		{
			"word": "volume",
			"count": 27
		},
		{
			"word": "religion",
			"count": 27
		},
		{
			"word": "development",
			"count": 26
		},
		{
			"word": "press",
			"count": 24
		},
		{
			"word": "space",
			"count": 22
		},
		{
			"word": "moral",
			"count": 22
		},
		{
			"word": "context",
			"count": 21
		},
		{
			"word": "idea",
			"count": 20
		},
		{
			"word": "niger",
			"count": 19
		},
		{
			"word": "muslim",
			"count": 19
		},
		{
			"word": "experience",
			"count": 18
		},
		{
			"word": "islam",
			"count": 18
		},
		{
			"word": "introduction",
			"count": 17
		},
		{
			"word": "life",
			"count": 16
		},
		{
			"word": "new",
			"count": 16
		},
		{
			"word": "high",
			"count": 16
		},
		{
			"word": "organization",
			"count": 16
		}
	],
	"islam-burkina-faso-collection-2021": [
		{
			"word": "archive",
			"count": 41
		},
		{
			"word": "islam",
			"count": 40
		},
		{
			"word": "africa",
			"count": 35
		},
		{
			"word": "digital",
			"count": 34
		},
		{
			"word": "numérique",
			"count": 33
		},
		{
			"word": "islamique",
			"count": 30
		},
		{
			"word": "musulman",
			"count": 27
		},
		{
			"word": "source",
			"count": 27
		},
		{
			"word": "african",
			"count": 26
		},
		{
			"word": "consulter",
			"count": 26
		},
		{
			"word": "afrique",
			"count": 24
		},
		{
			"word": "collection",
			"count": 23
		},
		{
			"word": "recherche",
			"count": 23
		},
		{
			"word": "document",
			"count": 23
		},
		{
			"word": "journal",
			"count": 23
		},
		{
			"word": "ligne",
			"count": 22
		},
		{
			"word": "history",
			"count": 21
		},
		{
			"word": "projet",
			"count": 19
		},
		{
			"word": "presse",
			"count": 19
		},
		{
			"word": "donnée",
			"count": 18
		},
		{
			"word": "histoire",
			"count": 17
		},
		{
			"word": "article",
			"count": 16
		},
		{
			"word": "chercheur",
			"count": 16
		},
		{
			"word": "africain",
			"count": 15
		},
		{
			"word": "base",
			"count": 14
		},
		{
			"word": "humanité",
			"count": 12
		},
		{
			"word": "accès",
			"count": 12
		},
		{
			"word": "publication",
			"count": 12
		}
	],
	"islam-ivoirien-burkinabe-numerique-2016": [
		{
			"word": "musulman",
			"count": 98
		},
		{
			"word": "islam",
			"count": 69
		},
		{
			"word": "site",
			"count": 62
		},
		{
			"word": "ivoirien",
			"count": 46
		},
		{
			"word": "numérique",
			"count": 45
		},
		{
			"word": "religieux",
			"count": 43
		},
		{
			"word": "côte",
			"count": 40
		},
		{
			"word": "ivoire",
			"count": 40
		},
		{
			"word": "association",
			"count": 39
		},
		{
			"word": "internet",
			"count": 38
		},
		{
			"word": "burkinabé",
			"count": 37
		},
		{
			"word": "web",
			"count": 30
		},
		{
			"word": "jeune",
			"count": 30
		},
		{
			"word": "islamique",
			"count": 25
		},
		{
			"word": "média",
			"count": 24
		},
		{
			"word": "page",
			"count": 24
		},
		{
			"word": "facebook",
			"count": 23
		},
		{
			"word": "nouveau",
			"count": 21
		},
		{
			"word": "politique",
			"count": 21
		},
		{
			"word": "pays",
			"count": 21
		},
		{
			"word": "mettre",
			"count": 19
		},
		{
			"word": "social",
			"count": 18
		},
		{
			"word": "année",
			"count": 17
		},
		{
			"word": "forme",
			"count": 17
		},
		{
			"word": "grand",
			"count": 17
		},
		{
			"word": "ère",
			"count": 16
		},
		{
			"word": "afrique",
			"count": 16
		},
		{
			"word": "figure",
			"count": 16
		}
	],
	"islam-medias-senat-burkina-faso-2016": [
		{
			"word": "musulman",
			"count": 112
		},
		{
			"word": "islam",
			"count": 66
		},
		{
			"word": "islamique",
			"count": 62
		},
		{
			"word": "imam",
			"count": 60
		},
		{
			"word": "politique",
			"count": 49
		},
		{
			"word": "public",
			"count": 48
		},
		{
			"word": "religieux",
			"count": 38
		},
		{
			"word": "burkinabè",
			"count": 35
		},
		{
			"word": "espace",
			"count": 34
		},
		{
			"word": "sénat",
			"count": 33
		},
		{
			"word": "grand",
			"count": 33
		},
		{
			"word": "association",
			"count": 33
		},
		{
			"word": "aeemb",
			"count": 31
		},
		{
			"word": "radio",
			"count": 28
		},
		{
			"word": "cerfi",
			"count": 28
		},
		{
			"word": "débat",
			"count": 26
		},
		{
			"word": "responsable",
			"count": 26
		},
		{
			"word": "article",
			"count": 25
		},
		{
			"word": "faib",
			"count": 25
		},
		{
			"word": "communauté",
			"count": 25
		},
		{
			"word": "compaoré",
			"count": 25
		},
		{
			"word": "journal",
			"count": 24
		},
		{
			"word": "média",
			"count": 24
		},
		{
			"word": "position",
			"count": 24
		},
		{
			"word": "ouagadougou",
			"count": 23
		},
		{
			"word": "étude",
			"count": 22
		},
		{
			"word": "social",
			"count": 22
		},
		{
			"word": "africain",
			"count": 21
		}
	],
	"islam-university-campuses-cote-divoire-2023": [
		{
			"word": "côte",
			"count": 145
		},
		{
			"word": "islam",
			"count": 123
		},
		{
			"word": "aeemci",
			"count": 119
		},
		{
			"word": "islamic",
			"count": 98
		},
		{
			"word": "university",
			"count": 95
		},
		{
			"word": "muslim",
			"count": 95
		},
		{
			"word": "student",
			"count": 92
		},
		{
			"word": "association",
			"count": 53
		},
		{
			"word": "campus",
			"count": 51
		},
		{
			"word": "mosque",
			"count": 49
		},
		{
			"word": "muslims",
			"count": 48
		},
		{
			"word": "salafi",
			"count": 39
		},
		{
			"word": "abidjan",
			"count": 33
		},
		{
			"word": "ouattara",
			"count": 33
		},
		{
			"word": "religious",
			"count": 32
		},
		{
			"word": "organization",
			"count": 31
		},
		{
			"word": "school",
			"count": 30
		},
		{
			"word": "new",
			"count": 28
		},
		{
			"word": "interview",
			"count": 28
		},
		{
			"word": "francophone",
			"count": 27
		},
		{
			"word": "cocody",
			"count": 27
		},
		{
			"word": "africa",
			"count": 26
		},
		{
			"word": "president",
			"count": 26
		},
		{
			"word": "salafism",
			"count": 25
		},
		{
			"word": "binaté",
			"count": 25
		},
		{
			"word": "national",
			"count": 25
		},
		{
			"word": "young",
			"count": 25
		},
		{
			"word": "training",
			"count": 25
		}
	],
	"leaders-muslim-ngos-burkina-faso-2016": [
		{
			"word": "muslim",
			"count": 43
		},
		{
			"word": "ngos",
			"count": 35
		},
		{
			"word": "religious",
			"count": 29
		},
		{
			"word": "support",
			"count": 29
		},
		{
			"word": "country",
			"count": 28
		},
		{
			"word": "activity",
			"count": 27
		},
		{
			"word": "social",
			"count": 25
		},
		{
			"word": "organisation",
			"count": 24
		},
		{
			"word": "association",
			"count": 23
		},
		{
			"word": "national",
			"count": 21
		},
		{
			"word": "study",
			"count": 21
		},
		{
			"word": "government",
			"count": 21
		},
		{
			"word": "state",
			"count": 20
		},
		{
			"word": "school",
			"count": 20
		},
		{
			"word": "leader",
			"count": 19
		},
		{
			"word": "authority",
			"count": 19
		},
		{
			"word": "arab",
			"count": 19
		},
		{
			"word": "islamic",
			"count": 18
		},
		{
			"word": "international",
			"count": 18
		},
		{
			"word": "education",
			"count": 18
		},
		{
			"word": "health",
			"count": 17
		},
		{
			"word": "development",
			"count": 16
		},
		{
			"word": "community",
			"count": 16
		},
		{
			"word": "french",
			"count": 16
		},
		{
			"word": "student",
			"count": 16
		},
		{
			"word": "ouagadougou",
			"count": 15
		},
		{
			"word": "speak",
			"count": 14
		},
		{
			"word": "faith",
			"count": 14
		}
	],
	"lutte-terrorisme-salafisme-benin-togo-2022": [
		{
			"word": "togo",
			"count": 32
		},
		{
			"word": "musulman",
			"count": 26
		},
		{
			"word": "bénin",
			"count": 24
		},
		{
			"word": "contre",
			"count": 21
		},
		{
			"word": "état",
			"count": 19
		},
		{
			"word": "pays",
			"count": 17
		},
		{
			"word": "terrorisme",
			"count": 14
		},
		{
			"word": "président",
			"count": 14
		},
		{
			"word": "islam",
			"count": 14
		},
		{
			"word": "salafisme",
			"count": 13
		},
		{
			"word": "menace",
			"count": 13
		},
		{
			"word": "politique",
			"count": 13
		},
		{
			"word": "togolais",
			"count": 13
		},
		{
			"word": "leader",
			"count": 12
		},
		{
			"word": "lutte",
			"count": 10
		},
		{
			"word": "religieux",
			"count": 10
		},
		{
			"word": "pouvoir",
			"count": 10
		},
		{
			"word": "national",
			"count": 10
		},
		{
			"word": "gouvernement",
			"count": 9
		},
		{
			"word": "opposition",
			"count": 9
		},
		{
			"word": "international",
			"count": 9
		},
		{
			"word": "année",
			"count": 8
		},
		{
			"word": "gnassingbé",
			"count": 8
		},
		{
			"word": "principal",
			"count": 8
		},
		{
			"word": "jeune",
			"count": 8
		},
		{
			"word": "groupe",
			"count": 7
		},
		{
			"word": "salafist",
			"count": 7
		},
		{
			"word": "parti",
			"count": 7
		}
	],
	"madore-2024-launch-iwac": [
		{
			"word": "zmo",
			"count": 5
		},
		{
			"word": "west",
			"count": 4
		},
		{
			"word": "mict",
			"count": 4
		},
		{
			"word": "iwac",
			"count": 4
		},
		{
			"word": "project",
			"count": 4
		},
		{
			"word": "launch",
			"count": 3
		},
		{
			"word": "islam",
			"count": 3
		},
		{
			"word": "africa",
			"count": 3
		},
		{
			"word": "berlin",
			"count": 3
		},
		{
			"word": "document",
			"count": 3
		},
		{
			"word": "nobili",
			"count": 3
		},
		{
			"word": "collection",
			"count": 2
		},
		{
			"word": "medium",
			"count": 2
		},
		{
			"word": "database",
			"count": 2
		},
		{
			"word": "recording",
			"count": 2
		},
		{
			"word": "côte",
			"count": 2
		},
		{
			"word": "site",
			"count": 2
		},
		{
			"word": "african",
			"count": 2
		},
		{
			"word": "klaas",
			"count": 2
		},
		{
			"word": "glenewinkel",
			"count": 2
		},
		{
			"word": "ulrike",
			"count": 2
		},
		{
			"word": "freitag",
			"count": 2
		},
		{
			"word": "mauro",
			"count": 2
		},
		{
			"word": "university",
			"count": 2
		},
		{
			"word": "illinois",
			"count": 2
		},
		{
			"word": "urbana",
			"count": 2
		},
		{
			"word": "champaign",
			"count": 2
		},
		{
			"word": "binate",
			"count": 2
		}
	],
	"madore-2025-perspectives-in-motion": [
		{
			"word": "discussion",
			"count": 4
		},
		{
			"word": "workshop",
			"count": 3
		},
		{
			"word": "zmo",
			"count": 3
		},
		{
			"word": "intellectual",
			"count": 3
		},
		{
			"word": "panel",
			"count": 3
		},
		{
			"word": "african",
			"count": 3
		},
		{
			"word": "university",
			"count": 3
		},
		{
			"word": "identity",
			"count": 3
		},
		{
			"word": "term",
			"count": 3
		},
		{
			"word": "global",
			"count": 2
		},
		{
			"word": "south",
			"count": 2
		},
		{
			"word": "organise",
			"count": 2
		},
		{
			"word": "religion",
			"count": 2
		},
		{
			"word": "explore",
			"count": 2
		},
		{
			"word": "western",
			"count": 2
		},
		{
			"word": "challenge",
			"count": 2
		},
		{
			"word": "enrich",
			"count": 2
		},
		{
			"word": "decolonial",
			"count": 2
		},
		{
			"word": "knowledge",
			"count": 2
		},
		{
			"word": "production",
			"count": 2
		},
		{
			"word": "roy",
			"count": 2
		},
		{
			"word": "kresse",
			"count": 2
		},
		{
			"word": "sounaye",
			"count": 2
		},
		{
			"word": "context",
			"count": 2
		},
		{
			"word": "framework",
			"count": 2
		},
		{
			"word": "maseno",
			"count": 2
		},
		{
			"word": "muslim",
			"count": 2
		},
		{
			"word": "analyse",
			"count": 2
		}
	],
	"muslim-feminist-media-cote-divoire-2020": [
		{
			"word": "woman",
			"count": 116
		},
		{
			"word": "muslim",
			"count": 77
		},
		{
			"word": "islamic",
			"count": 75
		},
		{
			"word": "côte",
			"count": 62
		},
		{
			"word": "kane",
			"count": 61
		},
		{
			"word": "koné",
			"count": 61
		},
		{
			"word": "islam",
			"count": 56
		},
		{
			"word": "aminata",
			"count": 52
		},
		{
			"word": "aeemci",
			"count": 47
		},
		{
			"word": "religious",
			"count": 46
		},
		{
			"word": "africa",
			"count": 40
		},
		{
			"word": "female",
			"count": 39
		},
		{
			"word": "social",
			"count": 37
		},
		{
			"word": "young",
			"count": 37
		},
		{
			"word": "new",
			"count": 29
		},
		{
			"word": "activist",
			"count": 28
		},
		{
			"word": "association",
			"count": 27
		},
		{
			"word": "medium",
			"count": 25
		},
		{
			"word": "entrepreneur",
			"count": 24
		},
		{
			"word": "entrepreneurship",
			"count": 24
		},
		{
			"word": "activity",
			"count": 23
		},
		{
			"word": "public",
			"count": 21
		},
		{
			"word": "president",
			"count": 21
		},
		{
			"word": "university",
			"count": 21
		},
		{
			"word": "right",
			"count": 21
		},
		{
			"word": "gender",
			"count": 20
		},
		{
			"word": "man",
			"count": 20
		},
		{
			"word": "religion",
			"count": 19
		}
	],
	"muslim-women-burkina-faso-2016": [
		{
			"word": "woman",
			"count": 206
		},
		{
			"word": "islamic",
			"count": 115
		},
		{
			"word": "muslim",
			"count": 99
		},
		{
			"word": "religious",
			"count": 77
		},
		{
			"word": "africa",
			"count": 56
		},
		{
			"word": "islam",
			"count": 54
		},
		{
			"word": "women",
			"count": 50
		},
		{
			"word": "association",
			"count": 50
		},
		{
			"word": "female",
			"count": 35
		},
		{
			"word": "educate",
			"count": 30
		},
		{
			"word": "new",
			"count": 30
		},
		{
			"word": "man",
			"count": 27
		},
		{
			"word": "education",
			"count": 27
		},
		{
			"word": "role",
			"count": 27
		},
		{
			"word": "study",
			"count": 24
		},
		{
			"word": "french",
			"count": 23
		},
		{
			"word": "community",
			"count": 23
		},
		{
			"word": "authority",
			"count": 22
		},
		{
			"word": "legitimacy",
			"count": 22
		},
		{
			"word": "change",
			"count": 22
		},
		{
			"word": "activism",
			"count": 21
		},
		{
			"word": "hajj",
			"count": 21
		},
		{
			"word": "femme",
			"count": 21
		},
		{
			"word": "organization",
			"count": 21
		},
		{
			"word": "figure",
			"count": 19
		},
		{
			"word": "preacher",
			"count": 19
		},
		{
			"word": "madrasa",
			"count": 19
		},
		{
			"word": "include",
			"count": 19
		}
	],
	"precheurs-musulmans-burkina-faso-2013": [
		{
			"word": "religieux",
			"count": 86
		},
		{
			"word": "islam",
			"count": 84
		},
		{
			"word": "musulman",
			"count": 71
		},
		{
			"word": "radio",
			"count": 60
		},
		{
			"word": "public",
			"count": 56
		},
		{
			"word": "islamique",
			"count": 56
		},
		{
			"word": "femme",
			"count": 46
		},
		{
			"word": "figure",
			"count": 38
		},
		{
			"word": "média",
			"count": 35
		},
		{
			"word": "association",
			"count": 35
		},
		{
			"word": "nouveau",
			"count": 34
		},
		{
			"word": "converti",
			"count": 32
		},
		{
			"word": "religion",
			"count": 31
		},
		{
			"word": "imam",
			"count": 31
		},
		{
			"word": "aeemb",
			"count": 31
		},
		{
			"word": "année",
			"count": 30
		},
		{
			"word": "nasr",
			"count": 30
		},
		{
			"word": "stratégie",
			"count": 29
		},
		{
			"word": "afrique",
			"count": 29
		},
		{
			"word": "mettre",
			"count": 29
		},
		{
			"word": "foi",
			"count": 29
		},
		{
			"word": "dir",
			"count": 29
		},
		{
			"word": "émission",
			"count": 28
		},
		{
			"word": "vendredi",
			"count": 27
		},
		{
			"word": "prêcheur",
			"count": 26
		},
		{
			"word": "houda",
			"count": 25
		},
		{
			"word": "communauté",
			"count": 25
		},
		{
			"word": "télévision",
			"count": 23
		}
	],
	"religieux-internet-ntic-burkina-faso-2019": [
		{
			"word": "religieux",
			"count": 92
		},
		{
			"word": "site",
			"count": 63
		},
		{
			"word": "radio",
			"count": 60
		},
		{
			"word": "média",
			"count": 59
		},
		{
			"word": "internet",
			"count": 51
		},
		{
			"word": "église",
			"count": 50
		},
		{
			"word": "social",
			"count": 43
		},
		{
			"word": "musulman",
			"count": 40
		},
		{
			"word": "organisation",
			"count": 38
		},
		{
			"word": "islamique",
			"count": 36
		},
		{
			"word": "web",
			"count": 32
		},
		{
			"word": "burkinabè",
			"count": 30
		},
		{
			"word": "année",
			"count": 28
		},
		{
			"word": "catholique",
			"count": 27
		},
		{
			"word": "télévision",
			"count": 25
		},
		{
			"word": "association",
			"count": 25
		},
		{
			"word": "journal",
			"count": 25
		},
		{
			"word": "page",
			"count": 25
		},
		{
			"word": "numérique",
			"count": 24
		},
		{
			"word": "ouagadougou",
			"count": 24
		},
		{
			"word": "facebook",
			"count": 24
		},
		{
			"word": "réseau",
			"count": 23
		},
		{
			"word": "audet",
			"count": 22
		},
		{
			"word": "pays",
			"count": 22
		},
		{
			"word": "jeune",
			"count": 22
		},
		{
			"word": "islam",
			"count": 22
		},
		{
			"word": "national",
			"count": 21
		},
		{
			"word": "utilisation",
			"count": 21
		}
	],
	"religion-internet-burkina-faso-2024": [
		{
			"word": "medium",
			"count": 93
		},
		{
			"word": "religious",
			"count": 91
		},
		{
			"word": "radio",
			"count": 69
		},
		{
			"word": "church",
			"count": 50
		},
		{
			"word": "muslim",
			"count": 50
		},
		{
			"word": "internet",
			"count": 49
		},
		{
			"word": "social",
			"count": 45
		},
		{
			"word": "website",
			"count": 43
		},
		{
			"word": "station",
			"count": 40
		},
		{
			"word": "organisation",
			"count": 35
		},
		{
			"word": "group",
			"count": 28
		},
		{
			"word": "digital",
			"count": 28
		},
		{
			"word": "site",
			"count": 28
		},
		{
			"word": "new",
			"count": 25
		},
		{
			"word": "catholic",
			"count": 25
		},
		{
			"word": "burkinabè",
			"count": 25
		},
		{
			"word": "create",
			"count": 25
		},
		{
			"word": "religion",
			"count": 24
		},
		{
			"word": "use",
			"count": 24
		},
		{
			"word": "association",
			"count": 24
		},
		{
			"word": "islam",
			"count": 24
		},
		{
			"word": "ouagadougou",
			"count": 24
		},
		{
			"word": "facebook",
			"count": 24
		},
		{
			"word": "presence",
			"count": 23
		},
		{
			"word": "communication",
			"count": 22
		},
		{
			"word": "press",
			"count": 22
		},
		{
			"word": "television",
			"count": 22
		},
		{
			"word": "launch",
			"count": 22
		}
	],
	"religious-activism-campuses": [
		{
			"word": "student",
			"count": 1071
		},
		{
			"word": "togo",
			"count": 797
		},
		{
			"word": "university",
			"count": 734
		},
		{
			"word": "religious",
			"count": 497
		},
		{
			"word": "benin",
			"count": 491
		},
		{
			"word": "association",
			"count": 470
		},
		{
			"word": "campus",
			"count": 423
		},
		{
			"word": "lomé",
			"count": 380
		},
		{
			"word": "political",
			"count": 368
		},
		{
			"word": "muslim",
			"count": 363
		},
		{
			"word": "jec",
			"count": 334
		},
		{
			"word": "national",
			"count": 279
		},
		{
			"word": "presse",
			"count": 277
		},
		{
			"word": "faith",
			"count": 266
		},
		{
			"word": "group",
			"count": 266
		},
		{
			"word": "bénin",
			"count": 256
		},
		{
			"word": "education",
			"count": 251
		},
		{
			"word": "conversation",
			"count": 245
		},
		{
			"word": "base",
			"count": 243
		},
		{
			"word": "leader",
			"count": 221
		},
		{
			"word": "challenge",
			"count": 219
		},
		{
			"word": "africa",
			"count": 214
		},
		{
			"word": "member",
			"count": 213
		},
		{
			"word": "activism",
			"count": 198
		},
		{
			"word": "islamic",
			"count": 198
		},
		{
			"word": "calavi",
			"count": 196
		},
		{
			"word": "social",
			"count": 187
		},
		{
			"word": "christian",
			"count": 186
		}
	],
	"religious-actors-digital-era-2017": [
		{
			"word": "religieux",
			"count": 75
		},
		{
			"word": "internet",
			"count": 46
		},
		{
			"word": "religion",
			"count": 43
		},
		{
			"word": "numérique",
			"count": 29
		},
		{
			"word": "média",
			"count": 24
		},
		{
			"word": "africain",
			"count": 21
		},
		{
			"word": "ligne",
			"count": 18
		},
		{
			"word": "nouveau",
			"count": 17
		},
		{
			"word": "étude",
			"count": 17
		},
		{
			"word": "social",
			"count": 17
		},
		{
			"word": "dir",
			"count": 17
		},
		{
			"word": "acteur",
			"count": 16
		},
		{
			"word": "vol",
			"count": 16
		},
		{
			"word": "web",
			"count": 15
		},
		{
			"word": "pratique",
			"count": 15
		},
		{
			"word": "afrique",
			"count": 15
		},
		{
			"word": "réseau",
			"count": 13
		},
		{
			"word": "église",
			"count": 13
		},
		{
			"word": "monde",
			"count": 13
		},
		{
			"word": "media",
			"count": 13
		},
		{
			"word": "hackett",
			"count": 13
		},
		{
			"word": "recherche",
			"count": 11
		},
		{
			"word": "forme",
			"count": 11
		},
		{
			"word": "islam",
			"count": 11
		},
		{
			"word": "groupe",
			"count": 10
		},
		{
			"word": "online",
			"count": 10
		},
		{
			"word": "digital",
			"count": 10
		},
		{
			"word": "musulman",
			"count": 9
		}
	],
	"salafism-cote-divoire-2016": [
		{
			"word": "côte",
			"count": 159
		},
		{
			"word": "amsci",
			"count": 124
		},
		{
			"word": "islam",
			"count": 116
		},
		{
			"word": "association",
			"count": 86
		},
		{
			"word": "new",
			"count": 69
		},
		{
			"word": "islamic",
			"count": 68
		},
		{
			"word": "info",
			"count": 63
		},
		{
			"word": "country",
			"count": 55
		},
		{
			"word": "muslim",
			"count": 55
		},
		{
			"word": "salafi",
			"count": 51
		},
		{
			"word": "national",
			"count": 47
		},
		{
			"word": "organization",
			"count": 45
		},
		{
			"word": "salafism",
			"count": 43
		},
		{
			"word": "muslims",
			"count": 43
		},
		{
			"word": "leader",
			"count": 41
		},
		{
			"word": "africa",
			"count": 40
		},
		{
			"word": "religion",
			"count": 36
		},
		{
			"word": "imam",
			"count": 34
		},
		{
			"word": "movement",
			"count": 33
		},
		{
			"word": "community",
			"count": 32
		},
		{
			"word": "mosque",
			"count": 32
		},
		{
			"word": "president",
			"count": 32
		},
		{
			"word": "religious",
			"count": 31
		},
		{
			"word": "university",
			"count": 31
		},
		{
			"word": "cni",
			"count": 30
		},
		{
			"word": "political",
			"count": 29
		},
		{
			"word": "youth",
			"count": 29
		},
		{
			"word": "journal",
			"count": 28
		}
	],
	"salafism-cote-ivoire-mande-2017": [
		{
			"word": "côte",
			"count": 60
		},
		{
			"word": "ivoire",
			"count": 60
		},
		{
			"word": "musulman",
			"count": 59
		},
		{
			"word": "association",
			"count": 56
		},
		{
			"word": "amsci",
			"count": 56
		},
		{
			"word": "islam",
			"count": 51
		},
		{
			"word": "année",
			"count": 35
		},
		{
			"word": "ivoirien",
			"count": 29
		},
		{
			"word": "sunnite",
			"count": 28
		},
		{
			"word": "islamique",
			"count": 24
		},
		{
			"word": "pays",
			"count": 21
		},
		{
			"word": "principal",
			"count": 19
		},
		{
			"word": "salafiste",
			"count": 18
		},
		{
			"word": "national",
			"count": 18
		},
		{
			"word": "président",
			"count": 18
		},
		{
			"word": "nouveau",
			"count": 17
		},
		{
			"word": "ouattara",
			"count": 15
		},
		{
			"word": "jeunesse",
			"count": 15
		},
		{
			"word": "politique",
			"count": 14
		},
		{
			"word": "info",
			"count": 14
		},
		{
			"word": "communauté",
			"count": 13
		},
		{
			"word": "imam",
			"count": 13
		},
		{
			"word": "dernier",
			"count": 12
		},
		{
			"word": "grand",
			"count": 12
		},
		{
			"word": "crise",
			"count": 12
		},
		{
			"word": "jeune",
			"count": 12
		},
		{
			"word": "salafist",
			"count": 11
		},
		{
			"word": "violence",
			"count": 11
		}
	],
	"sphere-publique-musulmane": [
		{
			"word": "musulman",
			"count": 583
		},
		{
			"word": "islam",
			"count": 515
		},
		{
			"word": "imam",
			"count": 472
		},
		{
			"word": "islamique",
			"count": 278
		},
		{
			"word": "afrique",
			"count": 260
		},
		{
			"word": "jeune",
			"count": 238
		},
		{
			"word": "mosquée",
			"count": 228
		},
		{
			"word": "association",
			"count": 227
		},
		{
			"word": "religieux",
			"count": 226
		},
		{
			"word": "année",
			"count": 207
		},
		{
			"word": "grand",
			"count": 193
		},
		{
			"word": "public",
			"count": 182
		},
		{
			"word": "mouvement",
			"count": 182
		},
		{
			"word": "politique",
			"count": 181
		},
		{
			"word": "sphère",
			"count": 174
		},
		{
			"word": "ouagadougou",
			"count": 172
		},
		{
			"word": "état",
			"count": 170
		},
		{
			"word": "communauté",
			"count": 169
		},
		{
			"word": "aeemb",
			"count": 164
		},
		{
			"word": "dir",
			"count": 150
		},
		{
			"word": "pays",
			"count": 149
		},
		{
			"word": "musulmane",
			"count": 145
		},
		{
			"word": "cohorte",
			"count": 142
		},
		{
			"word": "sunnite",
			"count": 140
		},
		{
			"word": "africain",
			"count": 135
		},
		{
			"word": "ouest",
			"count": 133
		},
		{
			"word": "construction",
			"count": 126
		},
		{
			"word": "prêcheur",
			"count": 123
		}
	]
};
