// AUTO-GENERATED by scripts/generate-summaries.mjs — DO NOT EDIT.
// Regenerate with `npm run gen:summaries` (runs automatically via the prebuild hook).
/* eslint-disable */
import type { CvCommunication } from '$lib/types/communication';
export const cvCommunications: CvCommunication[] = [
	{
		"id": "evolutions-nouvelles-formes-islam-afrique-ouest",
		"title": "Évolutions et nouvelles formes de l'islam en Afrique de l'Ouest: vers une radicalisation?",
		"authors": [
			"CIRAM"
		],
		"date": "24 March 2016",
		"dateISO": "2016-03-24",
		"conference": "Table-ronde organisée par le Centre Interdisciplinaire de Recherche sur l'Afrique et le Moyen-Orient (CIRAM)",
		"location": "Université Laval",
		"type": "event",
		"url": "https://www.ciram.hei.ulaval.ca/evolutions-et-nouvelles-formes-de-lislam-en-afrique-de-louest-vers-une-radicalisation/"
	},
	{
		"id": "launch-islam-west-africa-collection",
		"title": "Launch of the Islam West Africa Collection",
		"authors": [
			"Frédérick Madore"
		],
		"date": "9 November 2023",
		"dateISO": "2023-11-09",
		"conference": "Launch of the Islam West Africa Collection",
		"location": "Media in Cooperation and Transition (MiCT)",
		"type": "event",
		"url": "https://islam.zmo.de/s/westafrica/item/244"
	},
	{
		"id": "stias-dh-ai-african-studies-workshop-2026",
		"title": "Digital Humanities and Artificial Intelligence in African Studies: Towards Sustainable and Equitable Practices",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren",
			"Emmanuel Ngue Um",
			"Menno van Zaanen"
		],
		"date": "21-24 September 2026",
		"dateISO": "2026-09-21",
		"conference": "Digital Humanities and Artificial Intelligence in African Studies: Towards Sustainable and Equitable Practices",
		"location": "Stellenbosch Institute for Advanced Study (STIAS), Stellenbosch",
		"type": "event",
		"url": "https://fmadore.github.io/stias-dh-ai-workshop-2026/"
	},
	{
		"id": "university-campuses-africa-beyond",
		"title": "University Campuses in Africa and Beyond: Training Grounds, Moral Spaces and Political Arenas",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore"
		],
		"date": "6-8 September 2023",
		"dateISO": "2023-09-06",
		"conference": "University Campuses in Africa and Beyond",
		"location": "Leibniz-Zentrum Moderner Orient",
		"type": "event",
		"url": "https://remoboko.hypotheses.org/4854"
	},
	{
		"id": "volkswagenstiftung-dh-ai-african-studies-workshop-2026",
		"title": "Charting New Territory: Digital Humanities and AI in African Studies",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren"
		],
		"date": "18-20 February 2026",
		"dateISO": "2026-02-18",
		"conference": "Charting New Territory: Digital Humanities and AI in African Studies",
		"location": "Xplanatorium Herrenhausen, Hanover",
		"type": "event",
		"url": "https://fmadore.github.io/dh-ai-african-studies-2026/"
	},
	{
		"id": "workshop-religion-in-higher-educational-institutions-2021",
		"title": "Workshop “Religion in Higher Educational Institutions in Africa and Beyond: (Re)Conversion, Power, and Authority from a Comparative Perspective”",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore",
			"Vincent Favier",
			"Mahamadou Bello Adamou",
			"Adéjoké Rafiat Adétòrò"
		],
		"date": "16-17 November 2021",
		"dateISO": "2021-11-16",
		"conference": "Religion in Higher Educational Institutions in Africa and Beyond: (Re)Conversion, Power, and Authority from a Comparative Perspective",
		"location": "Leibniz-Zentrum Moderner Orient",
		"type": "event",
		"url": "https://remoboko.hypotheses.org/activities/workshops/workshop-2021"
	},
	{
		"id": "workshop-religions-on-campus-2022",
		"title": "Workshop “Religions on Campus: Coexisting Traditions, Reformulating the Secular and Life Projects”",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore",
			"Vincent Favier",
			"Mahamadou Bello Adamou",
			"Rakiya El Matine"
		],
		"date": "31 October - 4 November 2022",
		"dateISO": "2022-10-31",
		"conference": "Religions on Campus: Coexisting Traditions, Reformulating the Secular and Life Projects",
		"location": "Laboratoire d'Etudes et de Recherches sur les Dynamiques Sociales et le Développement Local (LASDEL)",
		"type": "event",
		"url": "https://remoboko.hypotheses.org/religions-on-campus-coexisting-traditions-reformulating-the-secular-and-life-projects"
	},
	{
		"id": "muslim-minorities-africa-2019",
		"title": "Muslim Minorities in Africa",
		"authors": [
			"Frédérick Madore"
		],
		"date": "21 November 2019",
		"dateISO": "2019-11-21",
		"conference": "62nd Meeting of the African Studies Association (ASA)",
		"location": "Boston",
		"type": "panel"
	},
	{
		"id": "author-meets-critic-faith-activism-2024",
		"title": "Author Meets Critic. Faith-based Student Activism in Togo and Benin: Muslims and Christians on University Campuses",
		"authors": [
			"Frédérick Madore"
		],
		"date": "12 December 2024",
		"dateISO": "2024-12-12",
		"conference": "67th Meeting of the African Studies Association (ASA)",
		"location": "Chicago",
		"type": "panel"
	},
	{
		"id": "dh-ai-african-studies-2025",
		"title": "Digital Humanities (DH) and AI in African Studies: Opportunities, Challenges, and Decolonial Perspectives",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren"
		],
		"date": "26 June 2025",
		"dateISO": "2025-06-26",
		"conference": "10th European Conference of African Studies (ECAS)",
		"location": "Prague",
		"type": "panel"
	},
	{
		"id": "humanites-numeriques-dh-ia-etudes-africaines-reaf-2026",
		"title": "Humanités numériques (DH) et IA dans les études africaines",
		"authors": [
			"Vincent Hiribarren",
			"Frédérick Madore"
		],
		"date": "30 juin 2026",
		"dateISO": "2026-06-30",
		"conference": "9èmes Rencontres des études africaines en France (REAF)",
		"location": "Paris",
		"type": "panel",
		"url": "https://reaf2026.sciencesconf.org/data/pages/A33.pdf"
	},
	{
		"id": "ai-archives-humanistica-2025",
		"title": "Intelligence artificielle et traitement des archives numériques : applications et enjeux dans la Collection Islam Afrique de l'Ouest",
		"authors": [
			"Frédérick Madore"
		],
		"date": "24 April 2025",
		"dateISO": "2025-04-24",
		"conference": "Colloque annuel Humanistica 2025",
		"panelTitle": "Archives et patrimoines",
		"location": "Cheikh Anta Diop University",
		"type": "conference"
	},
	{
		"id": "archives-algorithms-iwac-2025",
		"title": "From Archives to Algorithms: Uncovering Transregional Islamic Connections through the Islam West Africa Collection (IWAC)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "11 September 2025",
		"dateISO": "2025-09-11",
		"conference": "Eighth European Congress on World and Global History",
		"panelTitle": "Global and Transregional Histories: Digitally Connected?",
		"location": "Linnaeus University",
		"type": "conference",
		"url": "https://eniugh.org/events/global-and-transregional-histories-digtally-connected/"
	},
	{
		"id": "beyond-keywords-ai-iwac-mcp-2026",
		"title": "Beyond Keywords: AI-Mediated Access to the Islam West Africa Collection through an MCP Server and Agent Skill",
		"authors": [
			"Frédérick Madore"
		],
		"date": "15 June 2026",
		"dateISO": "2026-06-15",
		"conference": "Eighth Conference on Digital Humanities and Digital History",
		"location": "University of Luxembourg",
		"type": "conference"
	},
	{
		"id": "beyond-keywords-entity-linking-cikm-2026",
		"title": "Beyond Keywords: Training-Free Entity Linking for Multilingual Research Metadata",
		"authors": [
			"Jiayu Yang",
			"Durgesh Nandini",
			"Mirco Schönfeld",
			"Frédérick Madore",
			"Neeraj Thandayan Viswajith",
			"Oliver Baumann"
		],
		"date": "9 November 2026",
		"dateISO": "2026-11-09",
		"conference": "35th International ACM Conference on Knowledge and Information Management (CIKM 2026)",
		"location": "Auditorium Parco della Musica, Rome",
		"type": "conference",
		"url": "https://cikm2026.diag.uniroma1.it/"
	},
	{
		"id": "collection-islam-humanites-2024",
		"title": "La Collection Islam Afrique de l'Ouest: enjeux éthiques et décolonisation des humanités numériques",
		"authors": [
			"Frédérick Madore"
		],
		"date": "28 June 2024",
		"dateISO": "2024-06-28",
		"conference": "12th International Conference on Mande Studies",
		"panelTitle": "Décoloniser l'organisation et les systèmes de connaissance",
		"location": "Institut des Sciences Humaines",
		"type": "conference"
	},
	{
		"id": "faith-based-student-organizations-2023",
		"title": "'Too Young,' 'Immature,' and not Committed Enough: The Decline of Faith-Based Student Organizations in Togo and Benin?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2 June 2023",
		"dateISO": "2023-06-02",
		"conference": "9th European Conference on African Studies (ECAS)",
		"panelTitle": "Training for good life or a good society? Religious students' individual and collective aspirations in public universities in sub-Saharan Africa",
		"location": "University of Cologne",
		"type": "conference"
	},
	{
		"id": "generations-imam-benin-2021",
		"title": "Generations at Odds: The Controversial Political Candidacy of an Imam in Benin (2019)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "18 June 2021",
		"dateISO": "2021-06-18",
		"conference": "11th International Conference of the Mande Studies Association (MANSA)",
		"panelTitle": "Re-Inventing Islam: Muslims as Agents of Change in 20th & 21st Century West Africa",
		"location": "Uppsala",
		"type": "conference"
	},
	{
		"id": "good-muslim-bad-muslim-togo-2019",
		"title": "'Good Muslim, Bad Muslim' in Togo: The Construction of a Religious Minority Amid a Constitutional Crisis (2017–2018)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "21 November 2019",
		"dateISO": "2019-11-21",
		"conference": "62nd Meeting of the African Studies Association (ASA)",
		"panelTitle": "Muslim Minorities in Africa",
		"location": "Boston",
		"type": "conference"
	},
	{
		"id": "hajj-organization-state-cote-divoire-2016",
		"title": "The Organization of the Hajj and the State: Cohesion and Rivalries within the Muslim Community of Côte d'Ivoire (1993-2006)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "3 December 2016",
		"dateISO": "2016-12-03",
		"conference": "59th Annual Meeting of the African Studies Association (ASA)",
		"panelTitle": "New Voices in the Study of Islam in Africa I: The Production and Contestation of Muslim Institutions in Contemporary Africa",
		"location": "Washington D.C.",
		"type": "conference"
	},
	{
		"id": "historian-vs-ai-ecas-2025",
		"title": "Historian vs AI: who reads and analyses archives best?",
		"authors": [
			"Vincent Hiribarren",
			"Frédérick Madore"
		],
		"date": "26 June 2025",
		"dateISO": "2025-06-26",
		"conference": "10th European Conference of African Studies (ECAS)",
		"panelTitle": "Digital Humanities (DH) and AI in African Studies: Opportunities, Challenges, and Decolonial Perspectives",
		"location": "Prague",
		"type": "conference"
	},
	{
		"id": "imams-espace-public-ouagadougou-2012",
		"title": "Imams et espace public à Ouagadougou depuis 1990: entre visibilité nouvelle et concertation entre les générations",
		"authors": [
			"Frédérick Madore"
		],
		"date": "4 May 2012",
		"dateISO": "2012-05-04",
		"conference": "42nd Annual Canadian Association of African Studies Conference (CAAS)",
		"panelTitle": "Dynamiques religieuses, visions de l'Autre et relations intergénérationnelles",
		"location": "Université Laval",
		"type": "conference"
	},
	{
		"id": "imams-islamic-preachers-ouagadougou-2013",
		"title": "Imams, Islamic Preachers and Public Space in Ouagadougou (Burkina Faso) since the 1990s: Toward New Intergenerational Relationships and a Muslim Public Sphere",
		"authors": [
			"Frédérick Madore"
		],
		"date": "29 March 2013",
		"dateISO": "2013-03-29",
		"conference": "2013 Africa Conference",
		"panelTitle": "Uses of Media in African Social Movements",
		"location": "University of Texas at Austin",
		"type": "conference"
	},
	{
		"id": "islam-burkina-faso-collection-omeka-2022",
		"title": "Publishing the Islam Burkina Faso Collection with Omeka S",
		"authors": [
			"Frédérick Madore"
		],
		"date": "8 July 2022",
		"dateISO": "2022-07-08",
		"conference": "3rd Annual conference of the Africa Multiple Cluster of Excellence \"Medialities\"",
		"panelTitle": "The Digital - a challenging solution or solvable challenge?",
		"location": "University of Bayreuth",
		"type": "conference"
	},
	{
		"id": "islam-ivoirien-burkinabe-numerique-2016",
		"title": "L'islam ivoirien et burkinabé à l'ère du numérique: des communautés musulmanes 2.0?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "14 January 2016",
		"dateISO": "2016-01-14",
		"conference": "3ème rencontre des Jeunes Chercheur.e.s en Études Africaines",
		"panelTitle": "Le religieux et ses réseaux",
		"location": "Paris Diderot University",
		"type": "conference"
	},
	{
		"id": "islam-peripheries-open-up-2026",
		"title": "Islam's \"Peripheries\": Digital Humanities, Algorithmic Analysis, and AI in West Africa and Central Asia",
		"authors": [
			"Frédérick Madore",
			"Aksana Ismailbekova"
		],
		"date": "4 March 2026",
		"dateISO": "2026-03-04",
		"conference": "Kick-off 'Open Up'",
		"location": "Xplanatorium Herrenhausen, Hanover",
		"type": "conference",
		"url": "https://www.volkswagenstiftung.de/sites/default/files/documents/Entwurf%20Programm_KickOff%20OpenUp_2026.pdf"
	},
	{
		"id": "islam-university-campuses-cote-divoire-2019",
		"title": "Islam on University Campuses in Côte d'Ivoire since the 1970s: 'Muslim Intellectuals' and Francophone Salafism",
		"authors": [
			"Issouf Binaté",
			"Frédérick Madore"
		],
		"date": "12 June 2019",
		"dateISO": "2019-06-12",
		"conference": "8th European Conference on African Studies (ECAS)",
		"location": "University of Edinburgh",
		"type": "conference"
	},
	{
		"id": "mediatisation-islam-ouagadougou-2013",
		"title": "La médiatisation de l'islam à Ouagadougou depuis 1991: entre normalisation des discours et nouvelle agency des musulmans",
		"authors": [
			"Frédérick Madore"
		],
		"date": "3 May 2013",
		"dateISO": "2013-05-03",
		"conference": "43rd Annual Canadian Association of African Studies Conference (CAAS)",
		"location": "University of Ottawa",
		"type": "conference"
	},
	{
		"id": "militantisme-islamique-feminin-burkina-2019",
		"title": "Militantisme islamique féminin au Burkina Faso: des processus sinueux d'émancipation religieuse",
		"authors": [
			"Frédérick Madore"
		],
		"date": "27 August 2019",
		"dateISO": "2019-08-27",
		"conference": "IIe Congrès international de l'Institut du Genre",
		"location": "University of Angers",
		"type": "conference"
	},
	{
		"id": "nouveau-dynamisme-salafisme-cote-divoire-2017",
		"title": "Le nouveau dynamisme du salafisme en Côte d'Ivoire: vers une radicalisation de l'islam ivoirien?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "3 August 2017",
		"dateISO": "2017-08-03",
		"conference": "10th International Conference of the Mande Studies Association (MANSA)",
		"location": "International University of Grand-Bassam",
		"type": "conference"
	},
	{
		"id": "precheurs-precheuses-burkina-faso-2013",
		"title": "Prêcheurs et prêcheuses au Burkina Faso: regards croisés sur leurs stratégies de communication religieuse depuis 1990",
		"authors": [
			"Muriel Gomez-Perez",
			"Frédérick Madore"
		],
		"date": "7 May 2013",
		"dateISO": "2013-05-07",
		"conference": "81e Congrès de l'Association Francophone pour le Savoir (Acfas)",
		"location": "Université Laval",
		"type": "conference"
	},
	{
		"id": "publishing-islam-burkina-faso-collection-2022",
		"title": "Publishing the Islam Burkina Faso Collection: Collaboration for Digital Scholarship",
		"authors": [
			"Frédérick Madore",
			"Perry Collins"
		],
		"date": "15 September 2022",
		"dateISO": "2022-09-15",
		"conference": "34th Deutscher Orientalistentag (DOT)",
		"location": "Free University of Berlin",
		"type": "conference"
	},
	{
		"id": "reconfiguring-archive-amira-2026",
		"title": "Reconfiguring the Archive: Relationality and Discovery in the Africa Multiple Interactive Research Atlas (AMIRA)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "1 July 2026",
		"dateISO": "2026-07-01",
		"conference": "Reimagining the Archive in the Post-Truth Era: An International Interdisciplinary Conference",
		"location": "Cory Library for Historical Research, Makhanda",
		"type": "conference",
		"url": "https://ru.za.libguides.com/ilamcoryconf"
	},
	{
		"id": "retour-note-synthese-dh-ia-reaf-2026",
		"title": "Retour sur une note de synthèse analysant la relation entre Humanités Numériques, l’IA et les Études Africaines (Hanovre, février 2026)",
		"authors": [
			"Vincent Hiribarren",
			"Frédérick Madore"
		],
		"date": "30 June 2026",
		"dateISO": "2026-06-30",
		"conference": "9èmes Rencontres des études africaines en France (REAF)",
		"panelTitle": "Humanités numériques (DH) et IA dans les études africaines",
		"location": "Paris",
		"type": "conference"
	},
	{
		"id": "rue-islam-associatif-enjeux-citoyens-2014",
		"title": "Rue, islam associatif et enjeux citoyens: retour sur des orientations récentes au Sénégal, au Burkina Faso et en Côte d'Ivoire",
		"authors": [
			"Muriel Gomez-Perez",
			"Frédérick Madore",
			"Mathias Boukary Savadogo"
		],
		"date": "29 October 2014",
		"dateISO": "2014-10-29",
		"conference": "International Conference Le clos et l'ouvert. Acteurs religieux, acteurs sociaux et usages de la rue (Europe, Afrique, Asie, Amériques)",
		"location": "Gaston Berger University",
		"type": "conference"
	},
	{
		"id": "salafisme-securitisation-benin-togo-2022",
		"title": "Salafisme et sécuritisation de l'islam au Bénin et au Togo: instrumentalisations diverses d'une 'menace étrangère'",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2 June 2022",
		"dateISO": "2022-06-02",
		"conference": "Islamist Protest, Terrorism and (In)Security in Africa Conference",
		"location": "University of Maroua",
		"type": "conference"
	},
	{
		"id": "serveurs-mcp-glam-africains-stias-2026",
		"title": "Les serveurs MCP pour les GLAM africains : une voie d'avenir à l'ère de l'IA ?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "23 September 2026",
		"dateISO": "2026-09-23",
		"conference": "Humanités numériques et intelligence artificielle en études africaines : vers des pratiques durables et équitables",
		"location": "Stellenbosch Institute for Advanced Study (STIAS), Stellenbosch",
		"type": "workshop",
		"url": "https://fmadore.github.io/stias-dh-ai-workshop-2026/"
	},
	{
		"id": "zmo-kitchen-talks-ai-islamic-african-studies",
		"title": "Artificial Intelligence (AI) in African and Islamic Studies",
		"authors": [
			"Elisa Nobel-Dilaty",
			"Frédérick Madore"
		],
		"date": "11 December 2025",
		"dateISO": "2025-12-11",
		"conference": "ZMO Kitchen Talks",
		"episode": 14,
		"location": "Leibniz-Zentrum Moderner Orient",
		"type": "podcast",
		"url": "https://www.zmo.de/en/kitchen-talks"
	},
	{
		"id": "responsible-ai-access-mcp-server-2026",
		"title": "Responsible AI Access to Research Repositories: An MCP Server for African Studies Data",
		"authors": [
			"Frédérick Madore",
			"Oliver Baumann",
			"Durgesh Nandini",
			"Neeraj Thandayan Viswajith",
			"Jiayu Yang",
			"Mirco Schönfeld"
		],
		"date": "25 September 2026",
		"dateISO": "2026-09-25",
		"conference": "AI Day 2026, Research Center for AI in Science and Society (RAIS²)",
		"location": "University of Bayreuth",
		"type": "poster",
		"url": "https://www.rais2.uni-bayreuth.de/en/events/ai_day_2026/index.html"
	},
	{
		"id": "ai-africa-symposium-kansas-2026",
		"title": "University of Kansas AI and Africa Symposium",
		"authors": [
			"Frédérick Madore"
		],
		"date": "17 September 2026",
		"dateISO": "2026-09-17",
		"conference": "AI and Africa Symposium",
		"panelTitle": "Panel I: African History",
		"location": "University of Kansas, Lawrence",
		"type": "lecture",
		"url": "https://calendar.ku.edu/event/ai-and-africa-symposium"
	},
	{
		"id": "associations-chretiennes-islamiques-campus",
		"title": "Les associations chrétiennes et islamiques sur les campus de l'Université d'Abomey-Calavi et de l'Université de Lomé depuis 1970: la laïcité à l'université face à l'activisme religieux",
		"authors": [
			"Frédérick Madore"
		],
		"date": "8 March 2022",
		"dateISO": "2022-03-08",
		"conference": "Laboratoire d'Analyse et de Recherche, Religions, Espaces et Développement (LARRED)",
		"location": "Université d'Abomey-Calavi",
		"type": "lecture"
	},
	{
		"id": "collection-islam-afrique-ouest",
		"title": "La Collection Islam Afrique de l'Ouest: nouvelles perspectives sur l'histoire des communautés musulmanes via la presse et les humanités numériques",
		"authors": [
			"Frédérick Madore"
		],
		"date": "25 March 2024",
		"dateISO": "2024-03-25",
		"conference": "Enjeux éthiques et juridiques au diapason des données de la recherche en études aréales",
		"location": "Aix-en-Provence, Maison méditerranéenne des sciences de l'Homme",
		"type": "workshop"
	},
	{
		"id": "current-dynamics-islam-burkina-faso",
		"title": "Current Dynamics of Islam in Burkina Faso",
		"authors": [
			"Frédérick Madore"
		],
		"date": "16 November 2018",
		"dateISO": "2018-11-16",
		"conference": "Sahel Seminars",
		"location": "University of Florida",
		"type": "lecture",
		"url": "https://sahelresearch.africa.ufl.edu/events-activities/sahel-seminars/"
	},
	{
		"id": "defense-laicite-musulmans-burkina",
		"title": "La défense de la laïcité de l'État, un outil de revendication politique pour les musulmans au Burkina Faso (depuis 1960)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "4 July 2019",
		"dateISO": "2019-07-04",
		"conference": "Debating Laïcité in the Sahel: What Future for Secularism?",
		"location": "West African Research Center",
		"type": "workshop"
	},
	{
		"id": "digital-history-exe",
		"title": "DigitalHistory.Exe: Running New Programs on Old Files",
		"authors": [
			"Frédérick Madore"
		],
		"date": "8 April 2025",
		"dateISO": "2025-04-08",
		"conference": "Master Class",
		"location": "Leibniz Centre for Contemporary History Potsdam (ZZF)",
		"type": "lecture",
		"url": "https://web.archive.org/web/20250411145918/https://zzf-potsdam.de/forschung/doktorand_innen/master-class"
	},
	{
		"id": "digital-hoarding-open-archives-warsaw-2026",
		"title": "From Digital Hoarding to Open Archives: Using AI Agents to Unlock West African Newspaper Collections",
		"authors": [
			"Frédérick Madore"
		],
		"date": "16 April 2026",
		"dateISO": "2026-04-16",
		"conference": "Non-European Approaches in European Academia: Strategies for De-Europeanizing Research",
		"location": "Tadeusz Manteuffel Institute of History, Polish Academy of Sciences, Warsaw",
		"type": "workshop"
	},
	{
		"id": "digital-humanities-islam-burkina-faso",
		"title": "Digital Humanities in the Making: The Islam Burkina Faso Collection",
		"authors": [
			"Frédérick Madore"
		],
		"date": "16 September 2022",
		"dateISO": "2022-09-16",
		"conference": "Open Day at ZMO",
		"location": "Leibniz-Zentrum Moderner Orient",
		"type": "lecture"
	},
	{
		"id": "dormant-digital-collections-ai-triage-dga-2026",
		"title": "Dormant Digital Collections, AI Triage: Lessons from the Islam West Africa Collection and Beyond",
		"authors": [
			"Frédérick Madore"
		],
		"date": "6 May 2026",
		"dateISO": "2026-05-06",
		"conference": "Deutsche Gesellschaft für Asienforschung (DGA)",
		"panelTitle": "DGA-Roundtable-Reihe Sommersemester 2026",
		"location": "Leibniz-Zentrum Moderner Orient",
		"type": "lecture",
		"url": "https://asienforschung.de/events/roundtable-2-digital-humanities-und-kuenstliche-intelligenz-in-den-regionalwissenschaften/"
	},
	{
		"id": "elites-musulmanes-cote-divoire-burkina-faso",
		"title": "Les élites musulmanes en Côte d'Ivoire et au Burkina Faso depuis 1990 : des mobilisations politiques contrastées",
		"authors": [
			"Frédérick Madore"
		],
		"date": "25 September 2018",
		"dateISO": "2018-09-25",
		"conference": "Conférences midi du CIRAM",
		"location": "Université Laval",
		"type": "lecture",
		"url": "https://www.ciram.hei.ulaval.ca/les-elites-musulmanes-en-cote-divoire-et-au-burkina-faso-depuis-1990-des-mobilisations-politiques-contrastees/"
	},
	{
		"id": "emancipation-feminine-militantisme-islamique",
		"title": "Émancipation féminine et militantisme islamique en Afrique de l'Ouest depuis 1980: quelques enseignements du Burkina Faso, de la Côte d'Ivoire, du Togo et du Bénin",
		"authors": [
			"Frédérick Madore"
		],
		"date": "22 March 2022",
		"dateISO": "2022-03-22",
		"conference": "Atelier international Femmes africaines dans une société d'hommes: espaces contraints, habilité sociale et formes d'émancipation",
		"location": "Université de Kabala",
		"type": "workshop"
	},
	{
		"id": "etablir-faitiere-islamique",
		"title": "L'ambition fédératrice à l'épreuve de la diversité : étude comparative des faîtières islamiques au Burkina Faso, Togo, Bénin et Côte d'Ivoire",
		"authors": [
			"Frédérick Madore"
		],
		"date": "4 March 2025",
		"dateISO": "2025-03-04",
		"conference": "Workshop Religiosités et vies associatives en Afrique: entre stratégies d'organisation et vies en mouvement",
		"location": "Puidoux",
		"type": "workshop"
	},
	{
		"id": "formation-recherche-en-ligne-niamey",
		"title": "Formation en recherche en ligne",
		"authors": [
			"Frédérick Madore"
		],
		"date": "23 March 2024",
		"dateISO": "2024-03-23",
		"conference": "Atelier",
		"location": "Laboratoire d'Etudes et de Recherches sur les Dynamiques Sociales et le Développement Local (LASDEL)",
		"type": "lecture"
	},
	{
		"id": "formation-recherches-en-ligne-ouagadougou",
		"title": "Formation en recherche en ligne",
		"authors": [
			"Frédérick Madore"
		],
		"date": "19 July 2023",
		"dateISO": "2023-07-19",
		"conference": "Atelier",
		"location": "Université Joseph Ki-Zerbo",
		"type": "lecture"
	},
	{
		"id": "histoire-communautes-musulmanes-ouest-africaines-2025",
		"title": "L'histoire des communautés musulmanes ouest-africaines : approches et perspectives des humanités numériques",
		"authors": [
			"Frédérick Madore"
		],
		"date": "20 May 2025",
		"dateISO": "2025-05-20",
		"conference": "Séminaire 'Actualité de la recherche en anthropologie sociale en Afrique' animé par Sophie Bava, Alice Degorce et Marie Miran",
		"location": "École des hautes études en sciences sociales (EHESS)",
		"type": "lecture",
		"url": "https://doi.org/10.58079/13pmz"
	},
	{
		"id": "humanites-numeriques-ia-ecole-chartes-2025",
		"title": "Humanités numériques et flux de recherche augmentés par l'IA pour la Collection islam Afrique de l'Ouest",
		"authors": [
			"Frédérick Madore"
		],
		"date": "22 May 2025",
		"dateISO": "2025-05-22",
		"conference": "Work talk",
		"location": "École nationale des chartes",
		"type": "lecture"
	},
	{
		"id": "interfaith-coexistence-campuses",
		"title": "Interfaith coexistence on the campuses of the University of Lomé (Togo) and the University of Abomey-Calavi (Benin) since the 1970s",
		"authors": [
			"Frédérick Madore"
		],
		"date": "6 June 2023",
		"dateISO": "2023-06-06",
		"conference": "Workshop Religion for Peace? Identifying Conditions and Mechanisms of Interfaith Peace",
		"location": "Berlin, German Institute for Global and Area Studies (GIGA)",
		"type": "workshop"
	},
	{
		"id": "islam-algorithms-ai",
		"title": "Islam, Algorithms and AI",
		"authors": [
			"Frédérick Madore"
		],
		"date": "18 July 2024",
		"dateISO": "2024-07-18",
		"conference": "ZMO Sommerfest",
		"location": "Leibniz-Zentrum Moderner Orient",
		"type": "lecture"
	},
	{
		"id": "islam-burkina-cote-ivoire",
		"title": "L'islam au Burkina Faso et en Côte d'Ivoire: éveil et radicalisation?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "13 February 2017",
		"dateISO": "2017-02-13",
		"conference": "76e conférence Archéopat",
		"location": "Université du Québec à Rimouski",
		"type": "lecture"
	},
	{
		"id": "islam-peripheries-dh-ai-west-africa-central-asia-2026",
		"title": "Islam's \"Peripheries\": Digital Humanities, Algorithmic Analysis, and AI in West Africa and Central Asia",
		"authors": [
			"Aksana Ismailbekova",
			"Frédérick Madore"
		],
		"date": "29 June 2026",
		"dateISO": "2026-06-29",
		"conference": "Seminar series 'Digital History in/of Central Asia and the South Caucasus'",
		"location": "Friedrich-Alexander-Universität Erlangen-Nürnberg",
		"type": "lecture",
		"url": "https://www.osteuropa.phil.fau.de/digital-history-seminars/"
	},
	{
		"id": "militantisme-bissap-feminisme-islamique-2018",
		"title": "'Militantisme bissap', féminisme islamique et entrepreneuriat religieux en Côte d'Ivoire: Aminata Kane Koné, une figure de la réussite",
		"authors": [
			"Frédérick Madore"
		],
		"date": "8 September 2018",
		"dateISO": "2018-09-08",
		"conference": "Workshop Entrepreneuriat religieux et figures de la réussite en Afrique subsaharienne: terrains et concepts",
		"location": "Université Laval",
		"type": "workshop"
	},
	{
		"id": "militantisme-islamique-campus-lome",
		"title": "Militantisme islamique sur le campus de l'Université de Lomé (Togo) depuis les années 1980: être musulman en contexte minoritaire, laïc et (semi-)autoritaire",
		"authors": [
			"Frédérick Madore"
		],
		"date": "22 February 2022",
		"dateISO": "2022-02-22",
		"conference": "Chaire de recherche sur l'islam contemporain en Afrique de l'Ouest",
		"location": "Université du Québec à Montréal",
		"type": "lecture"
	},
	{
		"id": "militantisme-religieux-campus-benin-togo-2025",
		"title": "Militantisme religieux sur les campus universitaires : le cas du Bénin et du Togo",
		"authors": [
			"Frédérick Madore"
		],
		"date": "28 May 2025",
		"dateISO": "2025-05-28",
		"conference": "Séminaire 'Histoire et anthropologie comparées du fait religieux en Afrique' animé par Marie Miran",
		"location": "Humathèque Condorcet",
		"type": "lecture",
		"url": "https://doi.org/10.58079/13pmz"
	},
	{
		"id": "muslim-intellectuals-francophone-salafis",
		"title": "'Muslim Intellectuals' and 'Francophone Salafis' in West Africa: New Religious Elites?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "1 October 2020",
		"dateISO": "2020-10-01",
		"conference": "Hamilton Lugar School of Global and International Studies",
		"location": "Indiana University Bloomington",
		"type": "lecture"
	},
	{
		"id": "point-de-passage-frontieres-religieuses",
		"title": "Point de passage et frontières religieuses",
		"authors": [
			"Frédérick Madore"
		],
		"date": "3 June 2022",
		"dateISO": "2022-06-03",
		"conference": "Workshop Point de passage et frontières religieuses",
		"location": "Laboratoire d'Etudes et de Recherches sur les Dynamiques Sociales et le Développement Local (LASDEL)",
		"type": "workshop"
	},
	{
		"id": "political-mobilizations-burkina-faso",
		"title": "Political mobilizations in Burkina Faso",
		"authors": [
			"Frédérick Madore"
		],
		"date": "27 November 2020",
		"dateISO": "2020-11-27",
		"conference": "Workshop Political mobilizations in Burkina Faso",
		"location": "University of Ottawa",
		"type": "workshop"
	},
	{
		"id": "presentation-discussion-religious-activism-campuses-ciram-2025",
		"title": "Présentation-discussion de l'ouvrage Religious Activism on Campuses in Togo and Benin",
		"authors": [
			"Frédérick Madore"
		],
		"date": "6 November 2025",
		"dateISO": "2025-11-06",
		"conference": "Conférences midi du CIRAM",
		"location": "Université Laval",
		"type": "lecture",
		"url": "https://www.ciram.hei.ulaval.ca/activite/discussion-autour-du-livre-religious-activism-on-campuses-in-togo-and-benin/"
	},
	{
		"id": "public-islam-cote-ivoire-burkina-faso",
		"title": "Public Islam in Côte d'Ivoire and Burkina Faso: a comparative overview of the use of media by Muslims since the 1970s",
		"authors": [
			"Frédérick Madore"
		],
		"date": "24 January 2020",
		"dateISO": "2020-01-24",
		"conference": "Workshop Media and 'Public' Islam in Africa & Elsewhere",
		"location": "University of Florida",
		"type": "workshop"
	},
	{
		"id": "questions-islam-afrique-ouest-2025",
		"title": "Questions d'islam en Afrique de l'Ouest. Les enjeux et défis de la recherche avec les archives physiques et numériques",
		"authors": [
			"Frédérick Madore"
		],
		"date": "12 May 2025",
		"dateISO": "2025-05-12",
		"conference": "Séminaire de formation à la recherche en Afrique (SéFRA) animé par Fabienne Samson",
		"location": "École des hautes études en sciences sociales (EHESS)",
		"type": "lecture",
		"url": "https://doi.org/10.58079/13pmz"
	},
	{
		"id": "recherche-documentaire-zotero",
		"title": "La recherche documentaire en libre accès et la gestion de références bibliographiques avec Zotero",
		"authors": [
			"Frédérick Madore"
		],
		"date": "7 June 2019",
		"dateISO": "2019-06-07",
		"conference": "Université Alassane Ouattara",
		"location": "Université Alassane Ouattara",
		"type": "lecture"
	},
	{
		"id": "rencontre-chretiens-musulmans-2025",
		"title": "Rencontre entre chrétiens et musulmans: au-delà du binaire coexistence pacifique/conflits religieux",
		"authors": [
			"Frédérick Madore"
		],
		"date": "21 May 2025",
		"dateISO": "2025-05-21",
		"conference": "Séminaire 'Histoire et anthropologie comparées du fait religieux en Afrique' animé par Marie Miran",
		"location": "Humathèque Condorcet",
		"type": "lecture",
		"url": "https://doi.org/10.58079/13pmz"
	},
	{
		"id": "repenser-categorisation-religieuse-benin",
		"title": "Repenser la catégorisation religieuse à partir du Bénin, terre du vodun",
		"authors": [
			"Frédérick Madore",
			"Fiacre Anato"
		],
		"date": "5 December 2024",
		"dateISO": "2024-12-05",
		"conference": "Workshop L'Afrique des religions à l'épreuve des chiffres et des catégorisations",
		"location": "Université Paris Cité",
		"type": "workshop"
	},
	{
		"id": "representations-islam-muslims-togo",
		"title": "Representations of Islam and Muslims in Togo's State-Owned Newspapers Since the 1960s: From Loyal Religious Minority to Potential Threat",
		"authors": [
			"Frédérick Madore"
		],
		"date": "9 October 2020",
		"dateISO": "2020-10-09",
		"conference": "Workshop Islam, Media, and Popular Culture in Africa and Elsewhere",
		"location": "University of Florida",
		"type": "workshop"
	},
	{
		"id": "salafisme-pentecotisme-campus-benin-togo",
		"title": "Salafisme et pentecôtisme sur les campus au Bénin et au Togo: la laïcité à l'université face à l'activisme religieux",
		"authors": [
			"Frédérick Madore"
		],
		"date": "8 April 2021",
		"dateISO": "2021-04-08",
		"conference": "Conférences midi du CIRAM",
		"location": "Université Laval",
		"type": "lecture"
	},
	{
		"id": "tracing-islamic-knowledge-production",
		"title": "Tracing Islamic Knowledge Production in Francophone West African Newspapers (1990-Present)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2 December 2024",
		"dateISO": "2024-12-02",
		"conference": "Workshop Perspectives in Motion: Conceptual Fields from the Global South",
		"location": "Leibniz-Zentrum Moderner Orient",
		"type": "workshop"
	},
	{
		"id": "union-islamique-benin-elections",
		"title": "L'Union Islamique du Bénin et les élections législatives: comment comprendre la crise interne",
		"authors": [
			"Frédérick Madore"
		],
		"date": "28 May 2019",
		"dateISO": "2019-05-28",
		"conference": "Université d'Abomey-Calavi",
		"location": "Université d'Abomey-Calavi",
		"type": "lecture"
	},
	{
		"id": "uppsala-university-2025",
		"title": "Building AI Pipelines for African Digital Collections: Lessons from the Islam West Africa Collection",
		"authors": [
			"Frédérick Madore"
		],
		"date": "5 December 2025",
		"dateISO": "2025-12-05",
		"conference": "Work talk ALMEDA project",
		"location": "Uppsala University",
		"type": "lecture"
	},
	{
		"id": "when-ai-meets-the-archive-2025",
		"title": "When AI Meets the Archive: Transforming the Islam West Africa Collection with Large Language Models",
		"authors": [
			"Frédérick Madore"
		],
		"date": "20 August 2025",
		"dateISO": "2025-08-20",
		"conference": "SADiLaR Digital Humanities colloquia",
		"location": "North-West University",
		"type": "lecture",
		"url": "https://sadilar.org/en/dh-colloquium/"
	},
	{
		"id": "young-muslims-civic-engagement-burkina",
		"title": "'Plus rien ne sera jamais comme avant'? Young Muslims' new forms of civic engagement in Burkina Faso (2014-2017)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "19 October 2018",
		"dateISO": "2018-10-19",
		"conference": "Workshop Muslim Youth and Lived Islam in Africa & Beyond",
		"location": "University of Florida",
		"type": "workshop"
	},
	{
		"id": "yovo-historian-benin-togo",
		"title": "A 'Yovo' Historian in Benin and Togo: Conducting Fieldwork in Times of Pandemic and Fears of Jihadism Spreading",
		"authors": [
			"Frédérick Madore"
		],
		"date": "14 June 2022",
		"dateISO": "2022-06-14",
		"conference": "Workshop Researching Religion, Morality and Boko in West Africa",
		"location": "Martin-Luther-Universität Halle-Wittenberg",
		"type": "workshop"
	}
];
