// AUTO-GENERATED by scripts/generate-summaries.mjs — DO NOT EDIT.
// Regenerate with `npm run gen:summaries` (runs automatically via the prebuild hook).
/* eslint-disable */
import type { DigitalHumanitiesSummary } from '$lib/types/digitalHumanities';
export const dhProjectSummaries: DigitalHumanitiesSummary[] = [
	{
		"id": "amira",
		"title": "Africa Multiple Interactive Research Atlas (AMIRA)",
		"years": "2026",
		"shortDescription": "Interactive research atlas for the Africa Multiple Cluster of Excellence — browse, filter, and compare projects, people, institutions, and research items across partner centres in Africa, Brazil, and Germany.",
		"imageUrl": "/images/digital-humanities/amira.webp",
		"featured": true,
		"order": 2,
		"links": [
			{
				"url": "https://data.africamultiple.uni-bayreuth.de/s/amira"
			},
			{
				"url": "https://github.com/AM-Digital-Research-Environment/DRE-theme",
				"label": "DRE-theme",
				"type": "code"
			},
			{
				"url": "https://github.com/AM-Digital-Research-Environment/DRESearch",
				"label": "DRESearch",
				"type": "code"
			},
			{
				"url": "https://github.com/AM-Digital-Research-Environment/ResourceVisualizations",
				"label": "ResourceVisualizations",
				"type": "code"
			},
			{
				"url": "https://github.com/AM-Digital-Research-Environment/DRE-SEO",
				"label": "DRE-SEO",
				"type": "code"
			},
			{
				"url": "https://github.com/AM-Digital-Research-Environment/amira-mcp-server",
				"label": "amira-mcp-server",
				"type": "code"
			}
		],
		"skills": [
			"Omeka S",
			"Typesense",
			"Docker",
			"Nginx",
			"Svelte 5",
			"TypeScript",
			"ECharts",
			"MapLibre GL",
			"MongoDB",
			"Model Context Protocol",
			"Data visualisation",
			"Network graphs"
		]
	},
	{
		"id": "burkina-faso-digital-exhibits",
		"title": "Digital Exhibits on Islam in Burkina Faso",
		"years": "2021",
		"shortDescription": "Two digital exhibits featuring curated materials from the Islam West Africa Collection, each with an interactive timeline, contextual narratives, and selective bibliography.",
		"imageUrl": "/images/digital-humanities/burkina-faso-digital-exhibits.webp",
		"order": 9,
		"links": [
			{
				"url": "https://islam.zmo.de/s/westafrica/page/hajj-bf"
			},
			{
				"url": "https://islam.zmo.de/s/westafrica/page/student-activism-bf"
			}
		],
		"skills": [
			"Timeline JS"
		]
	},
	{
		"id": "dh-ai-african-studies",
		"title": "Charting New Territory: Digital Humanities and AI in African Studies",
		"years": "2025-2026",
		"shortDescription": "The website for a VolkswagenStiftung scoping workshop held in Hanover in February 2026, which documents its programme and 26 participants and carries a filterable bibliography of over 200 works, a concept map of the literature, six filmed interviews, and the forthcoming position paper.",
		"imageUrl": "/images/digital-humanities/dh-ai-african-studies.webp",
		"order": 4,
		"links": [
			{
				"url": "https://fmadore.github.io/dh-ai-african-studies-2026/"
			},
			{
				"url": "https://github.com/fmadore/dh-ai-african-studies-2026",
				"label": "dh-ai-african-studies-2026",
				"type": "code"
			}
		],
		"skills": [
			"Svelte 5",
			"SvelteKit",
			"TypeScript",
			"Tailwind CSS",
			"D3.js",
			"Leaflet",
			"Python",
			"Zotero",
			"Metadata Standards",
			"Data Visualisation",
			"Network graphs"
		],
		"seoKeywords": [
			"digital humanities",
			"artificial intelligence",
			"African studies",
			"scoping workshop",
			"VolkswagenStiftung",
			"concept map",
			"network visualisation",
			"bibliography",
			"data sovereignty",
			"digital colonialism",
			"African language technologies",
			"AI ethics"
		]
	},
	{
		"id": "genocide-at-the-security-council",
		"title": "Genocide at the Security Council",
		"years": "2026-",
		"shortDescription": "A reproducible pipeline and interactive dashboard tracing how the word genocide was used across 106,302 UN Security Council speeches, 1992–2023. Built with Python and SvelteKit, with every figure traceable to the script that made it.",
		"imageUrl": "/images/digital-humanities/genocide-at-the-security-council.webp",
		"order": 0,
		"links": [
			{
				"url": "https://fmadore.github.io/genocide-at-the-security-council/"
			},
			{
				"url": "https://github.com/fmadore/genocide-at-the-security-council",
				"label": "genocide-at-the-security-council",
				"type": "code"
			},
			{
				"url": "https://doi.org/10.7910/DVN/KGVSYH",
				"label": "Source corpus (Dataverse)",
				"type": "data"
			}
		],
		"skills": [
			"Python",
			"pandas",
			"Corpus Linguistics",
			"NLP",
			"Text Analysis",
			"Reproducible Research",
			"SvelteKit",
			"Svelte 5",
			"TypeScript",
			"ECharts",
			"MapLibre GL",
			"Data Visualisation",
			"GitHub Actions"
		],
		"seoKeywords": [
			"genocide",
			"UN Security Council",
			"corpus linguistics",
			"discourse analysis",
			"text as data",
			"digital humanities",
			"computational social science",
			"lexicometry",
			"concordance",
			"keyword in context",
			"reproducible research",
			"data visualisation",
			"international relations",
			"United Nations"
		]
	},
	{
		"id": "global-heshmat",
		"title": "Global Heshmat",
		"years": "2026",
		"shortDescription": "An interactive map tracing the public artworks of the Egyptian sculptor Hassan Heshmat across ten countries, developed for the Leibniz-Zentrum Moderner Orient (ZMO). Built with SvelteKit and MapLibre GL JS.",
		"imageUrl": "/images/digital-humanities/global-heshmat.webp",
		"order": 3,
		"links": [
			{
				"url": "https://heshmat.zmo.de/"
			},
			{
				"url": "https://github.com/ZMO-Berlin/Global-Heshmat",
				"label": "Global-Heshmat",
				"type": "code"
			}
		],
		"skills": [
			"Svelte 5",
			"SvelteKit",
			"TypeScript",
			"MapLibre GL",
			"WebGL",
			"Interactive mapping",
			"Data visualisation"
		]
	},
	{
		"id": "islam-burkina-faso-collection",
		"title": "Islam Burkina Faso Collection",
		"years": "2018-2023",
		"shortDescription": "An open-access digital database developed to address a critical gap in research infrastructure for West African Islamic studies, containing over 2,900 documents on Islam and Muslims in Burkina Faso. Now archived within the Islam West Africa Collection (IWAC).",
		"imageUrl": "/images/digital-humanities/islam-burkinafaso-banner.webp",
		"award": "I won a <a href='https://etcl.uvic.ca/2023/01/17/2023-open-scholarship-awards/' target='_blank' rel='noopener noreferrer'>2023 Emerging Open Scholarship Award</a>, sponsored by the <a href='https://c-ski.ca/' target='_blank' rel='noopener noreferrer'>Canadian Social Knowledge Institute (C-SKI)</a> and its partners, for my work on the Islam Burkina Faso Collection.",
		"reviews": [
			{
				"text": "Robert Launay, \"Review: Islam Burkina Faso Collection\", <em>Reviews in Digital Humanities</em> 4, no. 4 (2023).",
				"url": "https://doi.org/10.21428/3e88f64f.89e71c81",
				"quote": "The collection is an invaluable research tool for scholars in or outside Burkina Faso, offering access to material that is difficult or impossible to find outside — and sometimes even inside — the country [...] The collection is an extremely important contribution and critical aid to scholarship on Islam in West Africa."
			},
			{
				"text": "Vincent Hiribarren, \"Review of Frédérick Madore 'Islam Burkina Faso Collection'\", <em>Mande Studies</em> 24 (2022): 325-27.",
				"url": "https://doi.org/10.2979/mnd.2022.a908483",
				"quote": "Obviously, this is an impressive achievement, and the project launched in 2021 by Frédérick Madore will become an increasingly useful repository since travel in and to Burkina Faso has become more difficult. [...] What the interface also clearly offers is a potential re-interpretation of the documents used by Madore and new possible enquiries for students and professional researchers. The two exhibitions available on the website demonstrate the potential of such an approach and the way the database can also become part of our teaching. [...] the Islam Burkina Faso Collection is already a fascinating resource with a significant potential for future researchers."
			}
		],
		"publication": {
			"text": "To learn more about this project, see Frédérick Madore, \"La Collection Islam Burkina Faso : promesses et défis des humanités numériques\". <em>Revue d'Histoire Contemporaine de l'Afrique</em> 2021.",
			"url": "https://doi.org/10.51185/journals/rhca.2021.e610"
		},
		"order": 10,
		"links": [
			{
				"url": "https://web.archive.org/web/20240312164955/https://islam.domains.uflib.ufl.edu/s/bf/page/home",
				"label": "islam.domains.uflib.ufl.edu (Internet Archive)"
			}
		],
		"skills": [
			"Omeka S",
			"Tesseract",
			"Metadata Standards",
			"OpenRefine",
			"Zotero",
			"Linked Data"
		]
	},
	{
		"id": "iwac-ai-pipelines",
		"title": "IWAC AI Pipelines",
		"years": "2026",
		"shortDescription": "Python workflows for processing the Islam West Africa Collection using Large Language Models—automating OCR, NER, transcription, and summarisation at scale.",
		"imageUrl": "/images/digital-humanities/iwac-ai-pipelines.webp",
		"order": 3,
		"links": [
			{
				"url": "https://github.com/fmadore/iwac-ai-pipelines",
				"label": "iwac-ai-pipelines",
				"type": "code"
			},
			{
				"url": "https://github.com/fmadore/AI-NER-Validator",
				"label": "AI-NER-Validator",
				"type": "code"
			}
		],
		"skills": [
			"Python",
			"LLM",
			"Prompt Engineering",
			"OCR",
			"HTR",
			"NER",
			"NLP",
			"Docker",
			"Omeka S API"
		],
		"seoKeywords": [
			"AI pipelines",
			"LLM",
			"OCR",
			"NER",
			"named entity recognition",
			"handwritten text recognition",
			"audio transcription",
			"digital humanities",
			"Islam West Africa",
			"IWAC",
			"Google Gemini",
			"OpenAI",
			"Mistral",
			"archival processing"
		]
	},
	{
		"id": "iwac-bibliographic-data-wikidata",
		"title": "IWAC Bibliographic Data on Wikidata",
		"years": "2023",
		"shortDescription": "Over 850 bibliographical references from the Islam West Africa Collection uploaded to Wikidata, enabling SPARQL queries and automatic visualisations through Scholia.",
		"imageUrl": "/images/digital-humanities/iwac-bibliographic-data-wikidata.svg",
		"order": 8,
		"links": [
			{
				"url": "https://scholia.toolforge.org/topic/Q3155361",
				"label": "Islam in Benin",
				"type": "data"
			},
			{
				"url": "https://scholia.toolforge.org/topic/Q3081878",
				"label": "Islam in Burkina Faso",
				"type": "data"
			},
			{
				"url": "https://scholia.toolforge.org/topic/Q4119820",
				"label": "Islam in Côte d'Ivoire",
				"type": "data"
			},
			{
				"url": "https://scholia.toolforge.org/topic/Q3087639",
				"label": "Islam in Niger",
				"type": "data"
			},
			{
				"url": "https://scholia.toolforge.org/topic/Q522809",
				"label": "Islam in Togo",
				"type": "data"
			}
		],
		"skills": [
			"Wikidata",
			"OpenRefine",
			"Scholia",
			"SPARQL",
			"Linked Data",
			"Metadata Standards"
		]
	},
	{
		"id": "iwac-mcp-server",
		"title": "IWAC MCP Server",
		"years": "2026-",
		"shortDescription": "A Model Context Protocol server and companion agent skill that give AI assistants structured, read-only access to the Islam West Africa Collection — overcoming the limitations of keyword search through structured, AI-mediated access to the corpus.",
		"imageUrl": "/images/digital-humanities/iwac-mcp-server.webp",
		"order": 0,
		"links": [
			{
				"url": "https://islam.zmo.de/s/westafrica/page/ai-access"
			},
			{
				"url": "https://github.com/fmadore/iwac-mcp-server",
				"type": "code"
			}
		],
		"skills": [
			"Python",
			"Model Context Protocol",
			"LLM",
			"Prompt Engineering",
			"pandas",
			"Hugging Face",
			"JSON",
			"Omeka S API"
		],
		"seoKeywords": [
			"Model Context Protocol",
			"MCP server",
			"AI assistants",
			"digital humanities",
			"Islam West Africa",
			"IWAC",
			"semantic search",
			"agent skill",
			"data sovereignty",
			"open standard",
			"Claude",
			"archival research"
		]
	},
	{
		"id": "iwac-sentiment-analysis",
		"title": "IWAC Sentiment Analysis",
		"years": "2025",
		"shortDescription": "Interactive visualisation of sentiment patterns in 12,280+ West African press articles on Islam, with multi-model comparison (ChatGPT, Gemini, Mistral) and third-party arbitration.",
		"imageUrl": "/images/digital-humanities/iwac-sentiment-analysis.webp",
		"order": 2,
		"links": [
			{
				"url": "https://iwac.frederickmadore.com/sentiment-analysis/"
			},
			{
				"url": "https://github.com/fmadore/IWAC-sentiment-analysis",
				"label": "IWAC-sentiment-analysis",
				"type": "code"
			}
		],
		"skills": [
			"Svelte",
			"Data Visualisation",
			"ECharts",
			"Vite",
			"Tailwind CSS",
			"TypeScript",
			"Prompt Engineering",
			"LLM",
			"JSON"
		]
	},
	{
		"id": "iwac",
		"title": "Islam West Africa Collection",
		"years": "2023-",
		"shortDescription": "An open-access archive of over 14,700 items on Islam and Muslims in Benin, Burkina Faso, Côte d'Ivoire, Niger, Nigeria, and Togo.",
		"imageUrl": "/images/digital-humanities/IWAC.webp",
		"featured": true,
		"order": 1,
		"links": [
			{
				"url": "https://islam.zmo.de/s/westafrica"
			},
			{
				"url": "https://islam.zmo.de/s/afrique_ouest"
			},
			{
				"url": "https://github.com/fmadore/IwacSearch",
				"label": "IwacSearch",
				"type": "code"
			},
			{
				"url": "https://github.com/fmadore/IwacVisualizations",
				"label": "IwacVisualizations",
				"type": "code"
			},
			{
				"url": "https://github.com/fmadore/IWAC-SEO",
				"label": "IWAC-SEO",
				"type": "code"
			},
			{
				"url": "https://github.com/fmadore/IWAC-theme",
				"label": "IWAC-theme",
				"type": "code"
			},
			{
				"url": "https://github.com/fmadore/IWAC-Hugging-Face",
				"label": "IWAC-Hugging-Face",
				"type": "code"
			},
			{
				"url": "https://huggingface.co/datasets/fmadore/islam-west-africa-collection",
				"type": "data"
			}
		],
		"reviews": [
			{
				"text": "Anaïs Wion, \"Islam West Africa Collection: Dataset, Distant Reading, and Uses of AI for Discourse Analysis\", <em>The Digital Orientalist</em> 23 September 2025.",
				"url": "https://digitalorientalist.com/2025/09/23/islam-west-africa-collection-dataset-distant-reading-and-uses-of-ai-for-discourse-analysis/",
				"quote": "On the one hand, it is a database providing access to material that is difficult to access and highly specific, which can be reused by others and addressed with other research questions. But it is also an exemplary project that can inspire researchers to use the open access tools available to create their own platforms for analyzing and sharing their data. The care taken to comply with open access best practices is truly admirable."
			}
		],
		"skills": [
			"Omeka S",
			"Typesense",
			"ECharts",
			"MapLibre",
			"OpenRefine",
			"Metadata Standards",
			"Docker",
			"Linux",
			"Nginx",
			"Python",
			"Tesseract",
			"IIIF",
			"Linked Data",
			"Rclone",
			"spaCy",
			"pandas",
			"Hugging Face",
			"Embeddings",
			"Topic Modelling",
			"Web scraping"
		]
	},
	{
		"id": "live-translation",
		"title": "Live Translation and Subtitles",
		"years": "2026",
		"shortDescription": "A lightweight desktop app that captions a room as people speak, either translating into English or French or transcribing the spoken language. Built in Rust and Tauri for a bilingual workshop at STIAS in Stellenbosch.",
		"imageUrl": "/images/digital-humanities/live-translation.webp",
		"order": 2,
		"links": [
			{
				"url": "https://github.com/fmadore/Live-translation",
				"label": "Live-translation",
				"type": "code"
			},
			{
				"url": "https://fmadore.github.io/stias-dh-ai-workshop-2026/",
				"label": "STIAS workshop website"
			},
			{
				"url": "https://github.com/fmadore/stias-dh-ai-workshop-2026",
				"label": "stias-dh-ai-workshop-2026",
				"type": "code"
			}
		],
		"skills": [
			"Rust",
			"Tauri",
			"SvelteKit",
			"Svelte 5",
			"TypeScript",
			"WebSocket",
			"Real-time Audio",
			"Speech Recognition",
			"Machine Translation",
			"LLM",
			"Accessibility"
		],
		"seoKeywords": [
			"live translation",
			"live captions",
			"subtitles",
			"speech translation",
			"realtime speech recognition",
			"conference accessibility",
			"hybrid conference",
			"Tauri",
			"Rust",
			"Gemini",
			"OpenAI",
			"Mistral Voxtral",
			"digital humanities",
			"African studies"
		]
	},
	{
		"id": "omeka-s-docker",
		"title": "Omeka S Docker Template",
		"years": "2026",
		"shortDescription": "A reusable Docker template for deploying production-ready Omeka S digital archive installations with automatic setup, module management, and SSL support.",
		"imageUrl": "/images/digital-humanities/omeka-s-docker.webp",
		"order": 2,
		"links": [
			{
				"url": "https://github.com/AM-Digital-Research-Environment/omeka-s-docker",
				"label": "omeka-s-docker",
				"type": "code"
			}
		],
		"skills": [
			"Docker",
			"Nginx",
			"PHP",
			"MySQL",
			"Linux",
			"Omeka S",
			"IIIF",
			"Bash"
		],
		"seoKeywords": [
			"Omeka S",
			"Docker",
			"digital archives",
			"digital collections",
			"IIIF",
			"cultural heritage",
			"digital humanities",
			"containerization",
			"museum collections",
			"library technology"
		]
	},
	{
		"id": "remoboko",
		"title": "Remoboko Visualisations",
		"years": "2018-2024",
		"shortDescription": "Interactive visualisations for the Remoboko research group, including a points of interest map for my book and charts documenting the group's publications, activities, and collaborative network.",
		"imageUrl": "/images/digital-humanities/remoboko.webp",
		"order": 7,
		"links": [
			{
				"url": "https://fmadore.github.io/Remoboko/Book_DeGruyter/Maps/points_of_interest.html",
				"label": "Book: points of interest map"
			},
			{
				"url": "https://fmadore.github.io/Remoboko/Book_DeGruyter/Timeline/",
				"label": "Book: timeline"
			},
			{
				"url": "https://remoboko.hypotheses.org/visualisations"
			},
			{
				"url": "https://github.com/fmadore/Remoboko",
				"label": "Remoboko",
				"type": "code"
			}
		],
		"skills": [
			"Data Visualisation",
			"pandas",
			"Plotly",
			"Python",
			"Folium",
			"NLTK",
			"Leaflet",
			"D3.js"
		]
	},
	{
		"id": "zmo-ai-pipelines",
		"title": "ZMO AI Pipelines",
		"years": "2025",
		"shortDescription": "Google Colab notebooks that make AI accessible for researchers: transcribe audio/video, extract text from documents (OCR/HTR), and generate summaries—no installation required.",
		"imageUrl": "/images/digital-humanities/zmo-ai-pipelines.webp",
		"order": 5,
		"links": [
			{
				"url": "https://github.com/fmadore/zmo-ai-pipelines",
				"type": "code"
			}
		],
		"skills": [
			"Python",
			"Google Colab",
			"NLP",
			"OCR",
			"HTR",
			"LLM",
			"Prompt Engineering"
		],
		"seoKeywords": [
			"AI tools",
			"transcription",
			"OCR",
			"HTR",
			"handwriting recognition",
			"Google Gemini",
			"qualitative research",
			"digital humanities",
			"text analysis",
			"audio transcription",
			"Google Colab",
			"multilingual AI"
		]
	},
	{
		"id": "zmo-visualisations",
		"title": "ZMO Visualisations",
		"years": "2025",
		"shortDescription": "Two static web apps built using data scraped monthly from the ZMO website: a word cloud showing the topics covered by each research unit, and a dashboard providing an overview of the institute's complete publication history since 1994.",
		"imageUrl": "/images/digital-humanities/zmo-visualisations.webp",
		"order": 6,
		"links": [
			{
				"url": "https://zmo-berlin.github.io/visualisations/en/"
			},
			{
				"url": "https://zmo-berlin.github.io/visualisations/units_wordcloud/en/",
				"label": "Word cloud"
			},
			{
				"url": "https://zmo-berlin.github.io/visualisations/publications_dashboard/en/",
				"label": "Publications dashboard"
			},
			{
				"url": "https://github.com/ZMO-Berlin/visualisations",
				"label": "ZMO-Berlin/visualisations",
				"type": "code"
			}
		],
		"skills": [
			"Python",
			"Web scraping",
			"D3.js",
			"Data Visualisation",
			"Network graphs",
			"JSON",
			"GitHub Actions"
		],
		"seoKeywords": [
			"ZMO",
			"Leibniz-Zentrum Moderner Orient",
			"data visualisation",
			"word cloud",
			"publications dashboard",
			"bibliometrics",
			"co-authorship network",
			"web scraping",
			"D3",
			"digital humanities"
		]
	}
];
