/**
 * Auto-generated index of publication text analyses.
 * Generated by scripts/analyze-publications.py
 */

import type { PublicationTextAnalysis } from '$lib/types';

import { analysis as islamBurkinaFasoCollection2021 } from './islam-burkina-faso-collection-2021';

export const publicationAnalyses: Record<string, PublicationTextAnalysis> = {
	'islam-burkina-faso-collection-2021': islamBurkinaFasoCollection2021
};

export function getAnalysis(id: string): PublicationTextAnalysis | undefined {
	return publicationAnalyses[id];
}

export function hasAnalysis(id: string): boolean {
	return id in publicationAnalyses;
}

export function getAnalyzedIds(): string[] {
	return Object.keys(publicationAnalyses);
}
