/**
 * Text analysis for: madore-2024-launch-iwac
 * Auto-generated by scripts/analyze-publications.py
 */

import type { PublicationTextAnalysis } from '$lib/types';

export const analysis: PublicationTextAnalysis = {
	publicationId: 'madore-2024-launch-iwac',
	language: 'en',
	wordCount: 205,
	uniqueWords: 149,
	source: 'full-text',
	analyzedAt: '2026-02-12',
	frequencies: [
		{ word: 'zmo', count: 5, lemma: 'zmo', pos: 'propn' },
		{ word: 'west', count: 4, lemma: 'west', pos: 'propn' },
		{ word: 'mict', count: 4, lemma: 'mict', pos: 'propn' },
		{ word: 'madore', count: 4, lemma: 'madore', pos: 'propn' },
		{ word: 'iwac', count: 4, lemma: 'iwac', pos: 'propn' },
		{ word: 'project', count: 4, lemma: 'project', pos: 'noun' },
		{ word: 'launch', count: 3, lemma: 'launch', pos: 'verb' },
		{ word: 'islam', count: 3, lemma: 'islam', pos: 'propn' },
		{ word: 'africa', count: 3, lemma: 'africa', pos: 'propn' },
		{ word: 'berlin', count: 3, lemma: 'berlin', pos: 'propn' },
		{ word: 'frédérick', count: 3, lemma: 'frédérick', pos: 'propn' },
		{ word: 'document', count: 3, lemma: 'document', pos: 'noun' },
		{ word: 'nobili', count: 3, lemma: 'nobili', pos: 'propn' },
		{ word: 'collection', count: 2, lemma: 'collection', pos: 'propn' },
		{ word: 'november', count: 2, lemma: 'november', pos: 'propn' },
		{ word: 'medium', count: 2, lemma: 'medium', pos: 'noun' },
		{ word: 'database', count: 2, lemma: 'database', pos: 'noun' },
		{ word: 'recording', count: 2, lemma: 'recording', pos: 'noun' },
		{ word: 'côte', count: 2, lemma: 'côte', pos: 'propn' },
		{ word: 'site', count: 2, lemma: 'site', pos: 'noun' },
		{ word: 'african', count: 2, lemma: 'african', pos: 'adj' },
		{ word: 'klaas', count: 2, lemma: 'klaas', pos: 'propn' },
		{ word: 'glenewinkel', count: 2, lemma: 'glenewinkel', pos: 'propn' },
		{ word: 'ulrike', count: 2, lemma: 'ulrike', pos: 'propn' },
		{ word: 'freitag', count: 2, lemma: 'freitag', pos: 'propn' },
		{ word: 'mauro', count: 2, lemma: 'mauro', pos: 'propn' },
		{ word: 'university', count: 2, lemma: 'university', pos: 'propn' },
		{ word: 'illinois', count: 2, lemma: 'illinois', pos: 'propn' },
		{ word: 'urbana', count: 2, lemma: 'urbana', pos: 'propn' },
		{ word: 'champaign', count: 2, lemma: 'champaign', pos: 'propn' },
		{ word: 'binate', count: 2, lemma: 'binate', pos: 'propn' },
		{ word: 'vincent', count: 2, lemma: 'vincent', pos: 'propn' },
		{ word: 'favier', count: 2, lemma: 'favier', pos: 'propn' },
		{ word: 'kai', count: 2, lemma: 'kai', pos: 'propn' },
		{ word: 'kresse', count: 2, lemma: 'kresse', pos: 'propn' },
		{ word: 'future', count: 2, lemma: 'future', pos: 'adj' }
	],
	bigrams: [
		{ ngram: 'west africa', words: ["west", "africa"], count: 3 },
		{ ngram: 'islam west', words: ["islam", "west"], count: 2 },
		{ ngram: 'africa collection', words: ["africa", "collection"], count: 2 },
		{ ngram: 'klaas glenewinkel', words: ["klaas", "glenewinkel"], count: 2 },
		{ ngram: 'ulrike freitag', words: ["ulrike", "freitag"], count: 2 },
		{ ngram: 'mauro nobili', words: ["mauro", "nobili"], count: 2 },
		{ ngram: 'vincent favier', words: ["vincent", "favier"], count: 2 },
		{ ngram: 'kai kresse', words: ["kai", "kresse"], count: 2 }
	]
};
