/**
 * Text analysis for: madore-2025-perspectives-in-motion
 * Auto-generated by scripts/analyze-publications.py
 */

import type { PublicationTextAnalysis } from '$lib/types';

export const analysis: PublicationTextAnalysis = {
	publicationId: 'madore-2025-perspectives-in-motion',
	language: 'en',
	wordCount: 207,
	uniqueWords: 162,
	source: 'full-text',
	analyzedAt: '2026-02-05',
	frequencies: [
		{ word: 'discussion', count: 4, lemma: 'discussion', pos: 'noun' },
		{ word: 'workshop', count: 3, lemma: 'workshop', pos: 'noun' },
		{ word: 'zmo', count: 3, lemma: 'zmo', pos: 'propn' },
		{ word: 'intellectual', count: 3, lemma: 'intellectual', pos: 'adj' },
		{ word: 'panel', count: 3, lemma: 'panel', pos: 'noun' },
		{ word: 'african', count: 3, lemma: 'african', pos: 'adj' },
		{ word: 'university', count: 3, lemma: 'university', pos: 'propn' },
		{ word: 'identity', count: 3, lemma: 'identity', pos: 'noun' },
		{ word: 'term', count: 3, lemma: 'term', pos: 'noun' },
		{ word: 'global', count: 2, lemma: 'global', pos: 'propn' },
		{ word: 'south', count: 2, lemma: 'south', pos: 'propn' },
		{ word: 'frédérick', count: 2, lemma: 'frédérick', pos: 'propn' },
		{ word: 'madore', count: 2, lemma: 'madore', pos: 'propn' },
		{ word: 'organise', count: 2, lemma: 'organise', pos: 'verb' },
		{ word: 'religion', count: 2, lemma: 'religion', pos: 'propn' },
		{ word: 'explore', count: 2, lemma: 'explore', pos: 'verb' },
		{ word: 'western', count: 2, lemma: 'western', pos: 'adj' },
		{ word: 'challenge', count: 2, lemma: 'challenge', pos: 'verb' },
		{ word: 'enrich', count: 2, lemma: 'enrich', pos: 'verb' },
		{ word: 'decolonial', count: 2, lemma: 'decolonial', pos: 'adj' },
		{ word: 'knowledge', count: 2, lemma: 'knowledge', pos: 'noun' },
		{ word: 'production', count: 2, lemma: 'production', pos: 'noun' },
		{ word: 'roy', count: 2, lemma: 'roy', pos: 'propn' },
		{ word: 'kresse', count: 2, lemma: 'kresse', pos: 'propn' },
		{ word: 'sounaye', count: 2, lemma: 'sounaye', pos: 'propn' },
		{ word: 'context', count: 2, lemma: 'context', pos: 'noun' },
		{ word: 'framework', count: 2, lemma: 'framework', pos: 'noun' },
		{ word: 'maseno', count: 2, lemma: 'maseno', pos: 'propn' },
		{ word: 'muslim', count: 2, lemma: 'muslim', pos: 'adj' },
		{ word: 'analyse', count: 2, lemma: 'analyse', pos: 'verb' },
		{ word: 'islamic', count: 2, lemma: 'islamic', pos: 'adj' },
		{ word: 'critique', count: 2, lemma: 'critique', pos: 'verb' },
		{ word: 'day', count: 2, lemma: 'day', pos: 'noun' },
		{ word: 'concept', count: 2, lemma: 'concept', pos: 'noun' },
		{ word: 'swahili', count: 2, lemma: 'swahili', pos: 'propn' }
	],
	bigrams: [
		{ ngram: 'panel discussion', words: ["panel", "discussion"], count: 3 },
		{ ngram: 'global south', words: ["global", "south"], count: 2 },
		{ ngram: 'knowledge production', words: ["knowledge", "production"], count: 2 },
		{ ngram: 'swahili term', words: ["swahili", "term"], count: 2 }
	]
};
