// AUTO-GENERATED by scripts/generate-summaries.mjs — DO NOT EDIT.
// Regenerate with `npm run gen:summaries` (runs automatically via the prebuild hook).
/* eslint-disable */
import type { CvPublication } from '$lib/types/publication';
export const cvPublications: CvPublication[] = [
	{
		"id": "acteurs-religieux-numerique",
		"type": "special-issue",
		"title": "Les acteurs religieux africains à l'ère du numérique",
		"authors": [
			"Pamela Millet-Mouity",
			"Frédérick Madore"
		],
		"editors": "Pamela Millet-Mouity, Frédérick Madore",
		"date": "2017",
		"dateISO": "2017",
		"year": 2017,
		"journal": "Émulations",
		"publisher": "Presses universitaires de Louvain",
		"issue": "24",
		"url": "https://doi.org/10.14428/emulations.024",
		"doi": "10.14428/emulations.024"
	},
	{
		"id": "ambition-federatrice-faitieres-islamiques-2026",
		"type": "chapter",
		"title": "L'ambition fédératrice à l'épreuve de la diversité : étude comparative des faîtières islamiques au Burkina Faso, Togo, Bénin et Côte d'Ivoire",
		"authors": [
			"Frédérick Madore"
		],
		"date": "Forthcoming",
		"dateISO": "2026",
		"year": 2026,
		"book": "Vie associative et pratiques organisationnelles en Afrique de l'Ouest : saisir les associations par leur architecture bureaucratique",
		"editors": "André Chappatte, Bourahima Diomandé",
		"placeOfPublication": "Paris",
		"publisher": "Africae"
	},
	{
		"id": "beninese-imam-election-2022",
		"type": "article",
		"title": "A Beninese Imam's Controversial 2019 Election Campaign: Muslim Leadership and Political Engagement in a Minority Context",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2022",
		"dateISO": "2022-06-06",
		"year": 2022,
		"journal": "Islamic Africa",
		"publisher": "Brill",
		"volume": "13",
		"issue": "1",
		"pages": "1-26",
		"doi": "10.1163/21540993-01202004",
		"url": "https://doi.org/10.1163/21540993-01202004"
	},
	{
		"id": "charting-new-territory-digital-humanities-ki-african-studies-2026",
		"type": "blogpost",
		"title": "Charting New Territory: Digital Humanities und Künstliche Intelligenz in den African Studies",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren"
		],
		"date": "2026",
		"dateISO": "2026-03-31",
		"year": 2026,
		"publisher": "Digital History Bielefeld",
		"doi": "10.58079/15z9p"
	},
	{
		"id": "communaute-musulmane-burkina-faso-2014",
		"type": "encyclopedia",
		"title": "Communauté Musulmane du Burkina Faso",
		"authors": [
			"Frédérick Madore",
			"Muriel Gomez-Perez"
		],
		"date": "2014",
		"dateISO": "2014-09-01",
		"year": 2014,
		"publisher": "Brill",
		"encyclopediaTitle": "The Encyclopaedia of Islam, Three",
		"editors": "Kate Fleet, Gudrun Krämer, Denis Matringe, John Nawas, Everett Rowson",
		"placeOfPublication": "Leiden",
		"pages": "66-67",
		"doi": "10.1163/1573-3912_ei3_com_27698",
		"url": "https://doi.org/10.1163/1573-3912_ei3_com_27698"
	},
	{
		"id": "exister-contexte-autoritaire-lome-2023",
		"type": "chapter",
		"title": "Exister en contexte autoritaire : les associations étudiantes chrétiennes et islamiques à l'Université de Lomé sous Gnassingbé Eyadéma, 1970–2005",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2023",
		"dateISO": "2023",
		"year": 2023,
		"book": "Religiosity on University Campuses in Africa: Trends and Experiences",
		"editors": "Abdoulaye Sounaye, Frédérick Madore",
		"placeOfPublication": "Berlin",
		"publisher": "LIT Verlag",
		"pages": "51-83",
		"doi": "10.58144/20241107-000",
		"url": "https://doi.org/10.58144/20241107-000"
	},
	{
		"id": "for-whom-for-what-purpose-dh-ai-african-studies-2026",
		"type": "working-paper",
		"title": "For Whom and For What Purpose? A Position Paper on Digital Humanities and AI in African Studies",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren",
			"Agata Błoch",
			"Albrecht Hofheinz",
			"Ashleigh Harris",
			"Augustin Ndione",
			"Britta Frede",
			"Cassandra Mark-Thiesen",
			"Duncan Money",
			"Emmanuel Ngue Um",
			"Érika Melek Delgado",
			"Fallou Ngom",
			"Fu’ad Lawal",
			"Irene Mwendwa",
			"James Yékú",
			"Janeth David Nzenga",
			"Johannes Sibeko",
			"Karen Byera Ijumba",
			"Kọ́lá Túbọ̀sún",
			"Leah Junck",
			"Menno van Zaanen",
			"Nuraddin Aman",
			"Oumou Sidibé",
			"Susan Elizabeth Gagliardi",
			"Thompson Gyedu Kwarkye"
		],
		"date": "2026",
		"dateISO": "2026-09-09",
		"year": 2026,
		"series": "ZMO Programmatic Texts",
		"issue": "16",
		"publisher": "Leibniz-Zentrum Moderner Orient",
		"placeOfPublication": "Berlin",
		"doi": "10.58144/20260827-000",
		"url": "https://doi.org/10.58144/20260827-000"
	},
	{
		"id": "francophone-muslim-intellectuals-burkina-faso-2020",
		"type": "article",
		"title": "Francophone Muslim intellectuals, Islamic associational life and religious authority in Burkina Faso",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2020",
		"dateISO": "2020-05-21",
		"year": 2020,
		"journal": "Africa",
		"publisher": "Cambridge University Press",
		"volume": "90",
		"issue": "3",
		"pages": "625-646",
		"doi": "10.1017/S0001972020000108",
		"url": "https://doi.org/10.1017/S0001972020000108"
	},
	{
		"id": "good-muslim-bad-muslim-togo-2021",
		"type": "article",
		"title": "'Good Muslim, bad Muslim' in Togo: religious minority identity construction amid a sociopolitical crisis (2017-2018)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2021",
		"dateISO": "2021-06-07",
		"year": 2021,
		"journal": "The Journal of Modern African Studies",
		"publisher": "Cambridge University Press",
		"volume": "59",
		"issue": "2",
		"pages": "197-217",
		"doi": "10.1017/S0022278X21000094",
		"url": "https://doi.org/10.1017/S0022278X21000094"
	},
	{
		"id": "hackett-interview-digital-media-2017",
		"type": "article",
		"title": "Interview with Rosalind I. J. Hackett on Religion and Digital Media Trends in Africa",
		"authors": [
			"Rosalind I. J. Hackett",
			"Frédérick Madore",
			"Pamela Millet-Mouity"
		],
		"date": "2017",
		"dateISO": "2017",
		"year": 2017,
		"journal": "Émulations",
		"publisher": "Presses universitaires de Louvain",
		"issue": "24",
		"pages": "125-133",
		"doi": "10.14428/emulations.024.008",
		"url": "https://doi.org/10.14428/emulations.024.008"
	},
	{
		"id": "hadj-cote-divoire-2018",
		"type": "article",
		"title": "L'organisation du hadj en Côte d'Ivoire: entre facteur de cohésion et source de rivalités au sein de la communauté musulmane (1993-2010)",
		"authors": [
			"Frédérick Madore",
			"Yssoufou Traoré"
		],
		"date": "2018",
		"dateISO": "2018",
		"year": 2018,
		"journal": "Cahiers d'études africaines",
		"publisher": "Éditions de l’École des Hautes Études en Sciences Sociales",
		"issue": "229",
		"pages": "179-208",
		"doi": "10.4000/etudesafricaines.21880",
		"url": "https://doi.org/10.4000/etudesafricaines.21880"
	},
	{
		"id": "imams-islamic-preachers-ouagadougou-2020",
		"type": "chapter",
		"title": "Imams, Islamic Preachers, and Public Space in Ouagadougou (Burkina Faso) since the 1990s: Toward New Intergenerational Relationships and a Muslim Public Sphere",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2020",
		"dateISO": "2020",
		"year": 2020,
		"book": "Perspectives on the Religious Landscape in Africa",
		"editors": "Lady Jane Acquah, Toyin Falola",
		"placeOfPublication": "Durham, NC",
		"publisher": "Carolina Academic Press",
		"pages": "183-213",
		"url": "https://cap-press.com/books/isbn/9781531007317/Perspectives-on-Religious-Landscape-in-Africa"
	},
	{
		"id": "introduction-religiosity-university-campuses-2023",
		"type": "chapter",
		"title": "Introduction: Religiosity on University Campuses in Africa",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore"
		],
		"date": "2023",
		"dateISO": "2023",
		"year": 2023,
		"book": "Religiosity on University Campuses in Africa: Trends and Experiences",
		"editors": "Abdoulaye Sounaye, Frédérick Madore",
		"placeOfPublication": "Berlin",
		"publisher": "LIT Verlag",
		"pages": "3-21",
		"doi": "10.58144/20241107-000",
		"url": "https://doi.org/10.58144/20241107-000"
	},
	{
		"id": "islam-burkina-faso-collection-2021",
		"type": "article",
		"title": "La Collection Islam Burkina Faso : promesses et défis des humanités numériques",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2021",
		"dateISO": "2021-12-15",
		"year": 2021,
		"journal": "Revue d'Histoire Contemporaine de l'Afrique",
		"publisher": "University of Geneva",
		"doi": "10.51185/journals/rhca.2021.e610",
		"url": "https://doi.org/10.51185/journals/rhca.2021.e610"
	},
	{
		"id": "islam-ivoirien-burkinabe-numerique-2016",
		"type": "article",
		"title": "L'islam ivoirien et burkinabé à l'ère du numérique 2.0",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2016",
		"dateISO": "2016",
		"year": 2016,
		"journal": "Journal des anthropologues",
		"publisher": "Association Française des Anthropologues",
		"issue": "146-147",
		"pages": "151-178",
		"doi": "10.4000/jda.6525",
		"url": "https://doi.org/10.4000/jda.6525"
	},
	{
		"id": "islam-medias-senat-burkina-faso-2016",
		"type": "article",
		"title": "Islam, médias, mise en place du Sénat et article 37 de la Constitution: changement de paradigme au Burkina Faso (1991–2014)?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2016",
		"dateISO": "2016-03-10",
		"year": 2016,
		"journal": "Canadian Journal of African Studies / Revue canadienne des études africaines",
		"publisher": "Taylor & Francis",
		"volume": "50",
		"issue": "1",
		"pages": "7-27",
		"doi": "10.1080/00083968.2015.1101008",
		"url": "https://doi.org/10.1080/00083968.2015.1101008"
	},
	{
		"id": "islam-university-campuses-cote-divoire-2023",
		"type": "chapter",
		"title": "Islam on University Campuses in Côte d'Ivoire since the 1970s: Muslim Intellectuals and Francophone Salafism",
		"authors": [
			"Frédérick Madore",
			"Issouf Binaté"
		],
		"date": "2023",
		"dateISO": "2023",
		"year": 2023,
		"book": "Religiosity on University Campuses in Africa: Trends and Experiences",
		"editors": "Abdoulaye Sounaye, Frédérick Madore",
		"placeOfPublication": "Berlin",
		"publisher": "LIT Verlag",
		"pages": "273-307",
		"doi": "10.58144/20241107-000",
		"url": "https://doi.org/10.58144/20241107-000"
	},
	{
		"id": "leaders-muslim-ngos-burkina-faso-2016",
		"type": "chapter",
		"title": "Leaders of National and Transnational Muslim NGOs in Burkina Faso: Diverse Forms and Experiences of Islamic Civic Engagement",
		"authors": [
			"Kathéry Couillard",
			"Frédérick Madore",
			"Muriel Gomez-Perez"
		],
		"date": "2016",
		"dateISO": "2016",
		"year": 2016,
		"book": "Faith and Charity: Religion and Humanitarian Assistance in West Africa",
		"editors": "Marie Nathalie LeBlanc, Louis Audet Gosselin",
		"placeOfPublication": "London",
		"publisher": "Pluto Press",
		"pages": "105-123",
		"doi": "10.2307/j.ctt1gk0810.11",
		"url": "https://doi.org/10.2307/j.ctt1gk0810.11"
	},
	{
		"id": "lutte-terrorisme-salafisme-benin-togo-2022",
		"type": "report",
		"title": "Lutte contre le terrorisme et sécuritisation du salafisme au Bénin et au Togo: instrumentalisations diverses d'une « menace étrangère »",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2022",
		"dateISO": "2022-10",
		"year": 2022,
		"publisher": "Bulletin FrancoPaix",
		"volume": "7",
		"issue": "8",
		"pages": "2-7",
		"url": "https://dandurand.uqam.ca/publication/lutte-contre-le-terrorisme-et-securitisation-du-salafisme-au-benin-et-au-togo-instrumentalisations-diverses-dune-menace-etrangere/"
	},
	{
		"id": "madore-2024-launch-iwac",
		"type": "bulletin-article",
		"title": "Launch Islam West Africa Collection, 9 November 2023, MiCT, Berlin/Online",
		"authors": [
			"Frédérick Madore"
		],
		"date": "April 2024",
		"dateISO": "2024-04",
		"year": 2024,
		"journal": "ZMO Bulletin",
		"issue": "44",
		"pages": "9",
		"doi": "10.58144/20240415-000",
		"url": "https://doi.org/10.58144/20240415-000"
	},
	{
		"id": "madore-2025-perspectives-in-motion",
		"type": "bulletin-article",
		"title": "Perspectives in Motion: Conceptual Fields from the Global South, Workshop, 2-3 December 2024, ZMO",
		"authors": [
			"Frédérick Madore"
		],
		"date": "April 2025",
		"dateISO": "2025-04",
		"year": 2025,
		"journal": "ZMO Bulletin",
		"issue": "46",
		"pages": "7",
		"doi": "10.58144/20250401-000",
		"url": "https://doi.org/10.58144/20250401-000"
	},
	{
		"id": "madore-2026-conversation-coauthorship-dh-ai",
		"type": "bulletin-article",
		"title": "From Conversation to Co-authorship: A Workshop on Digital Humanities and AI in African Studies, 18–20 February 2026, Herrenhausen, Hanover",
		"authors": [
			"Frédérick Madore"
		],
		"date": "May 2026",
		"dateISO": "2026-05",
		"year": 2026,
		"journal": "ZMO Bulletin",
		"issue": "48",
		"pages": "10",
		"doi": "10.58144/20260430-000"
	},
	{
		"id": "madore-2026-decentering-knowledge",
		"type": "bulletin-article",
		"title": "Decentering Knowledge: Concepts, Conceptualizations, Translations, 13–14 October 2025, ZMO",
		"authors": [
			"Frédérick Madore"
		],
		"date": "May 2026",
		"dateISO": "2026-05",
		"year": 2026,
		"journal": "ZMO Bulletin",
		"issue": "48",
		"pages": "6-7",
		"doi": "10.58144/20260430-000",
		"url": ""
	},
	{
		"id": "madore-2026-iwac-private-database-public-resource",
		"type": "bulletin-article",
		"title": "From Private Database to Public Resource to a Testing Ground for AI Methods: The Islam West Africa Collection (IWAC)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2026",
		"dateISO": "2026",
		"year": 2026,
		"journal": "Shared World - People, Faiths, Ideas, Practices: New Directions in Research 2023-2025, Jahrbuch",
		"publisher": "Leibniz-Zentrum Moderner Orient",
		"pages": "113-120",
		"doi": "10.58144/20260302-000"
	},
	{
		"id": "madore-islam-politique-ouagadougou-2013",
		"type": "masters-thesis",
		"title": "Islam, politique et sphère publique à Ouagadougou (Burkina Faso) : différentes cohortes d'imams et de prêcheurs entre visibilité nouvelle et reconfiguration des rapports intergénérationnels (1960-2012)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2013",
		"dateISO": "2013",
		"year": 2013,
		"placeOfPublication": "Quebec City",
		"url": "https://corpus.ulaval.ca/jspui/handle/20.500.11794/24012"
	},
	{
		"id": "muslim-feminist-media-cote-divoire-2020",
		"type": "article",
		"title": "Muslim Feminist, Media Sensation, and Religious Entrepreneur: Aminata Kane Koné as a Figure of Success in Côte d'Ivoire",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2020",
		"dateISO": "2020",
		"year": 2020,
		"journal": "Africa Today",
		"publisher": "Indiana University Press",
		"volume": "67",
		"issue": "2-3",
		"pages": "17-38",
		"doi": "10.2979/africatoday.67.2_3.02",
		"url": "https://doi.org/10.2979/africatoday.67.2_3.02"
	},
	{
		"id": "muslim-minorities-africa-1",
		"type": "special-issue",
		"title": "Muslim Minorities in Africa, Part 1",
		"authors": [
			"Frédérick Madore",
			"Dorothea Schulz"
		],
		"editors": "Frédérick Madore, Dorothea Schulz",
		"date": "2021",
		"dateISO": "2021-07",
		"year": 2021,
		"journal": "Islamic Africa",
		"publisher": "Brill",
		"volume": "12",
		"issue": "2",
		"url": "https://brill.com/view/journals/iafr/12/2/iafr.12.issue-2.xml"
	},
	{
		"id": "muslim-minorities-africa-2",
		"type": "special-issue",
		"title": "Muslim Minorities in Africa, Part 2",
		"authors": [
			"Frédérick Madore",
			"Dorothea Schulz"
		],
		"editors": "Frédérick Madore, Dorothea Schulz",
		"date": "2022",
		"dateISO": "2022-01",
		"year": 2022,
		"journal": "Islamic Africa",
		"publisher": "Brill",
		"volume": "13",
		"issue": "1",
		"url": "https://brill.com/view/journals/iafr/13/1/iafr.13.issue-1.xml"
	},
	{
		"id": "muslim-women-burkina-faso-2016",
		"type": "article",
		"title": "Muslim Women in Burkina Faso since the 1970s: Toward Recognition as Figures of Religious Authority?",
		"authors": [
			"Frédérick Madore",
			"Muriel Gomez-Perez"
		],
		"date": "2016",
		"dateISO": "2016-11-02",
		"year": 2016,
		"journal": "Islamic Africa",
		"publisher": "Brill",
		"volume": "7",
		"issue": "2",
		"pages": "185-209",
		"doi": "10.1163/21540993-00702001",
		"url": "https://doi.org/10.1163/21540993-00702001"
	},
	{
		"id": "plan-brouillon-structurer-idees-2021",
		"type": "chapter",
		"title": "Du plan au brouillon : l'essentiel pour structurer ses idées et éviter le syndrome de la page blanche",
		"authors": [
			"Frédérick Madore",
			"Andrée-Ann Brassard"
		],
		"date": "2021",
		"dateISO": "2021",
		"year": 2021,
		"book": "Guide décolonisé et pluriversel de formation à la recherche en sciences sociales et humaines",
		"editors": "Florence Piron, Élisabeth Arsenault",
		"placeOfPublication": "Québec",
		"publisher": "Éditions science et bien commun",
		"url": "https://scienceetbiencommun.pressbooks.pub/projetthese/chapter/faire-une-table-des-matieres/"
	},
	{
		"id": "precheurs-musulmans-burkina-faso-2013",
		"type": "article",
		"title": "Prêcheurs(ses) musulmans(es) et stratégies de communication au Burkina Faso depuis 1990. Des processus différentiés de conversion interne",
		"authors": [
			"Muriel Gomez-Perez",
			"Frédérick Madore"
		],
		"date": "2013",
		"dateISO": "2013",
		"year": 2013,
		"journal": "Théologiques",
		"publisher": "Institut d’études religieuses de l’Université de Montréal",
		"volume": "21",
		"issue": "2",
		"pages": "121-157",
		"doi": "10.7202/1028465ar",
		"url": "https://doi.org/10.7202/1028465ar"
	},
	{
		"id": "religieux-internet-ntic-burkina-faso-2019",
		"type": "chapter",
		"title": "Le religieux sur Internet et dans les NTIC au Burkina Faso",
		"authors": [
			"Frédérick Madore",
			"Louis Audet Gosselin"
		],
		"date": "2019",
		"dateISO": "2019-06",
		"year": 2019,
		"book": "Rencontres religieuses et dynamiques sociales au Burkina Faso",
		"editors": "Alice Degorce, Ludovic O. Kibora, Katrin Langewiesche",
		"placeOfPublication": "Dakar",
		"publisher": "Amalion",
		"pages": "269-296",
		"url": "https://www.amalion.net/catalogue/rencontres-religieuses-et-dynamiques-sociales-au-burkina-faso/"
	},
	{
		"id": "religion-internet-burkina-faso-2024",
		"type": "chapter",
		"title": "Religion on the Internet and New Information and Communication Technologies in Burkina Faso",
		"authors": [
			"Frédérick Madore",
			"Louis Audet Gosselin"
		],
		"date": "2024",
		"dateISO": "2024",
		"year": 2024,
		"book": "Religious Encounters and Social Dynamics in Burkina Faso",
		"editors": "Alice Degorce, Ludovic O. Kibora, Katrin Langewiesche",
		"placeOfPublication": "Dakar",
		"publisher": "Amalion",
		"pages": "263-288",
		"url": "https://www.amalion.net/catalogue/religious-encounters-and-social-dynamics-in-burkina-faso/"
	},
	{
		"id": "religions-numeriques-afrique-2018",
		"type": "blogpost",
		"title": "Religions numériques en Afrique",
		"authors": [
			"Vincent Hiribarren",
			"Pamela Millet-Mouity",
			"Frédérick Madore"
		],
		"date": "2018",
		"dateISO": "2018-09-19",
		"year": 2018,
		"publisher": "Africa4. Regards croisés sur l'Afrique",
		"url": "https://www.liberation.fr/debats/2018/09/19/religions-numeriques-en-afrique_1816717/"
	},
	{
		"id": "religiosity-university-campuses",
		"type": "book",
		"title": "Religiosity on University Campuses in Africa: Trends and Experiences",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore"
		],
		"editors": "Abdoulaye Sounaye, Frédérick Madore",
		"date": "2023",
		"dateISO": "2023-08-29",
		"year": 2023,
		"placeOfPublication": "Berlin",
		"publisher": "LIT Verlag",
		"series": "Afrikanische Studien/African Studies 64",
		"doi": "10.58144/20241107-000",
		"url": "https://doi.org/10.58144/20241107-000",
		"isEditedVolume": true
	},
	{
		"id": "religious-activism-campuses",
		"type": "book",
		"title": "Religious Activism on Campuses in Togo and Benin: Christian and Muslim Students Navigating Authoritarianism and Laïcité, 1970–2023",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2025",
		"dateISO": "2025-03-31",
		"year": 2025,
		"placeOfPublication": "Berlin",
		"publisher": "De Gruyter",
		"series": "ZMO-Studien 48",
		"doi": "10.1515/9783111428895",
		"url": "https://doi.org/10.1515/9783111428895",
		"reviewedBy": [
			{
				"author": "Macodou Fall",
				"year": 2025,
				"title": "Frédérick Madore, Religious Activism on Campuses in Togo and Benin: Christian and Muslim Students Navigating Authoritarianism and Laïcité, 1970–2023. Berlin: De Gruyter, 2023. 308 Pages. ISBN: 978-3-11-142790-4.",
				"journal": "Research Africa Reviews",
				"volume": "9",
				"issue": "3",
				"pages": "15-17",
				"url": "https://researchafrica.duke.edu/sites/default/files/-5-7-Religious-Activism-on-Campuses-in-Togo-and-Benin-Issue3-2025.pdf",
				"excerpt": "These nuances, however, do not detract from the book's contribution, which is considerable; this is due to its comprehensive analysis of the history and development of faith-based movements in Togo and Benin from 1970 to 2023. The book offers a valuable resource for scholars seeking to understand the complex interplay between faith, activism, and adaptation in Francophone Africa."
			},
			{
				"author": "K. D. Thompson",
				"year": 2025,
				"title": "Religious Activism on Campuses in Togo and Benin: Christian and Muslim Students Navigating Authoritarianism and Laïcité, 1970–2023 by Frédérick Madore. Berlin: De Gruyter, 2025. Pp. xiii + 259. €79.99 (Hbk).",
				"journal": "The Journal of Modern African Studies",
				"volume": "63",
				"issue": "4",
				"pages": "298-300",
				"url": "https://doi.org/10.1017/S0022278X25101195",
				"excerpt": "Madore has produced an important work that documents previously neglected histories and demonstrates the significance of faith-based associations in shaping student activism, religious dynamics, and elite formation in West Africa. The book will be valuable for scholars of religion and higher education in Africa, students of social movements and those interested in how religious identity intersects with political and economic change."
			},
			{
				"author": "Douglas J. Falen",
				"year": 2026,
				"title": "Frédérick Madore. Religious Activism on Campuses in Togo and Benin: Christian and Muslim Students Navigating Authoritarianism and Laïcité, 1970–2023. De Gruyter Brill, 2025. 281 Pp. $98.99. Hardcover. ISBN: 9783111427904",
				"journal": "African Studies Review",
				"volume": "69",
				"issue": "1",
				"url": "https://doi.org/10.1017/asr.2025.10172",
				"excerpt": "Madore's account demonstrates an admirable respect for the current and former members he interviewed and a deep knowledge of the complex relationships between student religious associations, politico-economic conditions, and the challenges of Togolese and Beninese students."
			},
			{
				"author": "Matthew Swagler",
				"year": 2026,
				"title": "Frédérick Madore. Religious Activism on Campuses in Togo and Benin: Christian and Muslim Students Navigating Authoritarianism and Laïcité, 1970–2023",
				"journal": "The American Historical Review",
				"volume": "131",
				"issue": "3",
				"pages": "1417-18",
				"url": "https://doi.org/10.1093/ahr/rhag129",
				"excerpt": "Ultimately, the book’s sweeping account of religious associations on West African campuses stands as an important resource for historians of contemporary religion, higher education, and politics."
			}
		]
	},
	{
		"id": "religious-actors-digital-era-2017",
		"type": "article",
		"title": "Pour de nouvelles études sur les acteurs religieux africains à l'ère du numérique",
		"authors": [
			"Pamela Millet-Mouity",
			"Frédérick Madore"
		],
		"date": "2017",
		"dateISO": "2017",
		"year": 2017,
		"journal": "Émulations",
		"publisher": "Presses universitaires de Louvain",
		"issue": "24",
		"pages": "11-22",
		"doi": "10.14428/emulations.024.001",
		"url": "https://doi.org/10.14428/emulations.024.001"
	},
	{
		"id": "repenser-categorisation-religieuse-benin-2026",
		"type": "chapter",
		"title": "Repenser la catégorisation religieuse à partir du Bénin, terre du Vodun",
		"authors": [
			"Frédérick Madore",
			"Codjo Fiacre Anato"
		],
		"date": "2026",
		"dateISO": "2026-04-02",
		"year": 2026,
		"book": "L'Afrique des religions à l'épreuve des chiffres et des catégorisations",
		"editors": "Marc-Antoine Pérouse de Montclos, Nathalie Bernard-Maugiron, Aurélien Dasré",
		"placeOfPublication": "Paris",
		"publisher": "Maisonneuve & Larose-Hémisphères éditions",
		"pages": "25-48",
		"url": "https://www.hemisphereseditions.com/l-afrique-des-religions"
	},
	{
		"id": "rivalites-collaborations-islamiques-cote-ivoire-burkina-faso-2018",
		"type": "phd-dissertation",
		"title": "Rivalités et collaborations entre ainés et cadets sociaux dans les milieux associatifs islamiques en Côte d'Ivoire et au Burkina Faso (1970-2017)",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2018",
		"dateISO": "2018",
		"year": 2018,
		"placeOfPublication": "Quebec City",
		"url": "http://hdl.handle.net/20.500.11794/33246"
	},
	{
		"id": "salafism-cote-divoire-2016",
		"type": "article",
		"title": "The New Vitality of Salafism in Côte d'Ivoire: Toward a Radicalization of Ivoirian Islam?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2016",
		"dateISO": "2016-08-04",
		"year": 2016,
		"journal": "Journal of Religion in Africa",
		"publisher": "Brill",
		"volume": "46",
		"issue": "4",
		"pages": "417-452",
		"doi": "10.1163/15700666-12340090",
		"url": "https://doi.org/10.1163/15700666-12340090"
	},
	{
		"id": "salafism-cote-ivoire-mande-2017",
		"type": "conference-proceedings",
		"title": "Le nouveau dynamisme du salafisme en Côte d'Ivoire: vers une radicalisation de l'islam ivoirien?",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2017",
		"dateISO": "2017",
		"year": 2017,
		"proceedingsTitle": "Les Actes du Dixième Congrès International de l'Association des Études Mandé. Aux carrefours des identités: cohabitation, conflit, et réconciliation en Afrique de l'Ouest et dans les diasporas",
		"url": "https://shs.hal.science/halshs-01691275"
	},
	{
		"id": "sphere-publique-musulmane",
		"type": "book",
		"title": "La construction d'une sphère publique musulmane en Afrique de l'Ouest",
		"authors": [
			"Frédérick Madore"
		],
		"date": "2016",
		"dateISO": "2016-01-22",
		"year": 2016,
		"placeOfPublication": "Québec/Paris",
		"publisher": "Presses de l'Université Laval/Hermann",
		"series": "Religions, cultures et sociétés",
		"doi": "10.58144/20241205-000",
		"url": "https://doi.org/10.58144/20241205-000",
		"reviewedBy": [
			{
				"author": "Abdoulaye Sounaye",
				"year": 2019,
				"title": "CONSTRUCTING A MUSLIM PUBLIC SPHERE IN BURKINA FASO - La construction d'une sphère publique musulmane en Afrique de l'Ouest. By Frédérick Madore. Laval, Canada: Presses de l'Université Laval, 2016. Pp. viii + 208. $29.95, paperback (ISBN: 978-2-7637-2811-7)",
				"journal": "The Journal of African History",
				"volume": "60",
				"issue": "2",
				"pages": "330-332",
				"doi": "10.1017/S0021853719000677",
				"url": "https://doi.org/10.1017/S0021853719000677",
				"excerpt": "This book is a well-documented investigation and a case study with a sociological sensibility, yet one that is also driven by a clear historical agenda. It certainly helps to uncover the sometimes-tortuous trajectories of Islam in Africa. … By calling attention to the societal and structural developments that shaped Islam and Muslim interactions, an approach that has applications within and beyond Burkina Faso, Madore presents a valuable and insightful perspective on understanding Islam in West Africa."
			},
			{
				"author": "Robert Launay",
				"year": 2019,
				"title": "Madore Frédérick. — La construction d'une sphère publique musulmane en Afrique de l'Ouest. Québec, Presses de l'Université Laval, 2016, 208 p., bibl., ill.",
				"journal": "Cahiers d'études africaines",
				"issue": "233",
				"pages": "299-301",
				"doi": "10.4000/etudesafricaines.25055",
				"url": "https://doi.org/10.4000/etudesafricaines.25055",
				"excerpt": "Madore's book chronicles this rise to visibility in the public sphere through a detailed and incisive analysis of three cohorts of Muslim leaders in Burkina Faso. … Madore's book is a highly perceptive account of the shifting terrain of Muslim leadership in Burkina Faso over the past fifty years. … This is really a detailed, authoritative, and perceptive account of the emergence of Islamic leadership in Burkina Faso."
			},
			{
				"author": "Cynthia Ohayon",
				"year": 2017,
				"title": "Frédérick Madore, La construction d'une sphère publique musulmane en Afrique de l'Ouest",
				"journal": "Afrique contemporaine",
				"issue": "261-262",
				"pages": "270-272",
				"doi": "10.3917/afco.261.0270",
				"url": "https://doi.org/10.3917/afco.261.0270",
				"excerpt": "Alors que l'Afrique de l'Ouest est confrontée à la menace du radicalisme religieux, et alors que le Burkina Faso connaît depuis 2014 des bouleversements politiques considérables, cette analyse historique et contemporaine de l'islam burkinabé est plus que jamais pertinente."
			}
		]
	},
	{
		"id": "three-questions-madore-2022",
		"type": "blogpost",
		"title": "Three Questions to Dr. Frédérick Madore",
		"authors": [
			"Rand El Zein",
			"Frédérick Madore"
		],
		"date": "2022",
		"dateISO": "2022-04-07",
		"year": 2022,
		"publisher": "Remoboko blog",
		"doi": "10.58079/tldm",
		"url": "https://doi.org/10.58079/tldm"
	},
	{
		"id": "trier-coder-interpreter-ia-historien-2026",
		"type": "article",
		"title": "Trier, coder, interpréter : comment l’IA redistribue le travail de l’historien face à 30 000 sources sur l’islam ouest-africain",
		"authors": [
			"Frédérick Madore"
		],
		"date": "Forthcoming",
		"dateISO": "2026",
		"year": 2026,
		"journal": "Journal of West African History",
		"publisher": "Michigan State University Press",
		"volume": "12",
		"issue": "2"
	}
];
