/**
 * Reconcile the published slide decks with the talks that link them.
 *
 * The decks live in a second repository and deploy to slides.frederickmadore.com
 * on their own schedule. Nothing connects the two sides at build time, so a deck
 * can go live while the talk that should link it stays untouched — the deck is
 * then reachable only by guessing its URL, and it never appears in the Slides
 * gallery, which is built by filtering communications on `slidesUrl`. That is
 * exactly how 2026-05-06-dga-dormant-collections stayed invisible after it was
 * published.
 *
 * This compares three lists that must agree:
 *   1. the deck site's sitemap.xml — what is actually published
 *   2. `slidesUrl` across src/lib/data/communications — what this site links
 *   3. static/images/communications/slides/ — the mirrored cover posters
 *
 * Why the sitemap and not the deck repo's talks/talks.json: that file is a
 * build input, not a published artefact — the deck site is assembled from an
 * explicit allowlist that talks.json is not on, and it 404s. The sitemap is
 * generated by the same build that deploys the decks, so it states what
 * actually shipped rather than what was intended to.
 *
 * It does not fetch the covers themselves; `generate-slide-posters.mjs --check`
 * does that. Here a poster is only checked for existence, which keeps this a
 * single small request.
 *
 * Usage:
 *   node scripts/check-slides.mjs                     # fetch the live sitemap
 *   node scripts/check-slides.mjs --sitemap=path.xml  # read a local sitemap
 *   node scripts/check-slides.mjs --report=out.md     # also write a markdown report
 *
 * Exit codes: 0 clean, 1 a deck is unlinked / a link dangles / a poster is
 * missing, 2 the sitemap could not be read (inconclusive, not a failure).
 * Metadata drift is reported but never fails the run.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { walkData, loadModule } from './vault-sync-lib.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DATA_DIR = path.join(ROOT, 'src/lib/data/communications');
const POSTER_DIR = path.join(ROOT, 'static/images/communications/slides');

const SLIDES_SITE = 'https://slides.frederickmadore.com';
const SITEMAP_URL = `${SLIDES_SITE}/sitemap.xml`;
const REQUEST_TIMEOUT_MS = 20_000;

const argv = process.argv.slice(2);
const arg = (name) => argv.find((a) => a.startsWith(`--${name}=`))?.slice(name.length + 3) ?? null;
const sitemapPath = arg('sitemap');
const reportPath = arg('report');

/** `https://slides.frederickmadore.com/talks/<slug>/` -> `<slug>`. */
function deckSlug(url) {
	try {
		const segments = new URL(url).pathname.split('/').filter(Boolean);
		if (segments[0] !== 'talks' || !segments[1]) return null;
		return segments[1];
	} catch {
		return null;
	}
}

async function readSitemap() {
	if (sitemapPath) return readFileSync(path.resolve(sitemapPath), 'utf8');
	const response = await fetch(SITEMAP_URL, {
		signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
		headers: { accept: 'application/xml,text/xml' }
	});
	if (!response.ok) throw new Error(`HTTP ${response.status} fetching ${SITEMAP_URL}`);
	return response.text();
}

/**
 * The sitemap is the one input here that does not come out of this repository,
 * and what is read from it lands in a Markdown report the workflow posts as a
 * GitHub issue body. So both fields taken from it are rebuilt character by
 * character from a local alphabet rather than trusted: a value that is not a
 * deck slug or an ISO date is one this site could never have published, and
 * dropping it costs nothing, while pasting it into the report could forge a
 * heading, a link, or the `slidesUrl` line offered for copying into a data file.
 */
const SLUG_ALPHABET = 'abcdefghijklmnopqrstuvwxyz0123456789-';
const DIGITS = '0123456789';

/** A deck slug rebuilt from SLUG_ALPHABET, or null when it is not one. */
function safeSlug(raw) {
	const value = String(raw ?? '');
	if (value.length === 0 || value.length > 128) return null;
	let out = '';
	for (const char of value) {
		const i = SLUG_ALPHABET.indexOf(char);
		if (i === -1) return null;
		out += SLUG_ALPHABET.charAt(i);
	}
	return out;
}

/** A `<lastmod>` rebuilt as YYYY-MM-DD, or null when it is not one. */
function safeDate(raw) {
	const value = String(raw ?? '').trim();
	if (!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(value)) return null;
	let out = '';
	for (const char of value) out += char === '-' ? '-' : DIGITS.charAt(DIGITS.indexOf(char));
	return out;
}

/** Every deck URL in the sitemap, as slug -> { date }. */
function parsePublished(xml) {
	const decks = new Map();
	let rejected = 0;
	for (const block of xml.match(/<url>[\s\S]*?<\/url>/g) ?? []) {
		const loc = block.match(/<loc>([^<]+)<\/loc>/)?.[1];
		const raw = loc ? deckSlug(loc.trim()) : null;
		if (!raw) continue;
		const slug = safeSlug(raw);
		// Counted rather than dropped in silence: a deck skipped here would
		// otherwise never be reconciled and never explained either.
		if (!slug) {
			rejected += 1;
			continue;
		}
		decks.set(slug, { date: safeDate(block.match(/<lastmod>([^<]+)<\/lastmod>/)?.[1]) });
	}
	if (rejected > 0) {
		console.error(
			`Ignored ${rejected} sitemap entry/entries whose slug is not [a-z0-9-]: the deck site ` +
				`published something this check will not repeat into a report.`
		);
	}
	return decks;
}

const group = (findings) => {
	const byKind = new Map();
	for (const finding of findings) {
		byKind.set(finding.kind, [...(byKind.get(finding.kind) ?? []), finding.detail]);
	}
	return byKind;
};

async function reconcile(published) {
	const linked = new Map();
	const malformed = [];
	for (const file of walkData(DATA_DIR)) {
		const record = await loadModule(file);
		if (!record?.slidesUrl) continue;
		const slug = deckSlug(record.slidesUrl);
		if (slug) linked.set(slug, record);
		else malformed.push({ record, file });
	}

	const errors = [];
	const warnings = [];

	for (const { record, file } of malformed) {
		const rel = path.relative(ROOT, file).split(path.sep).join('/');
		errors.push({
			kind: 'Malformed slidesUrl',
			detail: `\`${record.id}\` — \`${record.slidesUrl}\` is not a \`/talks/<slug>/\` URL (${rel})`
		});
	}

	// 1. Published but not linked — the failure this check exists for.
	for (const [slug, deck] of published) {
		if (linked.has(slug)) continue;
		errors.push({
			kind: 'Published deck is not linked',
			detail:
				`\`${slug}\` (${deck.date ?? 'undated'}) is live at ${SLIDES_SITE}/talks/${slug}/ ` +
				`but no communication sets \`slidesUrl\`, so it is absent from the Slides gallery. ` +
				`Add \`slidesUrl: '${SLIDES_SITE}/talks/${slug}/'\` to the matching talk.`
		});
	}

	// 2. Linked but not published — a dead embed on a detail page.
	for (const [slug, record] of linked) {
		if (published.has(slug)) continue;
		errors.push({
			kind: 'Linked deck is not published',
			detail:
				`\`${record.id}\` links \`${slug}\`, which the deck site does not publish. ` +
				`The embed and the “Open deck” link both point at nothing.`
		});
	}

	// 3. Linked, published, but the cover poster was never mirrored.
	for (const [slug, record] of linked) {
		if (!published.has(slug)) continue;
		if (existsSync(path.join(POSTER_DIR, `${slug}.webp`))) continue;
		errors.push({
			kind: 'Missing cover poster',
			detail:
				`\`${slug}\` has no \`static/images/communications/slides/${slug}.webp\`, so the deck ` +
				`embed on \`${record.id}\` opens on a blank stage. Run \`npm run gen:posters\`.`
		});
	}

	// 4. Metadata drift — informative, never fatal. Both sides are hand-written,
	//    so a date that disagrees usually means one was corrected and the other
	//    was not.
	for (const [slug, record] of linked) {
		const deck = published.get(slug);
		if (deck?.date && record.dateISO && deck.date !== record.dateISO) {
			warnings.push({
				kind: 'Date drift',
				detail: `\`${slug}\` — the deck site says ${deck.date}, this site says ${record.dateISO}.`
			});
		}
	}

	const lines = [
		`Compared ${published.size} published deck(s) against ${linked.size} talk(s) linking one.`,
		''
	];
	for (const [kind, details] of group(errors)) {
		lines.push(`### ${kind}`, '', ...details.map((detail) => `- ${detail}`), '');
	}
	for (const [kind, details] of group(warnings)) {
		lines.push(`### ${kind} (warning)`, '', ...details.map((detail) => `- ${detail}`), '');
	}
	if (errors.length === 0 && warnings.length === 0) {
		lines.push(
			'Every published deck is linked from a talk, every link resolves, and every cover poster is mirrored.',
			''
		);
	}

	const report = lines.join('\n');
	if (reportPath) writeFileSync(path.resolve(reportPath), report);
	console.log(report.trimEnd());
	if (errors.length > 0) console.error(`\n${errors.length} problem(s) found.`);
	process.exitCode = errors.length > 0 ? 1 : 0;
}

let published = null;
try {
	published = parsePublished(await readSitemap());
} catch (error) {
	// A sitemap we cannot read is an inconclusive run, not a clean one. Exit 2
	// so the caller can tell "the check could not run" from "the check failed".
	console.error(`Could not read the deck sitemap: ${error.message}`);
	process.exitCode = 2;
}

if (published && published.size === 0) {
	console.error(
		`No deck URLs found in ${sitemapPath ?? SITEMAP_URL}; refusing to report every talk as dangling.`
	);
	process.exitCode = 2;
} else if (published) {
	await reconcile(published);
}
