/**
 * Generated by scripts/generate-image-variants.mjs. Do not edit manually.
 */
export interface ImageVariantManifestEntry {
	readonly sourceWidth: number;
	readonly widths: readonly number[];
}

export const imageVariantManifest: Readonly<Record<string, ImageVariantManifestEntry>> = {
	'activities/amira-launch-2026-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/amira-launch-2026.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'activities/asa-panel-discussion.webp': {
		sourceWidth: 1237,
		widths: [400, 800]
	},
	'activities/charting-new-territory-workshop-hannover-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/De-Gruyter-ZMO.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/dga-roundtable-2026-hero.webp': {
		sourceWidth: 1200,
		widths: [400, 800]
	},
	'activities/dh-digital-history-luxembourg-2026-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/ECAS-2025.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/ecole-nationale-des-chartes.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'activities/ENIUGH-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/humanistica-2025-dakar-hero.webp': {
		sourceWidth: 1200,
		widths: [400, 800]
	},
	'activities/humanistica-2025-dakar.webp': {
		sourceWidth: 400,
		widths: []
	},
	'activities/jmas-review-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/puidoux.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/research-africa-reviews-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/The-Digital-Orientalist-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/The-Digital-Orientalist.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/tracing-islamic-knowledge-production.webp': {
		sourceWidth: 1200,
		widths: [400, 800]
	},
	'activities/uppsala-2025-hero.webp': {
		sourceWidth: 1200,
		widths: [400, 800]
	},
	'activities/VolkswagenStiftung-logo.webp': {
		sourceWidth: 548,
		widths: [400]
	},
	'activities/volkswagenstiftung-open-up-kickoff-2026-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'activities/zmo-farewell-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/acfas_81e.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'communications/ALMEDA-logo-hero.webp': {
		sourceWidth: 1173,
		widths: [400, 800]
	},
	'communications/ALMEDA-logo.webp': {
		sourceWidth: 1173,
		widths: [400, 800]
	},
	'communications/associations-chretiennes-islamiques-campus-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/associations-chretiennes-islamiques-campus.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/c2dh-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/c2dh.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'communications/CAAS-logo-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/CAAS-logo.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/ciram-2025-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/ciram-2025.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/current-dynamics-islam-burkina-faso-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/current-dynamics-islam-burkina-faso.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/DH-islam-burkina-faso-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/DH-islam-burkina-faso.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/digital-hoarding-open-archives-warsaw-2026-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/digital-hoarding-open-archives-warsaw-2026.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/distam-2024-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/distam-2024.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/dormant-digital-collections-ai-triage-dga-2026-hero.webp': {
		sourceWidth: 917,
		widths: [400, 800]
	},
	'communications/dormant-digital-collections-ai-triage-dga-2026.webp': {
		sourceWidth: 917,
		widths: [400, 800]
	},
	'communications/ecas-2023-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/ecas-2023.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/ecas-2025-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/ecas-2025.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/EHESS-2025-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/EHESS-2025.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/elites-musulmanes-cote-divoire-burkina-faso-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/elites-musulmanes-cote-divoire-burkina-faso.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/emancipation-feminine-militantisme-islamique-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/emancipation-feminine-militantisme-islamique.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/ENIUGH-hero.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/ENIUGH.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/evolutions-nouvelles-formes-islam-afrique-ouest-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/evolutions-nouvelles-formes-islam-afrique-ouest.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/formation-recherche-en-ligne-ouagadougou.jpeg': {
		sourceWidth: 1024,
		widths: [400, 800]
	},
	'communications/Gaston_Berger_University_logo-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/Gaston_Berger_University_logo.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/generations-imam-benin-2021-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/generations-imam-benin-2021.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/humanistica-2025-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/humanistica-2025.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/interfaith-coexistence-campuses.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/islam-algorithms-ai-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/islam-algorithms-ai.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/islam-burkina-cote-ivoire-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/islam-burkina-cote-ivoire.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/islam-burkina-faso-collection-omeka-2022-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/islam-burkina-faso-collection-omeka-2022.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/islam-ivoirien-burkinabe-numerique-2016-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/islam-ivoirien-burkinabe-numerique-2016.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/islam-peripheries-dh-ai-west-africa-central-asia-2026-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/islam-peripheries-dh-ai-west-africa-central-asia-2026.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/islam-peripheries-open-up-2026-hero.webp': {
		sourceWidth: 781,
		widths: [400]
	},
	'communications/islam-peripheries-open-up-2026.webp': {
		sourceWidth: 781,
		widths: [400]
	},
	'communications/islam-university-campuses-cote-divoire-2019-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/islam-university-campuses-cote-divoire-2019.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/lasdel-logo-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/lasdel-logo.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/MANSA-logo-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/MANSA-logo.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/militantisme-islamique-campus-lome-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/militantisme-islamique-campus-lome.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/militantisme-islamique-feminin-burkina-2019-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/militantisme-islamique-feminin-burkina-2019.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/muslim-intellectuals-francophone-salafis-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/muslim-intellectuals-francophone-salafis.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/paris-cite-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/paris-cite.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/perspectives-in-motion-hero.webp': {
		sourceWidth: 874,
		widths: [400, 800]
	},
	'communications/perspectives-in-motion.webp': {
		sourceWidth: 874,
		widths: [400, 800]
	},
	'communications/point-de-passage-frontieres-religieuses-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/point-de-passage-frontieres-religieuses.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/poster-launch-IWAC-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/poster-launch-IWAC.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/public-islam-cote-ivoire-burkina-faso-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/public-islam-cote-ivoire-burkina-faso.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/publishing-islam-burkina-faso-collection-2022-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/publishing-islam-burkina-faso-collection-2022.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/puidoux-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/puidoux.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/reaf-2026-hero.webp': {
		sourceWidth: 977,
		widths: [400, 800]
	},
	'communications/reaf-2026.webp': {
		sourceWidth: 977,
		widths: [400, 800]
	},
	'communications/recherche-documentaire-zotero-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/recherche-documentaire-zotero.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/reconfiguring-archive-amira-2026.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/REMOBOKO-final-conference.webp': {
		sourceWidth: 1024,
		widths: [400, 800]
	},
	'communications/representations-islam-muslims-togo-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/representations-islam-muslims-togo.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/SADILAR-hero.webp': {
		sourceWidth: 940,
		widths: [400, 800]
	},
	'communications/SADILAR.webp': {
		sourceWidth: 940,
		widths: [400, 800]
	},
	'communications/salafisme-pentecotisme-campus-benin-togo-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/salafisme-pentecotisme-campus-benin-togo.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/salafisme-securitisation-benin-togo-2022-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/salafisme-securitisation-benin-togo-2022.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/union-islamique-benin-elections-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/union-islamique-benin-elections.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/University_of_Texas_at_Austin_seal-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/University_of_Texas_at_Austin_seal.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/VWST-logo.webp': {
		sourceWidth: 548,
		widths: [400]
	},
	'communications/workshop-Dakar-2019-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/workshop-Dakar-2019.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/workshop-religion-in-higher-educational-institutions-2021-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/workshop-religion-in-higher-educational-institutions-2021.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/workshop-religions-on-campus-2022-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/workshop-religions-on-campus-2022.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/young-muslims-civic-engagement-burkina-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/young-muslims-civic-engagement-burkina.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/yovo-historian-benin-togo-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/yovo-historian-benin-togo.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'communications/zmo-kitchen-talks-logo.webp': {
		sourceWidth: 224,
		widths: []
	},
	'communications/zmo-kitchen-talks-podcast-2025.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'communications/zzf-logo-hero.webp': {
		sourceWidth: 900,
		widths: [400, 800]
	},
	'communications/zzf-logo.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'digital-humanities/amira.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/burkina-faso-digital-exhibits.webp': {
		sourceWidth: 1200,
		widths: [400, 800]
	},
	'digital-humanities/dh-ai-african-studies.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/global-heshmat.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/islam-burkinafaso-banner.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/iwac-ai-pipelines.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/iwac-mcp-server.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/iwac-sentiment-analysis.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'digital-humanities/IWAC.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/omeka-s-docker.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/remoboko.webp': {
		sourceWidth: 1000,
		widths: [400, 800]
	},
	'digital-humanities/zmo-ai-pipelines.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'digital-humanities/zmo-visualisations.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'Profile-picture.webp': {
		sourceWidth: 300,
		widths: []
	},
	'publications/acteurs-religieux-numerique-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/acteurs-religieux-numerique.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/africa-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/africa-today-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/africa-today.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/africa.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/bulletin-franco-paix-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/bulletin-franco-paix.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/Cahiers-détudes-africaines-229-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/Cahiers-détudes-africaines-229.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/canadian-journal-of-african-studies-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/canadian-journal-of-african-studies.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/digital-history-bielefeld-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/digital-history-bielefeld.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/dissertation-cote-ivoire-burkina-faso-2018-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/dissertation-cote-ivoire-burkina-faso-2018.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/encyclopaedia-of-islam-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/encyclopaedia-of-islam.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/imams-ouagadougou-2020-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/imams-ouagadougou-2020.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/islam-politique-ouagadougou-2013-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/islam-politique-ouagadougou-2013.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/journal-des-anthropologues-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/journal-des-anthropologues.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/journal-of-religion-in-africa-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/journal-of-religion-in-africa.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/muslim-minorities-africa-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/muslim-minorities-africa.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/muslim-ngos-burkina-faso-2016.avif': {
		sourceWidth: 410,
		widths: [400]
	},
	'publications/plan-brouillon-2021-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/plan-brouillon-2021.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/religieux-internet-burkina-faso-2019-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/religieux-internet-burkina-faso-2019.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/religion-internet-burkina-faso-2024-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/religion-internet-burkina-faso-2024.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/religions-numeriques-afrique-2018-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/religions-numeriques-afrique-2018.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/religiosity-university-campuses-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/religiosity-university-campuses.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/religious-activism-campuses-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/religious-activism-campuses.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/repenser-categorisation-religieuse-benin.webp': {
		sourceWidth: 331,
		widths: []
	},
	'publications/revue-d-histoire-contemporaine-de-l-afrique-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/revue-d-histoire-contemporaine-de-l-afrique.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/salafisme-cote-ivoire-2017-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/salafisme-cote-ivoire-2017.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/sphere-publique-musulmane-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/sphere-publique-musulmane.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/the-journal-of-modern-african-studies-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/the-journal-of-modern-african-studies.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/Theologiques-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/Theologiques.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/three-questions-madore-2022-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/three-questions-madore-2022.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/zmo-bulletin-44-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/zmo-bulletin-44.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/zmo-bulletin-46-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/zmo-bulletin-46.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/zmo-bulletin-48-conversation-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/zmo-bulletin-48-conversation.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/zmo-bulletin-48-decentering-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/zmo-bulletin-48-decentering.webp': {
		sourceWidth: 600,
		widths: [400]
	},
	'publications/zmo-jahrbuch-hero.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'publications/zmo-jahrbuch.webp': {
		sourceWidth: 800,
		widths: [400]
	},
	'research/campus-activism.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'research/islams-peripheries.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'research/IWAC.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'research/muslim-minorities.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'research/youth-women-activism.webp': {
		sourceWidth: 1280,
		widths: [400, 800]
	},
	'teaching/guest-lecture.webp': {
		sourceWidth: 1920,
		widths: [400, 800, 1600]
	},
	'teaching/university-of-florida-logo.png': {
		sourceWidth: 226,
		widths: []
	},
	'teaching/uottawa.png': {
		sourceWidth: 179,
		widths: []
	}
};
