// AUTO-GENERATED by scripts/generate-reference-index.mjs — DO NOT EDIT.
// Regenerate with `npm run gen:refs` (runs automatically via the prebuild hook).
/* eslint-disable */
import type { ReferenceIndexEntry } from '$lib/types/referenceIndex';

export const referenceIndex: Record<string, ReferenceIndexEntry> = {
	"acteurs-religieux-numerique": {
		"id": "acteurs-religieux-numerique",
		"itemType": "publication",
		"title": "Les acteurs religieux africains à l'ère du numérique",
		"authors": [
			"Pamela Millet-Mouity",
			"Frédérick Madore"
		],
		"type": "special-issue",
		"date": "2017",
		"dateISO": "2017",
		"year": 2017,
		"image": "images/publications/acteurs-religieux-numerique.webp",
		"heroImage": {
			"src": "images/publications/acteurs-religieux-numerique-hero.webp"
		},
		"journal": "Émulations",
		"publisher": "Presses universitaires de Louvain"
	},
	"ai-archives-humanistica-2025": {
		"id": "ai-archives-humanistica-2025",
		"itemType": "communication",
		"title": "Intelligence artificielle et traitement des archives numériques : applications et enjeux dans la Collection Islam Afrique de l'Ouest",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "24 April 2025",
		"dateISO": "2025-04-24",
		"year": 2025,
		"image": "images/communications/humanistica-2025.webp",
		"heroImage": {
			"src": "images/communications/humanistica-2025-hero.webp"
		},
		"conference": "Colloque annuel Humanistica 2025",
		"location": "Cheikh Anta Diop University",
		"country": "Senegal"
	},
	"ambition-federatrice-faitieres-islamiques-2026": {
		"id": "ambition-federatrice-faitieres-islamiques-2026",
		"itemType": "publication",
		"title": "L'ambition fédératrice à l'épreuve de la diversité : étude comparative des faîtières islamiques au Burkina Faso, Togo, Bénin et Côte d'Ivoire",
		"authors": [
			"Frédérick Madore"
		],
		"type": "chapter",
		"date": "Forthcoming",
		"dateISO": "2026",
		"year": 2026,
		"book": "Vie associative et pratiques organisationnelles en Afrique de l'Ouest : saisir les associations par leur architecture bureaucratique",
		"publisher": "Africae"
	},
	"archives-algorithms-iwac-2025": {
		"id": "archives-algorithms-iwac-2025",
		"itemType": "communication",
		"title": "From Archives to Algorithms: Uncovering Transregional Islamic Connections through the Islam West Africa Collection (IWAC)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "11 September 2025",
		"dateISO": "2025-09-11",
		"year": 2025,
		"image": "images/communications/ENIUGH.webp",
		"heroImage": {
			"src": "images/communications/ENIUGH-hero.webp"
		},
		"conference": "Eighth European Congress on World and Global History",
		"location": "Linnaeus University",
		"country": "Sweden"
	},
	"associations-chretiennes-islamiques-campus": {
		"id": "associations-chretiennes-islamiques-campus",
		"itemType": "communication",
		"title": "Les associations chrétiennes et islamiques sur les campus de l'Université d'Abomey-Calavi et de l'Université de Lomé depuis 1970: la laïcité à l'université face à l'activisme religieux",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "8 March 2022",
		"dateISO": "2022-03-08",
		"year": 2022,
		"image": "images/communications/associations-chretiennes-islamiques-campus.webp",
		"heroImage": {
			"src": "images/communications/associations-chretiennes-islamiques-campus-hero.webp"
		},
		"conference": "Laboratoire d'Analyse et de Recherche, Religions, Espaces et Développement (LARRED)",
		"location": "Université d'Abomey-Calavi",
		"country": "Benin"
	},
	"author-meets-critic-faith-activism-2024": {
		"id": "author-meets-critic-faith-activism-2024",
		"itemType": "communication",
		"title": "Author Meets Critic. Faith-based Student Activism in Togo and Benin: Muslims and Christians on University Campuses",
		"authors": [
			"Frédérick Madore"
		],
		"type": "panel",
		"date": "12 December 2024",
		"dateISO": "2024-12-12",
		"year": 2024,
		"image": "images/communications/ASA-Logo.svg",
		"conference": "67th Meeting of the African Studies Association (ASA)",
		"location": "Chicago",
		"country": "United States"
	},
	"beninese-imam-election-2022": {
		"id": "beninese-imam-election-2022",
		"itemType": "publication",
		"title": "A Beninese Imam's Controversial 2019 Election Campaign: Muslim Leadership and Political Engagement in a Minority Context",
		"authors": [
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2022",
		"dateISO": "2022-06-06",
		"year": 2022,
		"image": "images/publications/muslim-minorities-africa.webp",
		"heroImage": {
			"src": "images/publications/muslim-minorities-africa-hero.webp"
		},
		"journal": "Islamic Africa",
		"publisher": "Brill"
	},
	"beyond-keywords-ai-iwac-mcp-2026": {
		"id": "beyond-keywords-ai-iwac-mcp-2026",
		"itemType": "communication",
		"title": "Beyond Keywords: AI-Mediated Access to the Islam West Africa Collection through an MCP Server and Agent Skill",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "15 June 2026",
		"dateISO": "2026-06-15",
		"year": 2026,
		"image": "images/communications/c2dh.webp",
		"heroImage": {
			"src": "images/communications/c2dh-hero.webp"
		},
		"conference": "Eighth Conference on Digital Humanities and Digital History",
		"location": "University of Luxembourg",
		"country": "Luxembourg"
	},
	"charting-new-territory-digital-humanities-ki-african-studies-2026": {
		"id": "charting-new-territory-digital-humanities-ki-african-studies-2026",
		"itemType": "publication",
		"title": "Charting New Territory: Digital Humanities und Künstliche Intelligenz in den African Studies",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren"
		],
		"type": "blogpost",
		"date": "2026",
		"dateISO": "2026-03-31",
		"year": 2026,
		"image": "images/publications/digital-history-bielefeld.webp",
		"heroImage": {
			"src": "images/publications/digital-history-bielefeld-hero.webp"
		},
		"publisher": "Digital History Bielefeld"
	},
	"collection-islam-afrique-ouest": {
		"id": "collection-islam-afrique-ouest",
		"itemType": "communication",
		"title": "La Collection Islam Afrique de l'Ouest: nouvelles perspectives sur l'histoire des communautés musulmanes via la presse et les humanités numériques",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "25 March 2024",
		"dateISO": "2024-03-25",
		"year": 2024,
		"image": "images/communications/distam-2024.webp",
		"heroImage": {
			"src": "images/communications/distam-2024-hero.webp"
		},
		"conference": "Enjeux éthiques et juridiques au diapason des données de la recherche en études aréales",
		"location": "Aix-en-Provence, Maison méditerranéenne des sciences de l'Homme",
		"country": "France"
	},
	"collection-islam-humanites-2024": {
		"id": "collection-islam-humanites-2024",
		"itemType": "communication",
		"title": "La Collection Islam Afrique de l'Ouest: enjeux éthiques et décolonisation des humanités numériques",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "28 June 2024",
		"dateISO": "2024-06-28",
		"year": 2024,
		"image": "images/communications/MANSA-logo.webp",
		"heroImage": {
			"src": "images/communications/MANSA-logo-hero.webp"
		},
		"conference": "12th International Conference on Mande Studies",
		"location": "Institut des Sciences Humaines",
		"country": "Mali"
	},
	"communaute-musulmane-burkina-faso-2014": {
		"id": "communaute-musulmane-burkina-faso-2014",
		"itemType": "publication",
		"title": "Communauté Musulmane du Burkina Faso",
		"authors": [
			"Frédérick Madore",
			"Muriel Gomez-Perez"
		],
		"type": "encyclopedia",
		"date": "2014",
		"dateISO": "2014-09-01",
		"year": 2014,
		"image": "images/publications/encyclopaedia-of-islam.webp",
		"heroImage": {
			"src": "images/publications/encyclopaedia-of-islam-hero.webp"
		},
		"publisher": "Brill"
	},
	"current-dynamics-islam-burkina-faso": {
		"id": "current-dynamics-islam-burkina-faso",
		"itemType": "communication",
		"title": "Current Dynamics of Islam in Burkina Faso",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "16 November 2018",
		"dateISO": "2018-11-16",
		"year": 2018,
		"image": "images/communications/current-dynamics-islam-burkina-faso.webp",
		"heroImage": {
			"src": "images/communications/current-dynamics-islam-burkina-faso-hero.webp"
		},
		"conference": "Sahel Seminars",
		"location": "University of Florida",
		"country": "United States"
	},
	"defense-laicite-musulmans-burkina": {
		"id": "defense-laicite-musulmans-burkina",
		"itemType": "communication",
		"title": "La défense de la laïcité de l'État, un outil de revendication politique pour les musulmans au Burkina Faso (depuis 1960)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "4 July 2019",
		"dateISO": "2019-07-04",
		"year": 2019,
		"image": "images/communications/workshop-Dakar-2019.webp",
		"heroImage": {
			"src": "images/communications/workshop-Dakar-2019-hero.webp"
		},
		"conference": "Debating Laïcité in the Sahel: What Future for Secularism?",
		"location": "West African Research Center",
		"country": "Senegal"
	},
	"dh-ai-african-studies-2025": {
		"id": "dh-ai-african-studies-2025",
		"itemType": "communication",
		"title": "Digital Humanities (DH) and AI in African Studies: Opportunities, Challenges, and Decolonial Perspectives",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren"
		],
		"type": "panel",
		"date": "26 June 2025",
		"dateISO": "2025-06-26",
		"year": 2025,
		"image": "images/communications/ecas-2025.webp",
		"heroImage": {
			"src": "images/communications/ecas-2025-hero.webp"
		},
		"conference": "10th European Conference of African Studies (ECAS)",
		"location": "Prague",
		"country": "Czech Republic"
	},
	"digital-history-exe": {
		"id": "digital-history-exe",
		"itemType": "communication",
		"title": "DigitalHistory.Exe: Running New Programs on Old Files",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "8 April 2025",
		"dateISO": "2025-04-08",
		"year": 2025,
		"image": "images/communications/zzf-logo.webp",
		"heroImage": {
			"src": "images/communications/zzf-logo-hero.webp"
		},
		"conference": "Master Class",
		"location": "Leibniz Centre for Contemporary History Potsdam (ZZF)",
		"country": "Germany"
	},
	"digital-hoarding-open-archives-warsaw-2026": {
		"id": "digital-hoarding-open-archives-warsaw-2026",
		"itemType": "communication",
		"title": "From Digital Hoarding to Open Archives: Using AI Agents to Unlock West African Newspaper Collections",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "16 April 2026",
		"dateISO": "2026-04-16",
		"year": 2026,
		"image": "images/communications/digital-hoarding-open-archives-warsaw-2026.webp",
		"heroImage": {
			"src": "images/communications/digital-hoarding-open-archives-warsaw-2026-hero.webp"
		},
		"conference": "Non-European Approaches in European Academia: Strategies for De-Europeanizing Research",
		"location": "Tadeusz Manteuffel Institute of History, Polish Academy of Sciences, Warsaw",
		"country": "Poland"
	},
	"digital-humanities-islam-burkina-faso": {
		"id": "digital-humanities-islam-burkina-faso",
		"itemType": "communication",
		"title": "Digital Humanities in the Making: The Islam Burkina Faso Collection",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "16 September 2022",
		"dateISO": "2022-09-16",
		"year": 2022,
		"image": "images/communications/DH-islam-burkina-faso.webp",
		"heroImage": {
			"src": "images/communications/DH-islam-burkina-faso-hero.webp"
		},
		"conference": "Open Day at ZMO",
		"location": "Leibniz-Zentrum Moderner Orient",
		"country": "Germany"
	},
	"dormant-digital-collections-ai-triage-dga-2026": {
		"id": "dormant-digital-collections-ai-triage-dga-2026",
		"itemType": "communication",
		"title": "Dormant Digital Collections, AI Triage: Lessons from the Islam West Africa Collection and Beyond",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "6 May 2026",
		"dateISO": "2026-05-06",
		"year": 2026,
		"image": "images/communications/dormant-digital-collections-ai-triage-dga-2026.webp",
		"heroImage": {
			"src": "images/communications/dormant-digital-collections-ai-triage-dga-2026-hero.webp"
		},
		"conference": "Deutsche Gesellschaft für Asienforschung (DGA)",
		"location": "Leibniz-Zentrum Moderner Orient",
		"country": "Germany"
	},
	"elites-musulmanes-cote-divoire-burkina-faso": {
		"id": "elites-musulmanes-cote-divoire-burkina-faso",
		"itemType": "communication",
		"title": "Les élites musulmanes en Côte d'Ivoire et au Burkina Faso depuis 1990 : des mobilisations politiques contrastées",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "25 September 2018",
		"dateISO": "2018-09-25",
		"year": 2018,
		"image": "images/communications/elites-musulmanes-cote-divoire-burkina-faso.webp",
		"heroImage": {
			"src": "images/communications/elites-musulmanes-cote-divoire-burkina-faso-hero.webp"
		},
		"conference": "Conférences midi du CIRAM",
		"location": "Université Laval",
		"country": "Canada"
	},
	"emancipation-feminine-militantisme-islamique": {
		"id": "emancipation-feminine-militantisme-islamique",
		"itemType": "communication",
		"title": "Émancipation féminine et militantisme islamique en Afrique de l'Ouest depuis 1980: quelques enseignements du Burkina Faso, de la Côte d'Ivoire, du Togo et du Bénin",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "22 March 2022",
		"dateISO": "2022-03-22",
		"year": 2022,
		"image": "images/communications/emancipation-feminine-militantisme-islamique.webp",
		"heroImage": {
			"src": "images/communications/emancipation-feminine-militantisme-islamique-hero.webp"
		},
		"conference": "Atelier international Femmes africaines dans une société d'hommes: espaces contraints, habilité sociale et formes d'émancipation",
		"location": "Université de Kabala",
		"country": "Mali"
	},
	"etablir-faitiere-islamique": {
		"id": "etablir-faitiere-islamique",
		"itemType": "communication",
		"title": "L'ambition fédératrice à l'épreuve de la diversité : étude comparative des faîtières islamiques au Burkina Faso, Togo, Bénin et Côte d'Ivoire",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "4 March 2025",
		"dateISO": "2025-03-04",
		"year": 2025,
		"image": "images/communications/puidoux.webp",
		"heroImage": {
			"src": "images/communications/puidoux-hero.webp"
		},
		"conference": "Workshop Religiosités et vies associatives en Afrique: entre stratégies d'organisation et vies en mouvement",
		"location": "Puidoux",
		"country": "Switzerland"
	},
	"evolutions-nouvelles-formes-islam-afrique-ouest": {
		"id": "evolutions-nouvelles-formes-islam-afrique-ouest",
		"itemType": "communication",
		"title": "Évolutions et nouvelles formes de l'islam en Afrique de l'Ouest: vers une radicalisation?",
		"authors": [
			"CIRAM"
		],
		"type": "event",
		"date": "24 March 2016",
		"dateISO": "2016-03-24",
		"year": 2016,
		"image": "images/communications/evolutions-nouvelles-formes-islam-afrique-ouest.webp",
		"heroImage": {
			"src": "images/communications/evolutions-nouvelles-formes-islam-afrique-ouest-hero.webp"
		},
		"conference": "Table-ronde organisée par le Centre Interdisciplinaire de Recherche sur l'Afrique et le Moyen-Orient (CIRAM)",
		"location": "Université Laval",
		"country": "Canada"
	},
	"exister-contexte-autoritaire-lome-2023": {
		"id": "exister-contexte-autoritaire-lome-2023",
		"itemType": "publication",
		"title": "Exister en contexte autoritaire : les associations étudiantes chrétiennes et islamiques à l'Université de Lomé sous Gnassingbé Eyadéma, 1970–2005",
		"authors": [
			"Frédérick Madore"
		],
		"type": "chapter",
		"date": "2023",
		"dateISO": "2023",
		"year": 2023,
		"image": "images/publications/religiosity-university-campuses.webp",
		"heroImage": {
			"src": "images/publications/religiosity-university-campuses-hero.webp"
		},
		"book": "Religiosity on University Campuses in Africa: Trends and Experiences",
		"publisher": "LIT Verlag"
	},
	"faith-based-student-organizations-2023": {
		"id": "faith-based-student-organizations-2023",
		"itemType": "communication",
		"title": "'Too Young,' 'Immature,' and not Committed Enough: The Decline of Faith-Based Student Organizations in Togo and Benin?",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "2 June 2023",
		"dateISO": "2023-06-02",
		"year": 2023,
		"image": "images/communications/ecas-2023.webp",
		"heroImage": {
			"src": "images/communications/ecas-2023-hero.webp"
		},
		"conference": "9th European Conference on African Studies (ECAS)",
		"location": "University of Cologne",
		"country": "Germany"
	},
	"formation-recherche-en-ligne-niamey": {
		"id": "formation-recherche-en-ligne-niamey",
		"itemType": "communication",
		"title": "Formation en recherche en ligne",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "23 March 2024",
		"dateISO": "2024-03-23",
		"year": 2024,
		"image": "images/communications/lasdel-logo.webp",
		"heroImage": {
			"src": "images/communications/lasdel-logo-hero.webp"
		},
		"conference": "Atelier",
		"location": "Laboratoire d'Etudes et de Recherches sur les Dynamiques Sociales et le Développement Local (LASDEL)",
		"country": "Niger"
	},
	"formation-recherches-en-ligne-ouagadougou": {
		"id": "formation-recherches-en-ligne-ouagadougou",
		"itemType": "communication",
		"title": "Formation en recherche en ligne",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "19 July 2023",
		"dateISO": "2023-07-19",
		"year": 2023,
		"image": "images/communications/formation-recherche-en-ligne-ouagadougou.jpeg",
		"heroImage": {
			"src": "images/communications/formation-recherche-en-ligne-ouagadougou.jpeg"
		},
		"conference": "Atelier",
		"location": "Université Joseph Ki-Zerbo",
		"country": "Burkina Faso"
	},
	"francophone-muslim-intellectuals-burkina-faso-2020": {
		"id": "francophone-muslim-intellectuals-burkina-faso-2020",
		"itemType": "publication",
		"title": "Francophone Muslim intellectuals, Islamic associational life and religious authority in Burkina Faso",
		"authors": [
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2020",
		"dateISO": "2020-05-21",
		"year": 2020,
		"image": "images/publications/africa.webp",
		"heroImage": {
			"src": "images/publications/africa-hero.webp"
		},
		"journal": "Africa",
		"publisher": "Cambridge University Press"
	},
	"generations-imam-benin-2021": {
		"id": "generations-imam-benin-2021",
		"itemType": "communication",
		"title": "Generations at Odds: The Controversial Political Candidacy of an Imam in Benin (2019)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "18 June 2021",
		"dateISO": "2021-06-18",
		"year": 2021,
		"image": "images/communications/generations-imam-benin-2021.webp",
		"heroImage": {
			"src": "images/communications/generations-imam-benin-2021-hero.webp"
		},
		"conference": "11th International Conference of the Mande Studies Association (MANSA)",
		"location": "Uppsala",
		"country": "Sweden"
	},
	"good-muslim-bad-muslim-togo-2019": {
		"id": "good-muslim-bad-muslim-togo-2019",
		"itemType": "communication",
		"title": "'Good Muslim, Bad Muslim' in Togo: The Construction of a Religious Minority Amid a Constitutional Crisis (2017–2018)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "21 November 2019",
		"dateISO": "2019-11-21",
		"year": 2019,
		"image": "images/communications/ASA-Logo.svg",
		"conference": "62nd Meeting of the African Studies Association (ASA)",
		"location": "Boston",
		"country": "United States"
	},
	"good-muslim-bad-muslim-togo-2021": {
		"id": "good-muslim-bad-muslim-togo-2021",
		"itemType": "publication",
		"title": "'Good Muslim, bad Muslim' in Togo: religious minority identity construction amid a sociopolitical crisis (2017-2018)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2021",
		"dateISO": "2021-06-07",
		"year": 2021,
		"image": "images/publications/the-journal-of-modern-african-studies.webp",
		"heroImage": {
			"src": "images/publications/the-journal-of-modern-african-studies-hero.webp"
		},
		"journal": "The Journal of Modern African Studies",
		"publisher": "Cambridge University Press"
	},
	"hackett-interview-digital-media-2017": {
		"id": "hackett-interview-digital-media-2017",
		"itemType": "publication",
		"title": "Interview with Rosalind I. J. Hackett on Religion and Digital Media Trends in Africa",
		"authors": [
			"Rosalind I. J. Hackett",
			"Frédérick Madore",
			"Pamela Millet-Mouity"
		],
		"type": "article",
		"date": "2017",
		"dateISO": "2017",
		"year": 2017,
		"image": "images/publications/acteurs-religieux-numerique.webp",
		"heroImage": {
			"src": "images/publications/acteurs-religieux-numerique-hero.webp"
		},
		"journal": "Émulations",
		"publisher": "Presses universitaires de Louvain"
	},
	"hadj-cote-divoire-2018": {
		"id": "hadj-cote-divoire-2018",
		"itemType": "publication",
		"title": "L'organisation du hadj en Côte d'Ivoire: entre facteur de cohésion et source de rivalités au sein de la communauté musulmane (1993-2010)",
		"authors": [
			"Frédérick Madore",
			"Yssoufou Traoré"
		],
		"type": "article",
		"date": "2018",
		"dateISO": "2018",
		"year": 2018,
		"image": "images/publications/Cahiers-détudes-africaines-229.webp",
		"heroImage": {
			"src": "images/publications/Cahiers-détudes-africaines-229-hero.webp"
		},
		"journal": "Cahiers d'études africaines",
		"publisher": "Éditions de l’École des Hautes Études en Sciences Sociales"
	},
	"hajj-organization-state-cote-divoire-2016": {
		"id": "hajj-organization-state-cote-divoire-2016",
		"itemType": "communication",
		"title": "The Organization of the Hajj and the State: Cohesion and Rivalries within the Muslim Community of Côte d'Ivoire (1993-2006)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "3 December 2016",
		"dateISO": "2016-12-03",
		"year": 2016,
		"image": "images/communications/ASA-Logo.svg",
		"conference": "59th Annual Meeting of the African Studies Association (ASA)",
		"location": "Washington D.C.",
		"country": "United States"
	},
	"histoire-communautes-musulmanes-ouest-africaines-2025": {
		"id": "histoire-communautes-musulmanes-ouest-africaines-2025",
		"itemType": "communication",
		"title": "L'histoire des communautés musulmanes ouest-africaines : approches et perspectives des humanités numériques",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "20 May 2025",
		"dateISO": "2025-05-20",
		"year": 2025,
		"image": "images/communications/EHESS-2025.webp",
		"heroImage": {
			"src": "images/communications/EHESS-2025-hero.webp"
		},
		"conference": "Séminaire 'Actualité de la recherche en anthropologie sociale en Afrique' animé par Sophie Bava, Alice Degorce et Marie Miran",
		"location": "École des hautes études en sciences sociales (EHESS)",
		"country": "France"
	},
	"historian-vs-ai-ecas-2025": {
		"id": "historian-vs-ai-ecas-2025",
		"itemType": "communication",
		"title": "Historian vs AI: who reads and analyses archives best?",
		"authors": [
			"Vincent Hiribarren",
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "26 June 2025",
		"dateISO": "2025-06-26",
		"year": 2025,
		"image": "images/communications/ecas-2025.webp",
		"heroImage": {
			"src": "images/communications/ecas-2025-hero.webp"
		},
		"conference": "10th European Conference of African Studies (ECAS)",
		"location": "Prague",
		"country": "Czech Republic"
	},
	"humanites-numeriques-dh-ia-etudes-africaines-reaf-2026": {
		"id": "humanites-numeriques-dh-ia-etudes-africaines-reaf-2026",
		"itemType": "communication",
		"title": "Humanités numériques (DH) et IA dans les études africaines",
		"authors": [
			"Vincent Hiribarren",
			"Frédérick Madore"
		],
		"type": "panel",
		"date": "30 juin 2026",
		"dateISO": "2026-06-30",
		"year": 2026,
		"image": "images/communications/reaf-2026.webp",
		"heroImage": {
			"src": "images/communications/reaf-2026-hero.webp"
		},
		"conference": "9èmes Rencontres des études africaines en France (REAF)",
		"location": "Paris",
		"country": "France"
	},
	"humanites-numeriques-ia-ecole-chartes-2025": {
		"id": "humanites-numeriques-ia-ecole-chartes-2025",
		"itemType": "communication",
		"title": "Humanités numériques et flux de recherche augmentés par l'IA pour la Collection islam Afrique de l'Ouest",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "22 May 2025",
		"dateISO": "2025-05-22",
		"year": 2025,
		"image": "images/activities/ecole-nationale-des-chartes.webp",
		"heroImage": {
			"src": "images/activities/ecole-nationale-des-chartes.webp"
		},
		"conference": "Work talk",
		"location": "École nationale des chartes",
		"country": "France"
	},
	"imams-espace-public-ouagadougou-2012": {
		"id": "imams-espace-public-ouagadougou-2012",
		"itemType": "communication",
		"title": "Imams et espace public à Ouagadougou depuis 1990: entre visibilité nouvelle et concertation entre les générations",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "4 May 2012",
		"dateISO": "2012-05-04",
		"year": 2012,
		"image": "images/communications/CAAS-logo.webp",
		"heroImage": {
			"src": "images/communications/CAAS-logo-hero.webp"
		},
		"conference": "42nd Annual Canadian Association of African Studies Conference (CAAS)",
		"location": "Université Laval",
		"country": "Canada"
	},
	"imams-islamic-preachers-ouagadougou-2013": {
		"id": "imams-islamic-preachers-ouagadougou-2013",
		"itemType": "communication",
		"title": "Imams, Islamic Preachers and Public Space in Ouagadougou (Burkina Faso) since the 1990s: Toward New Intergenerational Relationships and a Muslim Public Sphere",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "29 March 2013",
		"dateISO": "2013-03-29",
		"year": 2013,
		"image": "images/communications/University_of_Texas_at_Austin_seal.webp",
		"heroImage": {
			"src": "images/communications/University_of_Texas_at_Austin_seal-hero.webp"
		},
		"conference": "2013 Africa Conference",
		"location": "University of Texas at Austin",
		"country": "United States"
	},
	"imams-islamic-preachers-ouagadougou-2020": {
		"id": "imams-islamic-preachers-ouagadougou-2020",
		"itemType": "publication",
		"title": "Imams, Islamic Preachers, and Public Space in Ouagadougou (Burkina Faso) since the 1990s: Toward New Intergenerational Relationships and a Muslim Public Sphere",
		"authors": [
			"Frédérick Madore"
		],
		"type": "chapter",
		"date": "2020",
		"dateISO": "2020",
		"year": 2020,
		"image": "images/publications/imams-ouagadougou-2020.webp",
		"heroImage": {
			"src": "images/publications/imams-ouagadougou-2020-hero.webp"
		},
		"book": "Perspectives on the Religious Landscape in Africa",
		"publisher": "Carolina Academic Press"
	},
	"interfaith-coexistence-campuses": {
		"id": "interfaith-coexistence-campuses",
		"itemType": "communication",
		"title": "Interfaith coexistence on the campuses of the University of Lomé (Togo) and the University of Abomey-Calavi (Benin) since the 1970s",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "6 June 2023",
		"dateISO": "2023-06-06",
		"year": 2023,
		"image": "images/communications/interfaith-coexistence-campuses.webp",
		"heroImage": {
			"src": "images/communications/interfaith-coexistence-campuses.webp"
		},
		"conference": "Workshop Religion for Peace? Identifying Conditions and Mechanisms of Interfaith Peace",
		"location": "Berlin, German Institute for Global and Area Studies (GIGA)",
		"country": "Germany"
	},
	"introduction-religiosity-university-campuses-2023": {
		"id": "introduction-religiosity-university-campuses-2023",
		"itemType": "publication",
		"title": "Introduction: Religiosity on University Campuses in Africa",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore"
		],
		"type": "chapter",
		"date": "2023",
		"dateISO": "2023",
		"year": 2023,
		"image": "images/publications/religiosity-university-campuses.webp",
		"heroImage": {
			"src": "images/publications/religiosity-university-campuses-hero.webp"
		},
		"book": "Religiosity on University Campuses in Africa: Trends and Experiences",
		"publisher": "LIT Verlag"
	},
	"islam-algorithms-ai": {
		"id": "islam-algorithms-ai",
		"itemType": "communication",
		"title": "Islam, Algorithms and AI",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "18 July 2024",
		"dateISO": "2024-07-18",
		"year": 2024,
		"image": "images/communications/islam-algorithms-ai.webp",
		"heroImage": {
			"src": "images/communications/islam-algorithms-ai-hero.webp"
		},
		"conference": "ZMO Sommerfest",
		"location": "Leibniz-Zentrum Moderner Orient",
		"country": "Germany"
	},
	"islam-burkina-cote-ivoire": {
		"id": "islam-burkina-cote-ivoire",
		"itemType": "communication",
		"title": "L'islam au Burkina Faso et en Côte d'Ivoire: éveil et radicalisation?",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "13 February 2017",
		"dateISO": "2017-02-13",
		"year": 2017,
		"image": "images/communications/islam-burkina-cote-ivoire.webp",
		"heroImage": {
			"src": "images/communications/islam-burkina-cote-ivoire-hero.webp"
		},
		"conference": "76e conférence Archéopat",
		"location": "Université du Québec à Rimouski",
		"country": "Canada"
	},
	"islam-burkina-faso-collection-2021": {
		"id": "islam-burkina-faso-collection-2021",
		"itemType": "publication",
		"title": "La Collection Islam Burkina Faso : promesses et défis des humanités numériques",
		"authors": [
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2021",
		"dateISO": "2021-12-15",
		"year": 2021,
		"image": "images/publications/revue-d-histoire-contemporaine-de-l-afrique.webp",
		"heroImage": {
			"src": "images/publications/revue-d-histoire-contemporaine-de-l-afrique-hero.webp"
		},
		"journal": "Revue d'Histoire Contemporaine de l'Afrique",
		"publisher": "University of Geneva"
	},
	"islam-burkina-faso-collection-omeka-2022": {
		"id": "islam-burkina-faso-collection-omeka-2022",
		"itemType": "communication",
		"title": "Publishing the Islam Burkina Faso Collection with Omeka S",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "8 July 2022",
		"dateISO": "2022-07-08",
		"year": 2022,
		"image": "images/communications/islam-burkina-faso-collection-omeka-2022.webp",
		"heroImage": {
			"src": "images/communications/islam-burkina-faso-collection-omeka-2022-hero.webp"
		},
		"conference": "3rd Annual conference of the Africa Multiple Cluster of Excellence \"Medialities\"",
		"location": "University of Bayreuth",
		"country": "Germany"
	},
	"islam-ivoirien-burkinabe-numerique-2016": {
		"id": "islam-ivoirien-burkinabe-numerique-2016",
		"itemType": "publication",
		"title": "L'islam ivoirien et burkinabé à l'ère du numérique 2.0",
		"authors": [
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2016",
		"dateISO": "2016",
		"year": 2016,
		"image": "images/publications/journal-des-anthropologues.webp",
		"heroImage": {
			"src": "images/publications/journal-des-anthropologues-hero.webp"
		},
		"journal": "Journal des anthropologues",
		"publisher": "Association Française des Anthropologues"
	},
	"islam-medias-senat-burkina-faso-2016": {
		"id": "islam-medias-senat-burkina-faso-2016",
		"itemType": "publication",
		"title": "Islam, médias, mise en place du Sénat et article 37 de la Constitution: changement de paradigme au Burkina Faso (1991–2014)?",
		"authors": [
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2016",
		"dateISO": "2016-03-10",
		"year": 2016,
		"image": "images/publications/canadian-journal-of-african-studies.webp",
		"heroImage": {
			"src": "images/publications/canadian-journal-of-african-studies-hero.webp"
		},
		"journal": "Canadian Journal of African Studies / Revue canadienne des études africaines",
		"publisher": "Taylor & Francis"
	},
	"islam-peripheries-dh-ai-west-africa-central-asia-2026": {
		"id": "islam-peripheries-dh-ai-west-africa-central-asia-2026",
		"itemType": "communication",
		"title": "Islam's \"Peripheries\": Digital Humanities, Algorithmic Analysis, and AI in West Africa and Central Asia",
		"authors": [
			"Aksana Ismailbekova",
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "29 June 2026",
		"dateISO": "2026-06-29",
		"year": 2026,
		"image": "images/communications/islam-peripheries-dh-ai-west-africa-central-asia-2026.webp",
		"heroImage": {
			"src": "images/communications/islam-peripheries-dh-ai-west-africa-central-asia-2026-hero.webp"
		},
		"conference": "Seminar series 'Digital History in/of Central Asia and the South Caucasus'",
		"location": "Friedrich-Alexander-Universität Erlangen-Nürnberg",
		"country": "Germany"
	},
	"islam-peripheries-open-up-2026": {
		"id": "islam-peripheries-open-up-2026",
		"itemType": "communication",
		"title": "Islam's \"Peripheries\": Digital Humanities, Algorithmic Analysis, and AI in West Africa and Central Asia",
		"authors": [
			"Frédérick Madore",
			"Aksana Ismailbekova"
		],
		"type": "conference",
		"date": "4 March 2026",
		"dateISO": "2026-03-04",
		"year": 2026,
		"image": "images/communications/islam-peripheries-open-up-2026.webp",
		"heroImage": {
			"src": "images/communications/islam-peripheries-open-up-2026-hero.webp"
		},
		"conference": "Kick-off 'Open Up'",
		"location": "Xplanatorium Herrenhausen, Hanover",
		"country": "Germany"
	},
	"islam-university-campuses-cote-divoire-2019": {
		"id": "islam-university-campuses-cote-divoire-2019",
		"itemType": "communication",
		"title": "Islam on University Campuses in Côte d'Ivoire since the 1970s: 'Muslim Intellectuals' and Francophone Salafism",
		"authors": [
			"Issouf Binaté",
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "12 June 2019",
		"dateISO": "2019-06-12",
		"year": 2019,
		"image": "images/communications/islam-university-campuses-cote-divoire-2019.webp",
		"heroImage": {
			"src": "images/communications/islam-university-campuses-cote-divoire-2019-hero.webp"
		},
		"conference": "8th European Conference on African Studies (ECAS)",
		"location": "University of Edinburgh",
		"country": "Scotland"
	},
	"islam-university-campuses-cote-divoire-2023": {
		"id": "islam-university-campuses-cote-divoire-2023",
		"itemType": "publication",
		"title": "Islam on University Campuses in Côte d'Ivoire since the 1970s: Muslim Intellectuals and Francophone Salafism",
		"authors": [
			"Frédérick Madore",
			"Issouf Binaté"
		],
		"type": "chapter",
		"date": "2023",
		"dateISO": "2023",
		"year": 2023,
		"image": "images/publications/religiosity-university-campuses.webp",
		"heroImage": {
			"src": "images/publications/religiosity-university-campuses-hero.webp"
		},
		"book": "Religiosity on University Campuses in Africa: Trends and Experiences",
		"publisher": "LIT Verlag"
	},
	"launch-islam-west-africa-collection": {
		"id": "launch-islam-west-africa-collection",
		"itemType": "communication",
		"title": "Launch of the Islam West Africa Collection",
		"authors": [
			"Frédérick Madore"
		],
		"type": "event",
		"date": "9 November 2023",
		"dateISO": "2023-11-09",
		"year": 2023,
		"image": "images/communications/poster-launch-IWAC.webp",
		"heroImage": {
			"src": "images/communications/poster-launch-IWAC-hero.webp"
		},
		"conference": "Launch of the Islam West Africa Collection",
		"location": "Media in Cooperation and Transition (MiCT)",
		"country": "Germany"
	},
	"leaders-muslim-ngos-burkina-faso-2016": {
		"id": "leaders-muslim-ngos-burkina-faso-2016",
		"itemType": "publication",
		"title": "Leaders of National and Transnational Muslim NGOs in Burkina Faso: Diverse Forms and Experiences of Islamic Civic Engagement",
		"authors": [
			"Kathéry Couillard",
			"Frédérick Madore",
			"Muriel Gomez-Perez"
		],
		"type": "chapter",
		"date": "2016",
		"dateISO": "2016",
		"year": 2016,
		"image": "images/publications/muslim-ngos-burkina-faso-2016.avif",
		"heroImage": {
			"src": "images/publications/muslim-ngos-burkina-faso-2016.avif"
		},
		"book": "Faith and Charity: Religion and Humanitarian Assistance in West Africa",
		"publisher": "Pluto Press"
	},
	"lutte-terrorisme-salafisme-benin-togo-2022": {
		"id": "lutte-terrorisme-salafisme-benin-togo-2022",
		"itemType": "publication",
		"title": "Lutte contre le terrorisme et sécuritisation du salafisme au Bénin et au Togo: instrumentalisations diverses d'une « menace étrangère »",
		"authors": [
			"Frédérick Madore"
		],
		"type": "report",
		"date": "2022",
		"dateISO": "2022-10",
		"year": 2022,
		"image": "images/publications/bulletin-franco-paix.webp",
		"heroImage": {
			"src": "images/publications/bulletin-franco-paix-hero.webp"
		},
		"publisher": "Bulletin FrancoPaix"
	},
	"madore-2024-launch-iwac": {
		"id": "madore-2024-launch-iwac",
		"itemType": "publication",
		"title": "Launch Islam West Africa Collection, 9 November 2023, MiCT, Berlin/Online",
		"authors": [
			"Frédérick Madore"
		],
		"type": "bulletin-article",
		"date": "April 2024",
		"dateISO": "2024-04",
		"year": 2024,
		"image": "images/publications/zmo-bulletin-44.webp",
		"heroImage": {
			"src": "images/publications/zmo-bulletin-44-hero.webp"
		},
		"journal": "ZMO Bulletin"
	},
	"madore-2025-perspectives-in-motion": {
		"id": "madore-2025-perspectives-in-motion",
		"itemType": "publication",
		"title": "Perspectives in Motion: Conceptual Fields from the Global South, Workshop, 2-3 December 2024, ZMO",
		"authors": [
			"Frédérick Madore"
		],
		"type": "bulletin-article",
		"date": "April 2025",
		"dateISO": "2025-04",
		"year": 2025,
		"image": "images/publications/zmo-bulletin-46.webp",
		"heroImage": {
			"src": "images/publications/zmo-bulletin-46-hero.webp"
		},
		"journal": "ZMO Bulletin"
	},
	"madore-2026-conversation-coauthorship-dh-ai": {
		"id": "madore-2026-conversation-coauthorship-dh-ai",
		"itemType": "publication",
		"title": "From Conversation to Co-authorship: A Workshop on Digital Humanities and AI in African Studies, 18–20 February 2026, Herrenhausen, Hanover",
		"authors": [
			"Frédérick Madore"
		],
		"type": "bulletin-article",
		"date": "May 2026",
		"dateISO": "2026-05",
		"year": 2026,
		"image": "images/publications/zmo-bulletin-48-conversation.webp",
		"heroImage": {
			"src": "images/publications/zmo-bulletin-48-conversation-hero.webp"
		},
		"journal": "ZMO Bulletin"
	},
	"madore-2026-decentering-knowledge": {
		"id": "madore-2026-decentering-knowledge",
		"itemType": "publication",
		"title": "Decentering Knowledge: Concepts, Conceptualizations, Translations, 13–14 October 2025, ZMO",
		"authors": [
			"Frédérick Madore"
		],
		"type": "bulletin-article",
		"date": "May 2026",
		"dateISO": "2026-05",
		"year": 2026,
		"image": "images/publications/zmo-bulletin-48-decentering.webp",
		"heroImage": {
			"src": "images/publications/zmo-bulletin-48-decentering-hero.webp"
		},
		"journal": "ZMO Bulletin"
	},
	"madore-2026-iwac-private-database-public-resource": {
		"id": "madore-2026-iwac-private-database-public-resource",
		"itemType": "publication",
		"title": "From Private Database to Public Resource to a Testing Ground for AI Methods: The Islam West Africa Collection (IWAC)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "bulletin-article",
		"date": "2026",
		"dateISO": "2026",
		"year": 2026,
		"image": "images/publications/zmo-jahrbuch.webp",
		"heroImage": {
			"src": "images/publications/zmo-jahrbuch-hero.webp"
		},
		"journal": "Shared World - People, Faiths, Ideas, Practices: New Directions in Research 2023-2025, Jahrbuch",
		"publisher": "Leibniz-Zentrum Moderner Orient"
	},
	"madore-islam-politique-ouagadougou-2013": {
		"id": "madore-islam-politique-ouagadougou-2013",
		"itemType": "publication",
		"title": "Islam, politique et sphère publique à Ouagadougou (Burkina Faso) : différentes cohortes d'imams et de prêcheurs entre visibilité nouvelle et reconfiguration des rapports intergénérationnels (1960-2012)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "masters-thesis",
		"date": "2013",
		"dateISO": "2013",
		"year": 2013,
		"image": "images/publications/islam-politique-ouagadougou-2013.webp",
		"heroImage": {
			"src": "images/publications/islam-politique-ouagadougou-2013-hero.webp"
		}
	},
	"mediatisation-islam-ouagadougou-2013": {
		"id": "mediatisation-islam-ouagadougou-2013",
		"itemType": "communication",
		"title": "La médiatisation de l'islam à Ouagadougou depuis 1991: entre normalisation des discours et nouvelle agency des musulmans",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "3 May 2013",
		"dateISO": "2013-05-03",
		"year": 2013,
		"image": "images/communications/CAAS-logo.webp",
		"heroImage": {
			"src": "images/communications/CAAS-logo-hero.webp"
		},
		"conference": "43rd Annual Canadian Association of African Studies Conference (CAAS)",
		"location": "University of Ottawa",
		"country": "Canada"
	},
	"militantisme-bissap-feminisme-islamique-2018": {
		"id": "militantisme-bissap-feminisme-islamique-2018",
		"itemType": "communication",
		"title": "'Militantisme bissap', féminisme islamique et entrepreneuriat religieux en Côte d'Ivoire: Aminata Kane Koné, une figure de la réussite",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "8 September 2018",
		"dateISO": "2018-09-08",
		"year": 2018,
		"conference": "Workshop Entrepreneuriat religieux et figures de la réussite en Afrique subsaharienne: terrains et concepts",
		"location": "Université Laval",
		"country": "Canada"
	},
	"militantisme-islamique-campus-lome": {
		"id": "militantisme-islamique-campus-lome",
		"itemType": "communication",
		"title": "Militantisme islamique sur le campus de l'Université de Lomé (Togo) depuis les années 1980: être musulman en contexte minoritaire, laïc et (semi-)autoritaire",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "22 February 2022",
		"dateISO": "2022-02-22",
		"year": 2022,
		"image": "images/communications/militantisme-islamique-campus-lome.webp",
		"heroImage": {
			"src": "images/communications/militantisme-islamique-campus-lome-hero.webp"
		},
		"conference": "Chaire de recherche sur l'islam contemporain en Afrique de l'Ouest",
		"location": "Université du Québec à Montréal",
		"country": "Canada"
	},
	"militantisme-islamique-feminin-burkina-2019": {
		"id": "militantisme-islamique-feminin-burkina-2019",
		"itemType": "communication",
		"title": "Militantisme islamique féminin au Burkina Faso: des processus sinueux d'émancipation religieuse",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "27 August 2019",
		"dateISO": "2019-08-27",
		"year": 2019,
		"image": "images/communications/militantisme-islamique-feminin-burkina-2019.webp",
		"heroImage": {
			"src": "images/communications/militantisme-islamique-feminin-burkina-2019-hero.webp"
		},
		"conference": "IIe Congrès international de l'Institut du Genre",
		"location": "University of Angers",
		"country": "France"
	},
	"militantisme-religieux-campus-benin-togo-2025": {
		"id": "militantisme-religieux-campus-benin-togo-2025",
		"itemType": "communication",
		"title": "Militantisme religieux sur les campus universitaires : le cas du Bénin et du Togo",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "28 May 2025",
		"dateISO": "2025-05-28",
		"year": 2025,
		"image": "images/communications/EHESS-2025.webp",
		"heroImage": {
			"src": "images/communications/EHESS-2025-hero.webp"
		},
		"conference": "Séminaire 'Histoire et anthropologie comparées du fait religieux en Afrique' animé par Marie Miran",
		"location": "Humathèque Condorcet",
		"country": "France"
	},
	"muslim-feminist-media-cote-divoire-2020": {
		"id": "muslim-feminist-media-cote-divoire-2020",
		"itemType": "publication",
		"title": "Muslim Feminist, Media Sensation, and Religious Entrepreneur: Aminata Kane Koné as a Figure of Success in Côte d'Ivoire",
		"authors": [
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2020",
		"dateISO": "2020",
		"year": 2020,
		"image": "images/publications/africa-today.webp",
		"heroImage": {
			"src": "images/publications/africa-today-hero.webp"
		},
		"journal": "Africa Today",
		"publisher": "Indiana University Press"
	},
	"muslim-intellectuals-francophone-salafis": {
		"id": "muslim-intellectuals-francophone-salafis",
		"itemType": "communication",
		"title": "'Muslim Intellectuals' and 'Francophone Salafis' in West Africa: New Religious Elites?",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "1 October 2020",
		"dateISO": "2020-10-01",
		"year": 2020,
		"image": "images/communications/muslim-intellectuals-francophone-salafis.webp",
		"heroImage": {
			"src": "images/communications/muslim-intellectuals-francophone-salafis-hero.webp"
		},
		"conference": "Hamilton Lugar School of Global and International Studies",
		"location": "Indiana University Bloomington",
		"country": "United States"
	},
	"muslim-minorities-africa-1": {
		"id": "muslim-minorities-africa-1",
		"itemType": "publication",
		"title": "Muslim Minorities in Africa, Part 1",
		"authors": [
			"Frédérick Madore",
			"Dorothea Schulz"
		],
		"type": "special-issue",
		"date": "2021",
		"dateISO": "2021-07",
		"year": 2021,
		"image": "images/publications/muslim-minorities-africa.webp",
		"heroImage": {
			"src": "images/publications/muslim-minorities-africa-hero.webp"
		},
		"journal": "Islamic Africa",
		"publisher": "Brill"
	},
	"muslim-minorities-africa-2": {
		"id": "muslim-minorities-africa-2",
		"itemType": "publication",
		"title": "Muslim Minorities in Africa, Part 2",
		"authors": [
			"Frédérick Madore",
			"Dorothea Schulz"
		],
		"type": "special-issue",
		"date": "2022",
		"dateISO": "2022-01",
		"year": 2022,
		"image": "images/publications/muslim-minorities-africa.webp",
		"heroImage": {
			"src": "images/publications/muslim-minorities-africa-hero.webp"
		},
		"journal": "Islamic Africa",
		"publisher": "Brill"
	},
	"muslim-minorities-africa-2019": {
		"id": "muslim-minorities-africa-2019",
		"itemType": "communication",
		"title": "Muslim Minorities in Africa",
		"authors": [
			"Frédérick Madore"
		],
		"type": "panel",
		"date": "21 November 2019",
		"dateISO": "2019-11-21",
		"year": 2019,
		"image": "images/communications/ASA-Logo.svg",
		"conference": "62nd Meeting of the African Studies Association (ASA)",
		"location": "Boston",
		"country": "United States"
	},
	"muslim-women-burkina-faso-2016": {
		"id": "muslim-women-burkina-faso-2016",
		"itemType": "publication",
		"title": "Muslim Women in Burkina Faso since the 1970s: Toward Recognition as Figures of Religious Authority?",
		"authors": [
			"Frédérick Madore",
			"Muriel Gomez-Perez"
		],
		"type": "article",
		"date": "2016",
		"dateISO": "2016-11-02",
		"year": 2016,
		"image": "images/publications/muslim-minorities-africa.webp",
		"heroImage": {
			"src": "images/publications/muslim-minorities-africa-hero.webp"
		},
		"journal": "Islamic Africa",
		"publisher": "Brill"
	},
	"nouveau-dynamisme-salafisme-cote-divoire-2017": {
		"id": "nouveau-dynamisme-salafisme-cote-divoire-2017",
		"itemType": "communication",
		"title": "Le nouveau dynamisme du salafisme en Côte d'Ivoire: vers une radicalisation de l'islam ivoirien?",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "3 August 2017",
		"dateISO": "2017-08-03",
		"year": 2017,
		"image": "images/communications/MANSA-logo.webp",
		"heroImage": {
			"src": "images/communications/MANSA-logo-hero.webp"
		},
		"conference": "10th International Conference of the Mande Studies Association (MANSA)",
		"location": "International University of Grand-Bassam",
		"country": "Côte d'Ivoire"
	},
	"plan-brouillon-structurer-idees-2021": {
		"id": "plan-brouillon-structurer-idees-2021",
		"itemType": "publication",
		"title": "Du plan au brouillon : l'essentiel pour structurer ses idées et éviter le syndrome de la page blanche",
		"authors": [
			"Frédérick Madore",
			"Andrée-Ann Brassard"
		],
		"type": "chapter",
		"date": "2021",
		"dateISO": "2021",
		"year": 2021,
		"image": "images/publications/plan-brouillon-2021.webp",
		"heroImage": {
			"src": "images/publications/plan-brouillon-2021-hero.webp"
		},
		"book": "Guide décolonisé et pluriversel de formation à la recherche en sciences sociales et humaines",
		"publisher": "Éditions science et bien commun"
	},
	"point-de-passage-frontieres-religieuses": {
		"id": "point-de-passage-frontieres-religieuses",
		"itemType": "communication",
		"title": "Point de passage et frontières religieuses",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "3 June 2022",
		"dateISO": "2022-06-03",
		"year": 2022,
		"image": "images/communications/point-de-passage-frontieres-religieuses.webp",
		"heroImage": {
			"src": "images/communications/point-de-passage-frontieres-religieuses-hero.webp"
		},
		"conference": "Workshop Point de passage et frontières religieuses",
		"location": "Laboratoire d'Etudes et de Recherches sur les Dynamiques Sociales et le Développement Local (LASDEL)",
		"country": "Niger"
	},
	"political-mobilizations-burkina-faso": {
		"id": "political-mobilizations-burkina-faso",
		"itemType": "communication",
		"title": "Political mobilizations in Burkina Faso",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "27 November 2020",
		"dateISO": "2020-11-27",
		"year": 2020,
		"conference": "Workshop Political mobilizations in Burkina Faso",
		"location": "University of Ottawa",
		"country": "Canada"
	},
	"precheurs-musulmans-burkina-faso-2013": {
		"id": "precheurs-musulmans-burkina-faso-2013",
		"itemType": "publication",
		"title": "Prêcheurs(ses) musulmans(es) et stratégies de communication au Burkina Faso depuis 1990. Des processus différentiés de conversion interne",
		"authors": [
			"Muriel Gomez-Perez",
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2013",
		"dateISO": "2013",
		"year": 2013,
		"image": "images/publications/Theologiques.webp",
		"heroImage": {
			"src": "images/publications/Theologiques-hero.webp"
		},
		"journal": "Théologiques",
		"publisher": "Institut d’études religieuses de l’Université de Montréal"
	},
	"precheurs-precheuses-burkina-faso-2013": {
		"id": "precheurs-precheuses-burkina-faso-2013",
		"itemType": "communication",
		"title": "Prêcheurs et prêcheuses au Burkina Faso: regards croisés sur leurs stratégies de communication religieuse depuis 1990",
		"authors": [
			"Muriel Gomez-Perez",
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "7 May 2013",
		"dateISO": "2013-05-07",
		"year": 2013,
		"image": "images/communications/acfas_81e.webp",
		"conference": "81e Congrès de l'Association Francophone pour le Savoir (Acfas)",
		"location": "Université Laval",
		"country": "Canada"
	},
	"presentation-discussion-religious-activism-campuses-ciram-2025": {
		"id": "presentation-discussion-religious-activism-campuses-ciram-2025",
		"itemType": "communication",
		"title": "Présentation-discussion de l'ouvrage Religious Activism on Campuses in Togo and Benin",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "6 November 2025",
		"dateISO": "2025-11-06",
		"year": 2025,
		"image": "images/communications/ciram-2025.webp",
		"heroImage": {
			"src": "images/communications/ciram-2025-hero.webp"
		},
		"conference": "Conférences midi du CIRAM",
		"location": "Université Laval",
		"country": "Canada"
	},
	"public-islam-cote-ivoire-burkina-faso": {
		"id": "public-islam-cote-ivoire-burkina-faso",
		"itemType": "communication",
		"title": "Public Islam in Côte d'Ivoire and Burkina Faso: a comparative overview of the use of media by Muslims since the 1970s",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "24 January 2020",
		"dateISO": "2020-01-24",
		"year": 2020,
		"image": "images/communications/public-islam-cote-ivoire-burkina-faso.webp",
		"heroImage": {
			"src": "images/communications/public-islam-cote-ivoire-burkina-faso-hero.webp"
		},
		"conference": "Workshop Media and 'Public' Islam in Africa & Elsewhere",
		"location": "University of Florida",
		"country": "United States"
	},
	"publishing-islam-burkina-faso-collection-2022": {
		"id": "publishing-islam-burkina-faso-collection-2022",
		"itemType": "communication",
		"title": "Publishing the Islam Burkina Faso Collection: Collaboration for Digital Scholarship",
		"authors": [
			"Frédérick Madore",
			"Perry Collins"
		],
		"type": "conference",
		"date": "15 September 2022",
		"dateISO": "2022-09-15",
		"year": 2022,
		"image": "images/communications/publishing-islam-burkina-faso-collection-2022.webp",
		"heroImage": {
			"src": "images/communications/publishing-islam-burkina-faso-collection-2022-hero.webp"
		},
		"conference": "34th Deutscher Orientalistentag (DOT)",
		"location": "Free University of Berlin",
		"country": "Germany"
	},
	"questions-islam-afrique-ouest-2025": {
		"id": "questions-islam-afrique-ouest-2025",
		"itemType": "communication",
		"title": "Questions d'islam en Afrique de l'Ouest. Les enjeux et défis de la recherche avec les archives physiques et numériques",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "12 May 2025",
		"dateISO": "2025-05-12",
		"year": 2025,
		"image": "images/communications/EHESS-2025.webp",
		"heroImage": {
			"src": "images/communications/EHESS-2025-hero.webp"
		},
		"conference": "Séminaire de formation à la recherche en Afrique (SéFRA) animé par Fabienne Samson",
		"location": "École des hautes études en sciences sociales (EHESS)",
		"country": "France"
	},
	"recherche-documentaire-zotero": {
		"id": "recherche-documentaire-zotero",
		"itemType": "communication",
		"title": "La recherche documentaire en libre accès et la gestion de références bibliographiques avec Zotero",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "7 June 2019",
		"dateISO": "2019-06-07",
		"year": 2019,
		"image": "images/communications/recherche-documentaire-zotero.webp",
		"heroImage": {
			"src": "images/communications/recherche-documentaire-zotero-hero.webp"
		},
		"conference": "Université Alassane Ouattara",
		"location": "Université Alassane Ouattara",
		"country": "Côte d'Ivoire"
	},
	"reconfiguring-archive-amira-2026": {
		"id": "reconfiguring-archive-amira-2026",
		"itemType": "communication",
		"title": "Reconfiguring the Archive: Relationality and Discovery in the Africa Multiple Interactive Research Atlas (AMIRA)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "1 July 2026",
		"dateISO": "2026-07-01",
		"year": 2026,
		"image": "images/communications/reconfiguring-archive-amira-2026.webp",
		"heroImage": {
			"src": "images/communications/reconfiguring-archive-amira-2026.webp"
		},
		"conference": "Reimagining the Archive in the Post-Truth Era: An International Interdisciplinary Conference",
		"location": "Cory Library for Historical Research, Makhanda",
		"country": "South Africa"
	},
	"religieux-internet-ntic-burkina-faso-2019": {
		"id": "religieux-internet-ntic-burkina-faso-2019",
		"itemType": "publication",
		"title": "Le religieux sur Internet et dans les NTIC au Burkina Faso",
		"authors": [
			"Frédérick Madore",
			"Louis Audet Gosselin"
		],
		"type": "chapter",
		"date": "2019",
		"dateISO": "2019-06",
		"year": 2019,
		"image": "images/publications/religieux-internet-burkina-faso-2019.webp",
		"heroImage": {
			"src": "images/publications/religieux-internet-burkina-faso-2019-hero.webp"
		},
		"book": "Rencontres religieuses et dynamiques sociales au Burkina Faso",
		"publisher": "Amalion"
	},
	"religion-internet-burkina-faso-2024": {
		"id": "religion-internet-burkina-faso-2024",
		"itemType": "publication",
		"title": "Religion on the Internet and New Information and Communication Technologies in Burkina Faso",
		"authors": [
			"Frédérick Madore",
			"Louis Audet Gosselin"
		],
		"type": "chapter",
		"date": "2024",
		"dateISO": "2024",
		"year": 2024,
		"image": "images/publications/religion-internet-burkina-faso-2024.webp",
		"heroImage": {
			"src": "images/publications/religion-internet-burkina-faso-2024-hero.webp"
		},
		"book": "Religious Encounters and Social Dynamics in Burkina Faso",
		"publisher": "Amalion"
	},
	"religions-numeriques-afrique-2018": {
		"id": "religions-numeriques-afrique-2018",
		"itemType": "publication",
		"title": "Religions numériques en Afrique",
		"authors": [
			"Vincent Hiribarren",
			"Pamela Millet-Mouity",
			"Frédérick Madore"
		],
		"type": "blogpost",
		"date": "2018",
		"dateISO": "2018-09-19",
		"year": 2018,
		"image": "images/publications/religions-numeriques-afrique-2018.webp",
		"heroImage": {
			"src": "images/publications/religions-numeriques-afrique-2018-hero.webp"
		},
		"publisher": "Africa4. Regards croisés sur l'Afrique"
	},
	"religiosity-university-campuses": {
		"id": "religiosity-university-campuses",
		"itemType": "publication",
		"title": "Religiosity on University Campuses in Africa: Trends and Experiences",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore"
		],
		"type": "book",
		"date": "2023",
		"dateISO": "2023-08-29",
		"year": 2023,
		"image": "images/publications/religiosity-university-campuses.webp",
		"heroImage": {
			"src": "images/publications/religiosity-university-campuses-hero.webp"
		},
		"publisher": "LIT Verlag"
	},
	"religious-activism-campuses": {
		"id": "religious-activism-campuses",
		"itemType": "publication",
		"title": "Religious Activism on Campuses in Togo and Benin: Christian and Muslim Students Navigating Authoritarianism and Laïcité, 1970–2023",
		"authors": [
			"Frédérick Madore"
		],
		"type": "book",
		"date": "2025",
		"dateISO": "2025-03-31",
		"year": 2025,
		"image": "images/publications/religious-activism-campuses.webp",
		"heroImage": {
			"src": "images/publications/religious-activism-campuses-hero.webp"
		},
		"publisher": "De Gruyter"
	},
	"religious-actors-digital-era-2017": {
		"id": "religious-actors-digital-era-2017",
		"itemType": "publication",
		"title": "Pour de nouvelles études sur les acteurs religieux africains à l'ère du numérique",
		"authors": [
			"Pamela Millet-Mouity",
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2017",
		"dateISO": "2017",
		"year": 2017,
		"image": "images/publications/acteurs-religieux-numerique.webp",
		"heroImage": {
			"src": "images/publications/acteurs-religieux-numerique-hero.webp"
		},
		"journal": "Émulations",
		"publisher": "Presses universitaires de Louvain"
	},
	"rencontre-chretiens-musulmans-2025": {
		"id": "rencontre-chretiens-musulmans-2025",
		"itemType": "communication",
		"title": "Rencontre entre chrétiens et musulmans: au-delà du binaire coexistence pacifique/conflits religieux",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "21 May 2025",
		"dateISO": "2025-05-21",
		"year": 2025,
		"image": "images/communications/EHESS-2025.webp",
		"heroImage": {
			"src": "images/communications/EHESS-2025-hero.webp"
		},
		"conference": "Séminaire 'Histoire et anthropologie comparées du fait religieux en Afrique' animé par Marie Miran",
		"location": "Humathèque Condorcet",
		"country": "France"
	},
	"repenser-categorisation-religieuse-benin": {
		"id": "repenser-categorisation-religieuse-benin",
		"itemType": "communication",
		"title": "Repenser la catégorisation religieuse à partir du Bénin, terre du vodun",
		"authors": [
			"Frédérick Madore",
			"Fiacre Anato"
		],
		"type": "workshop",
		"date": "5 December 2024",
		"dateISO": "2024-12-05",
		"year": 2024,
		"image": "images/communications/paris-cite.webp",
		"heroImage": {
			"src": "images/communications/paris-cite-hero.webp"
		},
		"conference": "Workshop L'Afrique des religions à l'épreuve des chiffres et des catégorisations",
		"location": "Université Paris Cité",
		"country": "France"
	},
	"repenser-categorisation-religieuse-benin-2026": {
		"id": "repenser-categorisation-religieuse-benin-2026",
		"itemType": "publication",
		"title": "Repenser la catégorisation religieuse à partir du Bénin, terre du Vodun",
		"authors": [
			"Frédérick Madore",
			"Codjo Fiacre Anato"
		],
		"type": "chapter",
		"date": "2026",
		"dateISO": "2026-04-02",
		"year": 2026,
		"image": "images/publications/repenser-categorisation-religieuse-benin.webp",
		"heroImage": {
			"src": "images/publications/repenser-categorisation-religieuse-benin.webp"
		},
		"book": "L'Afrique des religions à l'épreuve des chiffres et des catégorisations",
		"publisher": "Maisonneuve & Larose-Hémisphères éditions"
	},
	"representations-islam-muslims-togo": {
		"id": "representations-islam-muslims-togo",
		"itemType": "communication",
		"title": "Representations of Islam and Muslims in Togo's State-Owned Newspapers Since the 1960s: From Loyal Religious Minority to Potential Threat",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "9 October 2020",
		"dateISO": "2020-10-09",
		"year": 2020,
		"image": "images/communications/representations-islam-muslims-togo.webp",
		"heroImage": {
			"src": "images/communications/representations-islam-muslims-togo-hero.webp"
		},
		"conference": "Workshop Islam, Media, and Popular Culture in Africa and Elsewhere",
		"location": "University of Florida",
		"country": "United States"
	},
	"retour-note-synthese-dh-ia-reaf-2026": {
		"id": "retour-note-synthese-dh-ia-reaf-2026",
		"itemType": "communication",
		"title": "Retour sur une note de synthèse analysant la relation entre Humanités Numériques, l’IA et les Études Africaines (Hanovre, février 2026)",
		"authors": [
			"Vincent Hiribarren",
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "30 June 2026",
		"dateISO": "2026-06-30",
		"year": 2026,
		"image": "images/communications/reaf-2026.webp",
		"heroImage": {
			"src": "images/communications/reaf-2026-hero.webp"
		},
		"conference": "9èmes Rencontres des études africaines en France (REAF)",
		"location": "Paris",
		"country": "France"
	},
	"rivalites-collaborations-islamiques-cote-ivoire-burkina-faso-2018": {
		"id": "rivalites-collaborations-islamiques-cote-ivoire-burkina-faso-2018",
		"itemType": "publication",
		"title": "Rivalités et collaborations entre ainés et cadets sociaux dans les milieux associatifs islamiques en Côte d'Ivoire et au Burkina Faso (1970-2017)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "phd-dissertation",
		"date": "2018",
		"dateISO": "2018",
		"year": 2018,
		"image": "images/publications/dissertation-cote-ivoire-burkina-faso-2018.webp",
		"heroImage": {
			"src": "images/publications/dissertation-cote-ivoire-burkina-faso-2018-hero.webp"
		}
	},
	"rue-islam-associatif-enjeux-citoyens-2014": {
		"id": "rue-islam-associatif-enjeux-citoyens-2014",
		"itemType": "communication",
		"title": "Rue, islam associatif et enjeux citoyens: retour sur des orientations récentes au Sénégal, au Burkina Faso et en Côte d'Ivoire",
		"authors": [
			"Muriel Gomez-Perez",
			"Frédérick Madore",
			"Mathias Boukary Savadogo"
		],
		"type": "conference",
		"date": "29 October 2014",
		"dateISO": "2014-10-29",
		"year": 2014,
		"image": "images/communications/Gaston_Berger_University_logo.webp",
		"heroImage": {
			"src": "images/communications/Gaston_Berger_University_logo-hero.webp"
		},
		"conference": "International Conference Le clos et l'ouvert. Acteurs religieux, acteurs sociaux et usages de la rue (Europe, Afrique, Asie, Amériques)",
		"location": "Gaston Berger University",
		"country": "Senegal"
	},
	"salafism-cote-divoire-2016": {
		"id": "salafism-cote-divoire-2016",
		"itemType": "publication",
		"title": "The New Vitality of Salafism in Côte d'Ivoire: Toward a Radicalization of Ivoirian Islam?",
		"authors": [
			"Frédérick Madore"
		],
		"type": "article",
		"date": "2016",
		"dateISO": "2016-08-04",
		"year": 2016,
		"image": "images/publications/journal-of-religion-in-africa.webp",
		"heroImage": {
			"src": "images/publications/journal-of-religion-in-africa-hero.webp"
		},
		"journal": "Journal of Religion in Africa",
		"publisher": "Brill"
	},
	"salafism-cote-ivoire-mande-2017": {
		"id": "salafism-cote-ivoire-mande-2017",
		"itemType": "publication",
		"title": "Le nouveau dynamisme du salafisme en Côte d'Ivoire: vers une radicalisation de l'islam ivoirien?",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference-proceedings",
		"date": "2017",
		"dateISO": "2017",
		"year": 2017,
		"image": "images/publications/salafisme-cote-ivoire-2017.webp",
		"heroImage": {
			"src": "images/publications/salafisme-cote-ivoire-2017-hero.webp"
		}
	},
	"salafisme-pentecotisme-campus-benin-togo": {
		"id": "salafisme-pentecotisme-campus-benin-togo",
		"itemType": "communication",
		"title": "Salafisme et pentecôtisme sur les campus au Bénin et au Togo: la laïcité à l'université face à l'activisme religieux",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "8 April 2021",
		"dateISO": "2021-04-08",
		"year": 2021,
		"image": "images/communications/salafisme-pentecotisme-campus-benin-togo.webp",
		"heroImage": {
			"src": "images/communications/salafisme-pentecotisme-campus-benin-togo-hero.webp"
		},
		"conference": "Conférences midi du CIRAM",
		"location": "Université Laval",
		"country": "Canada"
	},
	"salafisme-securitisation-benin-togo-2022": {
		"id": "salafisme-securitisation-benin-togo-2022",
		"itemType": "communication",
		"title": "Salafisme et sécuritisation de l'islam au Bénin et au Togo: instrumentalisations diverses d'une 'menace étrangère'",
		"authors": [
			"Frédérick Madore"
		],
		"type": "conference",
		"date": "2 June 2022",
		"dateISO": "2022-06-02",
		"year": 2022,
		"image": "images/communications/salafisme-securitisation-benin-togo-2022.webp",
		"heroImage": {
			"src": "images/communications/salafisme-securitisation-benin-togo-2022-hero.webp"
		},
		"conference": "Islamist Protest, Terrorism and (In)Security in Africa Conference",
		"location": "University of Maroua",
		"country": "Cameroon"
	},
	"sphere-publique-musulmane": {
		"id": "sphere-publique-musulmane",
		"itemType": "publication",
		"title": "La construction d'une sphère publique musulmane en Afrique de l'Ouest",
		"authors": [
			"Frédérick Madore"
		],
		"type": "book",
		"date": "2016",
		"dateISO": "2016-01-22",
		"year": 2016,
		"image": "images/publications/sphere-publique-musulmane.webp",
		"heroImage": {
			"src": "images/publications/sphere-publique-musulmane-hero.webp"
		},
		"publisher": "Presses de l'Université Laval/Hermann"
	},
	"stias-dh-ai-african-studies-workshop-2026": {
		"id": "stias-dh-ai-african-studies-workshop-2026",
		"itemType": "communication",
		"title": "Digital Humanities and Artificial Intelligence in African Studies: Towards Sustainable and Equitable Practices",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren",
			"Emmanuel Ngue Um",
			"Menno van Zaanen"
		],
		"type": "event",
		"date": "21-24 September 2026",
		"dateISO": "2026-09-21",
		"year": 2026,
		"image": "images/communications/point-sud-logo.svg",
		"conference": "Digital Humanities and Artificial Intelligence in African Studies: Towards Sustainable and Equitable Practices",
		"location": "Stellenbosch Institute for Advanced Study (STIAS), Stellenbosch",
		"country": "South Africa"
	},
	"three-questions-madore-2022": {
		"id": "three-questions-madore-2022",
		"itemType": "publication",
		"title": "Three Questions to Dr. Frédérick Madore",
		"authors": [
			"Rand El Zein",
			"Frédérick Madore"
		],
		"type": "blogpost",
		"date": "2022",
		"dateISO": "2022-04-07",
		"year": 2022,
		"image": "images/publications/three-questions-madore-2022.webp",
		"heroImage": {
			"src": "images/publications/three-questions-madore-2022-hero.webp"
		},
		"publisher": "Remoboko blog"
	},
	"tracing-islamic-knowledge-production": {
		"id": "tracing-islamic-knowledge-production",
		"itemType": "communication",
		"title": "Tracing Islamic Knowledge Production in Francophone West African Newspapers (1990-Present)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "2 December 2024",
		"dateISO": "2024-12-02",
		"year": 2024,
		"image": "images/communications/perspectives-in-motion.webp",
		"heroImage": {
			"src": "images/communications/perspectives-in-motion-hero.webp"
		},
		"conference": "Workshop Perspectives in Motion: Conceptual Fields from the Global South",
		"location": "Leibniz-Zentrum Moderner Orient",
		"country": "Germany"
	},
	"union-islamique-benin-elections": {
		"id": "union-islamique-benin-elections",
		"itemType": "communication",
		"title": "L'Union Islamique du Bénin et les élections législatives: comment comprendre la crise interne",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "28 May 2019",
		"dateISO": "2019-05-28",
		"year": 2019,
		"image": "images/communications/union-islamique-benin-elections.webp",
		"heroImage": {
			"src": "images/communications/union-islamique-benin-elections-hero.webp"
		},
		"conference": "Université d'Abomey-Calavi",
		"location": "Université d'Abomey-Calavi",
		"country": "Benin"
	},
	"university-campuses-africa-beyond": {
		"id": "university-campuses-africa-beyond",
		"itemType": "communication",
		"title": "University Campuses in Africa and Beyond: Training Grounds, Moral Spaces and Political Arenas",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore"
		],
		"type": "event",
		"date": "6-8 September 2023",
		"dateISO": "2023-09-06",
		"year": 2023,
		"image": "images/communications/REMOBOKO-final-conference.webp",
		"conference": "University Campuses in Africa and Beyond",
		"location": "Leibniz-Zentrum Moderner Orient",
		"country": "Germany"
	},
	"uppsala-university-2025": {
		"id": "uppsala-university-2025",
		"itemType": "communication",
		"title": "Building AI Pipelines for African Digital Collections: Lessons from the Islam West Africa Collection",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "5 December 2025",
		"dateISO": "2025-12-05",
		"year": 2025,
		"image": "images/communications/ALMEDA-logo.webp",
		"heroImage": {
			"src": "images/communications/ALMEDA-logo-hero.webp"
		},
		"conference": "Work talk ALMEDA project",
		"location": "Uppsala University",
		"country": "Sweden"
	},
	"volkswagenstiftung-dh-ai-african-studies-workshop-2026": {
		"id": "volkswagenstiftung-dh-ai-african-studies-workshop-2026",
		"itemType": "communication",
		"title": "Charting New Territory: Digital Humanities and AI in African Studies",
		"authors": [
			"Frédérick Madore",
			"Vincent Hiribarren"
		],
		"type": "event",
		"date": "18-20 February 2026",
		"dateISO": "2026-02-18",
		"year": 2026,
		"image": "images/communications/VWST-logo.webp",
		"conference": "Charting New Territory: Digital Humanities and AI in African Studies",
		"location": "Xplanatorium Herrenhausen, Hanover",
		"country": "Germany"
	},
	"when-ai-meets-the-archive-2025": {
		"id": "when-ai-meets-the-archive-2025",
		"itemType": "communication",
		"title": "When AI Meets the Archive: Transforming the Islam West Africa Collection with Large Language Models",
		"authors": [
			"Frédérick Madore"
		],
		"type": "lecture",
		"date": "20 August 2025",
		"dateISO": "2025-08-20",
		"year": 2025,
		"image": "images/communications/SADILAR.webp",
		"heroImage": {
			"src": "images/communications/SADILAR-hero.webp"
		},
		"conference": "SADiLaR Digital Humanities colloquia",
		"location": "North-West University",
		"country": "South Africa"
	},
	"workshop-religion-in-higher-educational-institutions-2021": {
		"id": "workshop-religion-in-higher-educational-institutions-2021",
		"itemType": "communication",
		"title": "Workshop “Religion in Higher Educational Institutions in Africa and Beyond: (Re)Conversion, Power, and Authority from a Comparative Perspective”",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore",
			"Vincent Favier",
			"Mahamadou Bello Adamou",
			"Adéjoké Rafiat Adétòrò"
		],
		"type": "event",
		"date": "16-17 November 2021",
		"dateISO": "2021-11-16",
		"year": 2021,
		"image": "images/communications/workshop-religion-in-higher-educational-institutions-2021.webp",
		"heroImage": {
			"src": "images/communications/workshop-religion-in-higher-educational-institutions-2021-hero.webp"
		},
		"conference": "Religion in Higher Educational Institutions in Africa and Beyond: (Re)Conversion, Power, and Authority from a Comparative Perspective",
		"location": "Leibniz-Zentrum Moderner Orient",
		"country": "Germany"
	},
	"workshop-religions-on-campus-2022": {
		"id": "workshop-religions-on-campus-2022",
		"itemType": "communication",
		"title": "Workshop “Religions on Campus: Coexisting Traditions, Reformulating the Secular and Life Projects”",
		"authors": [
			"Abdoulaye Sounaye",
			"Frédérick Madore",
			"Vincent Favier",
			"Mahamadou Bello Adamou",
			"Rakiya El Matine"
		],
		"type": "event",
		"date": "31 October - 4 November 2022",
		"dateISO": "2022-10-31",
		"year": 2022,
		"image": "images/communications/workshop-religions-on-campus-2022.webp",
		"heroImage": {
			"src": "images/communications/workshop-religions-on-campus-2022-hero.webp"
		},
		"conference": "Religions on Campus: Coexisting Traditions, Reformulating the Secular and Life Projects",
		"location": "Laboratoire d'Etudes et de Recherches sur les Dynamiques Sociales et le Développement Local (LASDEL)",
		"country": "Niger"
	},
	"young-muslims-civic-engagement-burkina": {
		"id": "young-muslims-civic-engagement-burkina",
		"itemType": "communication",
		"title": "'Plus rien ne sera jamais comme avant'? Young Muslims' new forms of civic engagement in Burkina Faso (2014-2017)",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "19 October 2018",
		"dateISO": "2018-10-19",
		"year": 2018,
		"image": "images/communications/young-muslims-civic-engagement-burkina.webp",
		"heroImage": {
			"src": "images/communications/young-muslims-civic-engagement-burkina-hero.webp"
		},
		"conference": "Workshop Muslim Youth and Lived Islam in Africa & Beyond",
		"location": "University of Florida",
		"country": "United States"
	},
	"yovo-historian-benin-togo": {
		"id": "yovo-historian-benin-togo",
		"itemType": "communication",
		"title": "A 'Yovo' Historian in Benin and Togo: Conducting Fieldwork in Times of Pandemic and Fears of Jihadism Spreading",
		"authors": [
			"Frédérick Madore"
		],
		"type": "workshop",
		"date": "14 June 2022",
		"dateISO": "2022-06-14",
		"year": 2022,
		"image": "images/communications/yovo-historian-benin-togo.webp",
		"heroImage": {
			"src": "images/communications/yovo-historian-benin-togo-hero.webp"
		},
		"conference": "Workshop Researching Religion, Morality and Boko in West Africa",
		"location": "Martin-Luther-Universität Halle-Wittenberg",
		"country": "Germany"
	},
	"zmo-kitchen-talks-ai-islamic-african-studies": {
		"id": "zmo-kitchen-talks-ai-islamic-african-studies",
		"itemType": "communication",
		"title": "Artificial Intelligence (AI) in African and Islamic Studies",
		"authors": [
			"Elisa Nobel-Dilaty",
			"Frédérick Madore"
		],
		"type": "podcast",
		"date": "11 December 2025",
		"dateISO": "2025-12-11",
		"year": 2025,
		"image": "images/communications/zmo-kitchen-talks-logo.webp",
		"heroImage": {
			"src": "images/communications/zmo-kitchen-talks-logo.webp"
		},
		"conference": "ZMO Kitchen Talks",
		"location": "Leibniz-Zentrum Moderner Orient",
		"country": "Germany",
		"episode": 14
	}
};
