// AUTO-GENERATED by scripts/generate-reference-index.mjs — DO NOT EDIT.
// Regenerate with `npm run gen:refs` (runs automatically via the prebuild hook).
/* eslint-disable */
import type { ReferenceCitationEntry } from '$lib/types/referenceIndex';

export const referenceCitations: Record<string, ReferenceCitationEntry> = {
	"acteurs-religieux-numerique": {
		"itemType": "publication",
		"cite": "(Millet-Mouity and Madore, 2017)",
		"title": "Les acteurs religieux africains à l'ère du numérique"
	},
	"ai-archives-humanistica-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "Intelligence artificielle et traitement des archives numériques : applications et enjeux dans la Collection Islam Afrique de l'Ouest"
	},
	"ambition-federatrice-faitieres-islamiques-2026": {
		"itemType": "publication",
		"cite": "(Madore, 2026)",
		"title": "L'ambition fédératrice à l'épreuve de la diversité : étude comparative des faîtières islamiques au Burkina Faso, Togo, Bénin et Côte d'Ivoire"
	},
	"archives-algorithms-iwac-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "From Archives to Algorithms: Uncovering Transregional Islamic Connections through the Islam West Africa Collection (IWAC)"
	},
	"associations-chretiennes-islamiques-campus": {
		"itemType": "communication",
		"cite": "(Madore, 2022)",
		"title": "Les associations chrétiennes et islamiques sur les campus de l'Université d'Abomey-Calavi et de l'Université de Lomé depuis 1970: la laïcité à l'université face à l'activisme religieux"
	},
	"author-meets-critic-faith-activism-2024": {
		"itemType": "communication",
		"cite": "(Madore, 2024)",
		"title": "Author Meets Critic. Faith-based Student Activism in Togo and Benin: Muslims and Christians on University Campuses"
	},
	"beninese-imam-election-2022": {
		"itemType": "publication",
		"cite": "(Madore, 2022)",
		"title": "A Beninese Imam's Controversial 2019 Election Campaign: Muslim Leadership and Political Engagement in a Minority Context"
	},
	"beyond-keywords-ai-iwac-mcp-2026": {
		"itemType": "communication",
		"cite": "(Madore, 2026)",
		"title": "Beyond Keywords: AI-Mediated Access to the Islam West Africa Collection through an MCP Server and Agent Skill"
	},
	"charting-new-territory-digital-humanities-ki-african-studies-2026": {
		"itemType": "publication",
		"cite": "(Madore and Hiribarren, 2026)",
		"title": "Charting New Territory: Digital Humanities und Künstliche Intelligenz in den African Studies"
	},
	"collection-islam-afrique-ouest": {
		"itemType": "communication",
		"cite": "(Madore, 2024)",
		"title": "La Collection Islam Afrique de l'Ouest: nouvelles perspectives sur l'histoire des communautés musulmanes via la presse et les humanités numériques"
	},
	"collection-islam-humanites-2024": {
		"itemType": "communication",
		"cite": "(Madore, 2024)",
		"title": "La Collection Islam Afrique de l'Ouest: enjeux éthiques et décolonisation des humanités numériques"
	},
	"communaute-musulmane-burkina-faso-2014": {
		"itemType": "publication",
		"cite": "(Madore and Gomez-Perez, 2014)",
		"title": "Communauté Musulmane du Burkina Faso"
	},
	"current-dynamics-islam-burkina-faso": {
		"itemType": "communication",
		"cite": "(Madore, 2018)",
		"title": "Current Dynamics of Islam in Burkina Faso"
	},
	"defense-laicite-musulmans-burkina": {
		"itemType": "communication",
		"cite": "(Madore, 2019)",
		"title": "La défense de la laïcité de l'État, un outil de revendication politique pour les musulmans au Burkina Faso (depuis 1960)"
	},
	"dh-ai-african-studies-2025": {
		"itemType": "communication",
		"cite": "(Madore and Hiribarren, 2025)",
		"title": "Digital Humanities (DH) and AI in African Studies: Opportunities, Challenges, and Decolonial Perspectives"
	},
	"digital-history-exe": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "DigitalHistory.Exe: Running New Programs on Old Files"
	},
	"digital-hoarding-open-archives-warsaw-2026": {
		"itemType": "communication",
		"cite": "(Madore, 2026)",
		"title": "From Digital Hoarding to Open Archives: Using AI Agents to Unlock West African Newspaper Collections"
	},
	"digital-humanities-islam-burkina-faso": {
		"itemType": "communication",
		"cite": "(Madore, 2022)",
		"title": "Digital Humanities in the Making: The Islam Burkina Faso Collection"
	},
	"dormant-digital-collections-ai-triage-dga-2026": {
		"itemType": "communication",
		"cite": "(Madore, 2026)",
		"title": "Dormant Digital Collections, AI Triage: Lessons from the Islam West Africa Collection and Beyond"
	},
	"elites-musulmanes-cote-divoire-burkina-faso": {
		"itemType": "communication",
		"cite": "(Madore, 2018)",
		"title": "Les élites musulmanes en Côte d'Ivoire et au Burkina Faso depuis 1990 : des mobilisations politiques contrastées"
	},
	"emancipation-feminine-militantisme-islamique": {
		"itemType": "communication",
		"cite": "(Madore, 2022)",
		"title": "Émancipation féminine et militantisme islamique en Afrique de l'Ouest depuis 1980: quelques enseignements du Burkina Faso, de la Côte d'Ivoire, du Togo et du Bénin"
	},
	"etablir-faitiere-islamique": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "L'ambition fédératrice à l'épreuve de la diversité : étude comparative des faîtières islamiques au Burkina Faso, Togo, Bénin et Côte d'Ivoire"
	},
	"evolutions-nouvelles-formes-islam-afrique-ouest": {
		"itemType": "communication",
		"cite": "(CIRAM, 2016)",
		"title": "Évolutions et nouvelles formes de l'islam en Afrique de l'Ouest: vers une radicalisation?"
	},
	"exister-contexte-autoritaire-lome-2023": {
		"itemType": "publication",
		"cite": "(Madore, 2023)",
		"title": "Exister en contexte autoritaire : les associations étudiantes chrétiennes et islamiques à l'Université de Lomé sous Gnassingbé Eyadéma, 1970–2005"
	},
	"faith-based-student-organizations-2023": {
		"itemType": "communication",
		"cite": "(Madore, 2023)",
		"title": "'Too Young,' 'Immature,' and not Committed Enough: The Decline of Faith-Based Student Organizations in Togo and Benin?"
	},
	"formation-recherche-en-ligne-niamey": {
		"itemType": "communication",
		"cite": "(Madore, 2024)",
		"title": "Formation en recherche en ligne"
	},
	"formation-recherches-en-ligne-ouagadougou": {
		"itemType": "communication",
		"cite": "(Madore, 2023)",
		"title": "Formation en recherche en ligne"
	},
	"francophone-muslim-intellectuals-burkina-faso-2020": {
		"itemType": "publication",
		"cite": "(Madore, 2020)",
		"title": "Francophone Muslim intellectuals, Islamic associational life and religious authority in Burkina Faso"
	},
	"generations-imam-benin-2021": {
		"itemType": "communication",
		"cite": "(Madore, 2021)",
		"title": "Generations at Odds: The Controversial Political Candidacy of an Imam in Benin (2019)"
	},
	"good-muslim-bad-muslim-togo-2019": {
		"itemType": "communication",
		"cite": "(Madore, 2019)",
		"title": "'Good Muslim, Bad Muslim' in Togo: The Construction of a Religious Minority Amid a Constitutional Crisis (2017–2018)"
	},
	"good-muslim-bad-muslim-togo-2021": {
		"itemType": "publication",
		"cite": "(Madore, 2021)",
		"title": "'Good Muslim, bad Muslim' in Togo: religious minority identity construction amid a sociopolitical crisis (2017-2018)"
	},
	"hackett-interview-digital-media-2017": {
		"itemType": "publication",
		"cite": "(Hackett et al., 2017)",
		"title": "Interview with Rosalind I. J. Hackett on Religion and Digital Media Trends in Africa"
	},
	"hadj-cote-divoire-2018": {
		"itemType": "publication",
		"cite": "(Madore and Traoré, 2018)",
		"title": "L'organisation du hadj en Côte d'Ivoire: entre facteur de cohésion et source de rivalités au sein de la communauté musulmane (1993-2010)"
	},
	"hajj-organization-state-cote-divoire-2016": {
		"itemType": "communication",
		"cite": "(Madore, 2016)",
		"title": "The Organization of the Hajj and the State: Cohesion and Rivalries within the Muslim Community of Côte d'Ivoire (1993-2006)"
	},
	"histoire-communautes-musulmanes-ouest-africaines-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "L'histoire des communautés musulmanes ouest-africaines : approches et perspectives des humanités numériques"
	},
	"historian-vs-ai-ecas-2025": {
		"itemType": "communication",
		"cite": "(Hiribarren and Madore, 2025)",
		"title": "Historian vs AI: who reads and analyses archives best?"
	},
	"humanites-numeriques-dh-ia-etudes-africaines-reaf-2026": {
		"itemType": "communication",
		"cite": "(Hiribarren and Madore, 2026)",
		"title": "Humanités numériques (DH) et IA dans les études africaines"
	},
	"humanites-numeriques-ia-ecole-chartes-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "Humanités numériques et flux de recherche augmentés par l'IA pour la Collection islam Afrique de l'Ouest"
	},
	"imams-espace-public-ouagadougou-2012": {
		"itemType": "communication",
		"cite": "(Madore, 2012)",
		"title": "Imams et espace public à Ouagadougou depuis 1990: entre visibilité nouvelle et concertation entre les générations"
	},
	"imams-islamic-preachers-ouagadougou-2013": {
		"itemType": "communication",
		"cite": "(Madore, 2013)",
		"title": "Imams, Islamic Preachers and Public Space in Ouagadougou (Burkina Faso) since the 1990s: Toward New Intergenerational Relationships and a Muslim Public Sphere"
	},
	"imams-islamic-preachers-ouagadougou-2020": {
		"itemType": "publication",
		"cite": "(Madore, 2020)",
		"title": "Imams, Islamic Preachers, and Public Space in Ouagadougou (Burkina Faso) since the 1990s: Toward New Intergenerational Relationships and a Muslim Public Sphere"
	},
	"interfaith-coexistence-campuses": {
		"itemType": "communication",
		"cite": "(Madore, 2023)",
		"title": "Interfaith coexistence on the campuses of the University of Lomé (Togo) and the University of Abomey-Calavi (Benin) since the 1970s"
	},
	"introduction-religiosity-university-campuses-2023": {
		"itemType": "publication",
		"cite": "(Sounaye and Madore, 2023)",
		"title": "Introduction: Religiosity on University Campuses in Africa"
	},
	"islam-algorithms-ai": {
		"itemType": "communication",
		"cite": "(Madore, 2024)",
		"title": "Islam, Algorithms and AI"
	},
	"islam-burkina-cote-ivoire": {
		"itemType": "communication",
		"cite": "(Madore, 2017)",
		"title": "L'islam au Burkina Faso et en Côte d'Ivoire: éveil et radicalisation?"
	},
	"islam-burkina-faso-collection-2021": {
		"itemType": "publication",
		"cite": "(Madore, 2021)",
		"title": "La Collection Islam Burkina Faso : promesses et défis des humanités numériques"
	},
	"islam-burkina-faso-collection-omeka-2022": {
		"itemType": "communication",
		"cite": "(Madore, 2022)",
		"title": "Publishing the Islam Burkina Faso Collection with Omeka S"
	},
	"islam-ivoirien-burkinabe-numerique-2016": {
		"itemType": "publication",
		"cite": "(Madore, 2016)",
		"title": "L'islam ivoirien et burkinabé à l'ère du numérique 2.0"
	},
	"islam-medias-senat-burkina-faso-2016": {
		"itemType": "publication",
		"cite": "(Madore, 2016)",
		"title": "Islam, médias, mise en place du Sénat et article 37 de la Constitution: changement de paradigme au Burkina Faso (1991–2014)?"
	},
	"islam-peripheries-dh-ai-west-africa-central-asia-2026": {
		"itemType": "communication",
		"cite": "(Ismailbekova and Madore, 2026)",
		"title": "Islam's \"Peripheries\": Digital Humanities, Algorithmic Analysis, and AI in West Africa and Central Asia"
	},
	"islam-peripheries-open-up-2026": {
		"itemType": "communication",
		"cite": "(Madore and Ismailbekova, 2026)",
		"title": "Islam's \"Peripheries\": Digital Humanities, Algorithmic Analysis, and AI in West Africa and Central Asia"
	},
	"islam-university-campuses-cote-divoire-2019": {
		"itemType": "communication",
		"cite": "(Binaté and Madore, 2019)",
		"title": "Islam on University Campuses in Côte d'Ivoire since the 1970s: 'Muslim Intellectuals' and Francophone Salafism"
	},
	"islam-university-campuses-cote-divoire-2023": {
		"itemType": "publication",
		"cite": "(Madore and Binaté, 2023)",
		"title": "Islam on University Campuses in Côte d'Ivoire since the 1970s: Muslim Intellectuals and Francophone Salafism"
	},
	"launch-islam-west-africa-collection": {
		"itemType": "communication",
		"cite": "(Madore, 2023)",
		"title": "Launch of the Islam West Africa Collection"
	},
	"leaders-muslim-ngos-burkina-faso-2016": {
		"itemType": "publication",
		"cite": "(Couillard et al., 2016)",
		"title": "Leaders of National and Transnational Muslim NGOs in Burkina Faso: Diverse Forms and Experiences of Islamic Civic Engagement"
	},
	"lutte-terrorisme-salafisme-benin-togo-2022": {
		"itemType": "publication",
		"cite": "(Madore, 2022)",
		"title": "Lutte contre le terrorisme et sécuritisation du salafisme au Bénin et au Togo: instrumentalisations diverses d'une « menace étrangère »"
	},
	"madore-2024-launch-iwac": {
		"itemType": "publication",
		"cite": "(Madore, 2024)",
		"title": "Launch Islam West Africa Collection, 9 November 2023, MiCT, Berlin/Online"
	},
	"madore-2025-perspectives-in-motion": {
		"itemType": "publication",
		"cite": "(Madore, 2025)",
		"title": "Perspectives in Motion: Conceptual Fields from the Global South, Workshop, 2-3 December 2024, ZMO"
	},
	"madore-2026-conversation-coauthorship-dh-ai": {
		"itemType": "publication",
		"cite": "(Madore, 2026)",
		"title": "From Conversation to Co-authorship: A Workshop on Digital Humanities and AI in African Studies, 18–20 February 2026, Herrenhausen, Hanover"
	},
	"madore-2026-decentering-knowledge": {
		"itemType": "publication",
		"cite": "(Madore, 2026)",
		"title": "Decentering Knowledge: Concepts, Conceptualizations, Translations, 13–14 October 2025, ZMO"
	},
	"madore-2026-iwac-private-database-public-resource": {
		"itemType": "publication",
		"cite": "(Madore, 2026)",
		"title": "From Private Database to Public Resource to a Testing Ground for AI Methods: The Islam West Africa Collection (IWAC)"
	},
	"madore-islam-politique-ouagadougou-2013": {
		"itemType": "publication",
		"cite": "(Madore, 2013)",
		"title": "Islam, politique et sphère publique à Ouagadougou (Burkina Faso) : différentes cohortes d'imams et de prêcheurs entre visibilité nouvelle et reconfiguration des rapports intergénérationnels (1960-2012)"
	},
	"mediatisation-islam-ouagadougou-2013": {
		"itemType": "communication",
		"cite": "(Madore, 2013)",
		"title": "La médiatisation de l'islam à Ouagadougou depuis 1991: entre normalisation des discours et nouvelle agency des musulmans"
	},
	"militantisme-bissap-feminisme-islamique-2018": {
		"itemType": "communication",
		"cite": "(Madore, 2018)",
		"title": "'Militantisme bissap', féminisme islamique et entrepreneuriat religieux en Côte d'Ivoire: Aminata Kane Koné, une figure de la réussite"
	},
	"militantisme-islamique-campus-lome": {
		"itemType": "communication",
		"cite": "(Madore, 2022)",
		"title": "Militantisme islamique sur le campus de l'Université de Lomé (Togo) depuis les années 1980: être musulman en contexte minoritaire, laïc et (semi-)autoritaire"
	},
	"militantisme-islamique-feminin-burkina-2019": {
		"itemType": "communication",
		"cite": "(Madore, 2019)",
		"title": "Militantisme islamique féminin au Burkina Faso: des processus sinueux d'émancipation religieuse"
	},
	"militantisme-religieux-campus-benin-togo-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "Militantisme religieux sur les campus universitaires : le cas du Bénin et du Togo"
	},
	"muslim-feminist-media-cote-divoire-2020": {
		"itemType": "publication",
		"cite": "(Madore, 2020)",
		"title": "Muslim Feminist, Media Sensation, and Religious Entrepreneur: Aminata Kane Koné as a Figure of Success in Côte d'Ivoire"
	},
	"muslim-intellectuals-francophone-salafis": {
		"itemType": "communication",
		"cite": "(Madore, 2020)",
		"title": "'Muslim Intellectuals' and 'Francophone Salafis' in West Africa: New Religious Elites?"
	},
	"muslim-minorities-africa-1": {
		"itemType": "publication",
		"cite": "(Madore and Schulz, 2021)",
		"title": "Muslim Minorities in Africa, Part 1"
	},
	"muslim-minorities-africa-2": {
		"itemType": "publication",
		"cite": "(Madore and Schulz, 2022)",
		"title": "Muslim Minorities in Africa, Part 2"
	},
	"muslim-minorities-africa-2019": {
		"itemType": "communication",
		"cite": "(Madore, 2019)",
		"title": "Muslim Minorities in Africa"
	},
	"muslim-women-burkina-faso-2016": {
		"itemType": "publication",
		"cite": "(Madore and Gomez-Perez, 2016)",
		"title": "Muslim Women in Burkina Faso since the 1970s: Toward Recognition as Figures of Religious Authority?"
	},
	"nouveau-dynamisme-salafisme-cote-divoire-2017": {
		"itemType": "communication",
		"cite": "(Madore, 2017)",
		"title": "Le nouveau dynamisme du salafisme en Côte d'Ivoire: vers une radicalisation de l'islam ivoirien?"
	},
	"plan-brouillon-structurer-idees-2021": {
		"itemType": "publication",
		"cite": "(Madore and Brassard, 2021)",
		"title": "Du plan au brouillon : l'essentiel pour structurer ses idées et éviter le syndrome de la page blanche"
	},
	"point-de-passage-frontieres-religieuses": {
		"itemType": "communication",
		"cite": "(Madore, 2022)",
		"title": "Point de passage et frontières religieuses"
	},
	"political-mobilizations-burkina-faso": {
		"itemType": "communication",
		"cite": "(Madore, 2020)",
		"title": "Political mobilizations in Burkina Faso"
	},
	"precheurs-musulmans-burkina-faso-2013": {
		"itemType": "publication",
		"cite": "(Gomez-Perez and Madore, 2013)",
		"title": "Prêcheurs(ses) musulmans(es) et stratégies de communication au Burkina Faso depuis 1990. Des processus différentiés de conversion interne"
	},
	"precheurs-precheuses-burkina-faso-2013": {
		"itemType": "communication",
		"cite": "(Gomez-Perez and Madore, 2013)",
		"title": "Prêcheurs et prêcheuses au Burkina Faso: regards croisés sur leurs stratégies de communication religieuse depuis 1990"
	},
	"presentation-discussion-religious-activism-campuses-ciram-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "Présentation-discussion de l'ouvrage Religious Activism on Campuses in Togo and Benin"
	},
	"public-islam-cote-ivoire-burkina-faso": {
		"itemType": "communication",
		"cite": "(Madore, 2020)",
		"title": "Public Islam in Côte d'Ivoire and Burkina Faso: a comparative overview of the use of media by Muslims since the 1970s"
	},
	"publishing-islam-burkina-faso-collection-2022": {
		"itemType": "communication",
		"cite": "(Madore and Collins, 2022)",
		"title": "Publishing the Islam Burkina Faso Collection: Collaboration for Digital Scholarship"
	},
	"questions-islam-afrique-ouest-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "Questions d'islam en Afrique de l'Ouest. Les enjeux et défis de la recherche avec les archives physiques et numériques"
	},
	"recherche-documentaire-zotero": {
		"itemType": "communication",
		"cite": "(Madore, 2019)",
		"title": "La recherche documentaire en libre accès et la gestion de références bibliographiques avec Zotero"
	},
	"reconfiguring-archive-amira-2026": {
		"itemType": "communication",
		"cite": "(Madore, 2026)",
		"title": "Reconfiguring the Archive: Relationality and Discovery in the Africa Multiple Interactive Research Atlas (AMIRA)"
	},
	"religieux-internet-ntic-burkina-faso-2019": {
		"itemType": "publication",
		"cite": "(Madore and Gosselin, 2019)",
		"title": "Le religieux sur Internet et dans les NTIC au Burkina Faso"
	},
	"religion-internet-burkina-faso-2024": {
		"itemType": "publication",
		"cite": "(Madore and Gosselin, 2024)",
		"title": "Religion on the Internet and New Information and Communication Technologies in Burkina Faso"
	},
	"religions-numeriques-afrique-2018": {
		"itemType": "publication",
		"cite": "(Hiribarren et al., 2018)",
		"title": "Religions numériques en Afrique"
	},
	"religiosity-university-campuses": {
		"itemType": "publication",
		"cite": "(Sounaye and Madore, 2023)",
		"title": "Religiosity on University Campuses in Africa: Trends and Experiences"
	},
	"religious-activism-campuses": {
		"itemType": "publication",
		"cite": "(Madore, 2025)",
		"title": "Religious Activism on Campuses in Togo and Benin: Christian and Muslim Students Navigating Authoritarianism and Laïcité, 1970–2023"
	},
	"religious-actors-digital-era-2017": {
		"itemType": "publication",
		"cite": "(Millet-Mouity and Madore, 2017)",
		"title": "Pour de nouvelles études sur les acteurs religieux africains à l'ère du numérique"
	},
	"rencontre-chretiens-musulmans-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "Rencontre entre chrétiens et musulmans: au-delà du binaire coexistence pacifique/conflits religieux"
	},
	"repenser-categorisation-religieuse-benin": {
		"itemType": "communication",
		"cite": "(Madore and Anato, 2024)",
		"title": "Repenser la catégorisation religieuse à partir du Bénin, terre du vodun"
	},
	"repenser-categorisation-religieuse-benin-2026": {
		"itemType": "publication",
		"cite": "(Madore and Anato, 2026)",
		"title": "Repenser la catégorisation religieuse à partir du Bénin, terre du Vodun"
	},
	"representations-islam-muslims-togo": {
		"itemType": "communication",
		"cite": "(Madore, 2020)",
		"title": "Representations of Islam and Muslims in Togo's State-Owned Newspapers Since the 1960s: From Loyal Religious Minority to Potential Threat"
	},
	"retour-note-synthese-dh-ia-reaf-2026": {
		"itemType": "communication",
		"cite": "(Hiribarren and Madore, 2026)",
		"title": "Retour sur une note de synthèse analysant la relation entre Humanités Numériques, l’IA et les Études Africaines (Hanovre, février 2026)"
	},
	"rivalites-collaborations-islamiques-cote-ivoire-burkina-faso-2018": {
		"itemType": "publication",
		"cite": "(Madore, 2018)",
		"title": "Rivalités et collaborations entre ainés et cadets sociaux dans les milieux associatifs islamiques en Côte d'Ivoire et au Burkina Faso (1970-2017)"
	},
	"rue-islam-associatif-enjeux-citoyens-2014": {
		"itemType": "communication",
		"cite": "(Gomez-Perez et al., 2014)",
		"title": "Rue, islam associatif et enjeux citoyens: retour sur des orientations récentes au Sénégal, au Burkina Faso et en Côte d'Ivoire"
	},
	"salafism-cote-divoire-2016": {
		"itemType": "publication",
		"cite": "(Madore, 2016)",
		"title": "The New Vitality of Salafism in Côte d'Ivoire: Toward a Radicalization of Ivoirian Islam?"
	},
	"salafism-cote-ivoire-mande-2017": {
		"itemType": "publication",
		"cite": "(Madore, 2017)",
		"title": "Le nouveau dynamisme du salafisme en Côte d'Ivoire: vers une radicalisation de l'islam ivoirien?"
	},
	"salafisme-pentecotisme-campus-benin-togo": {
		"itemType": "communication",
		"cite": "(Madore, 2021)",
		"title": "Salafisme et pentecôtisme sur les campus au Bénin et au Togo: la laïcité à l'université face à l'activisme religieux"
	},
	"salafisme-securitisation-benin-togo-2022": {
		"itemType": "communication",
		"cite": "(Madore, 2022)",
		"title": "Salafisme et sécuritisation de l'islam au Bénin et au Togo: instrumentalisations diverses d'une 'menace étrangère'"
	},
	"sphere-publique-musulmane": {
		"itemType": "publication",
		"cite": "(Madore, 2016)",
		"title": "La construction d'une sphère publique musulmane en Afrique de l'Ouest"
	},
	"stias-dh-ai-african-studies-workshop-2026": {
		"itemType": "communication",
		"cite": "(Madore et al., 2026)",
		"title": "Digital Humanities and Artificial Intelligence in African Studies: Towards Sustainable and Equitable Practices"
	},
	"three-questions-madore-2022": {
		"itemType": "publication",
		"cite": "(Zein and Madore, 2022)",
		"title": "Three Questions to Dr. Frédérick Madore"
	},
	"tracing-islamic-knowledge-production": {
		"itemType": "communication",
		"cite": "(Madore, 2024)",
		"title": "Tracing Islamic Knowledge Production in Francophone West African Newspapers (1990-Present)"
	},
	"union-islamique-benin-elections": {
		"itemType": "communication",
		"cite": "(Madore, 2019)",
		"title": "L'Union Islamique du Bénin et les élections législatives: comment comprendre la crise interne"
	},
	"university-campuses-africa-beyond": {
		"itemType": "communication",
		"cite": "(Sounaye and Madore, 2023)",
		"title": "University Campuses in Africa and Beyond: Training Grounds, Moral Spaces and Political Arenas"
	},
	"uppsala-university-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "Building AI Pipelines for African Digital Collections: Lessons from the Islam West Africa Collection"
	},
	"volkswagenstiftung-dh-ai-african-studies-workshop-2026": {
		"itemType": "communication",
		"cite": "(Madore and Hiribarren, 2026)",
		"title": "Charting New Territory: Digital Humanities and AI in African Studies"
	},
	"when-ai-meets-the-archive-2025": {
		"itemType": "communication",
		"cite": "(Madore, 2025)",
		"title": "When AI Meets the Archive: Transforming the Islam West Africa Collection with Large Language Models"
	},
	"workshop-religion-in-higher-educational-institutions-2021": {
		"itemType": "communication",
		"cite": "(Sounaye et al., 2021)",
		"title": "Workshop “Religion in Higher Educational Institutions in Africa and Beyond: (Re)Conversion, Power, and Authority from a Comparative Perspective”"
	},
	"workshop-religions-on-campus-2022": {
		"itemType": "communication",
		"cite": "(Sounaye et al., 2022)",
		"title": "Workshop “Religions on Campus: Coexisting Traditions, Reformulating the Secular and Life Projects”"
	},
	"young-muslims-civic-engagement-burkina": {
		"itemType": "communication",
		"cite": "(Madore, 2018)",
		"title": "'Plus rien ne sera jamais comme avant'? Young Muslims' new forms of civic engagement in Burkina Faso (2014-2017)"
	},
	"yovo-historian-benin-togo": {
		"itemType": "communication",
		"cite": "(Madore, 2022)",
		"title": "A 'Yovo' Historian in Benin and Togo: Conducting Fieldwork in Times of Pandemic and Fears of Jihadism Spreading"
	},
	"zmo-kitchen-talks-ai-islamic-african-studies": {
		"itemType": "communication",
		"cite": "(Nobel-Dilaty and Madore, 2025)",
		"title": "Artificial Intelligence (AI) in African and Islamic Studies"
	}
};
